### ISSUE TITLE
Official jammer names

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1022]
Currently hiding units from radar in a radius is called "jammer" and hiding only oneself is called "stealth".

Consider whether to adopt the following naming scheme for purposes such as patch notes, guides or wikis:

* jammer -> area jammer
* stealth -> personal jammer

The area/personal adjective is consistent with how shields and cloak are named.
Calling both "jammer" reflects the fact that both apply the same effect.
"Stealth" is slightly ambiguous (newbies might confuse it with cloak).

**Comment by GoogleFrog** [comment]
If stealth were not slightly ambiguous I would prefer the term because it has better verbing. A unit which is radar invisible can be called a "Stealth X" but not a "Jam X" (at best we have "Jammed X" or "Personal Jamming X"). The same problem applies to the word "Cloak" and many descriptions try to get around this with ill-defined words such as "Infiltration".

I have just removed radar invisibility from every reachable unit (except for Claw). There is no longer any completely personal stealth so we have a similar situations to large and small shields. Small shields are not actually called 'Personal'. Thug and Felon are "Shielded" and that is the end of their consistency.

**Comment by KingRaptor** [comment]
"cloaked"

I think the one place that uses "personal shield" is the comm module?

**Comment by sprunk** [comment]
It was not really about the unit descriptions but about various places where the features have to be named, for example patch notes, wikis or space+click menu. However, with stealth removed, the issue is solved.
