### ISSUE TITLE
Command Panel shouldn't show tabs when irrelevant

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K#1025]
The Command Panel has unnecessary visual noise with the tabs when things other than constructors, commanders, or factories are selected. It should only show tabs when the selected units have buttons in them, ideally granularly enough that, for example, when a factory is selected it doesn't show the "Factories, Econ, etc" tabs, just Orders and Units.

**Comment by GoogleFrog** [comment]
Sounds complicated, how about just greying out and unpressabling the button when nothing is in the tab?

**Comment by dvr333** [comment]
Well, what about have the tabs hidden by default, then when a builder or factory is selected they show but the invalid ones are greyed out and unpressable.

**Comment by GoogleFrog** [comment]
The tabs form the edge of the UI and main battle. I think changing the shape of that border when unit selection changes draws too much attention to that area.

**Comment by dvr333** [comment]
That's true, I suppose that would happen even if the main command UI didn't change size (though keeping that size consistent would help). Greying out is worth doing in either case.

**Comment by GoogleFrog** [comment]
The Units tab could move next to the Order tab, that would mostly resolve the convex UI problem if the tab is hidden. I lean towards hiding the tabs because no tabs should be visible when no unit is selected. Alternately we could grey out all tabs when nothing is selected, even the technically active tab.

Greying out the tabs might be problematic as the tabs are already semitransparent when unselected. However, we could change the text colour.

**Comment by mtroyka** [comment]
I think we should hide any tab that isn't relevant to the selected units. For example glaives should not show any of the build tabs, etc. Hiding them entirely when no units are selected is probably preferable, and consistent with other games.

**Comment by GoogleFrog** [comment]
Fixed variously.
