### ISSUE TITLE
infolog.txt is spammed with [Warning] and [Error]

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K#1041]
please fix them, they make finding real errors / problems a mess. also infolog.txt is bloated with useless crap infos because of this.

the spam hides real warnings and errors which are important to see to fix real issues!

**Comment by abma** [comment]
i.e.:
Warning: [CCEG::Load] table for CEG "custom:gravityless_flamer" invalid (parse errors?

**Comment by abma** [comment]
~2.5k (!!!) lines of useless warnings are currently in infolog.txt when zk is run.

**Comment by GoogleFrog** [comment]
The "Error: Unable to open audio" appear to be an engine limitation. We did not want sounds to automatically occur for these actions so we set the sounds to nil in sounds.lua. The engine should respect that.

The only other errors I get are due to broken maps.

The weapondef warning should be fixed in the relevant files. Don't use weapondefs_posts because that makes the warnings pointless.

**Comment by GoogleFrog** [comment]
abma get grammar and less colloquial "rage speak" (not sure of a good term) such as "bloated with useless crap infos".

**Comment by abma** [comment]
sorry for the rage. but this problem was reported several times and it makes more time needed for all people when opening/uploading/.... the logfile.

**Comment by abma** [comment]
thanks! the spam imo is fixed (some warnings are left, but okish)
