### ISSUE TITLE
open serious host 

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#1050]
serious contains:
- no commorphs
- no team trolling including resign after one or little fail attempt,
meh f*** this.

just deny players who have marked as repeating trolly or pushing down their elo on purpose or got a lot of complains about team uncooperative behaviour.

-

**Comment by Licho1** [comment]
Commanders can be disabled using existing modoptions. 
Player behavior fix needs a giant spider-like device that invades brain and takes control. 
It's construction is currently out of scope of this project, please try contacting NSA or other well funded agency.

**Comment by Jamanno** [comment]
open a private serious host seemed to fix most of the trolling and it wouldn't be that hard or?

**Comment by knorker** [comment]
One reason the current serious host fails is because the maps are not serious.
It is not about tweaking player's brains but having the settings of host reflect its title.

When joining a host titled "serious" one expects somewhat skillful matches or at least normal RTS gameplay. Instead there is always the risk of silly lolmaps (trololo, duck, Finnishflag) or cluster games with too large teams on too small maps.

Compare to the "Experienced Host" that failed to gain popularity because of matches like this:
http://i.imgur.com/5SCBQUc.png
That was not "experienced" or "serious", players who look for such playstyle were disappointed and leave.

Also look at history of the "Small Teams" room that started as 3v3, but then grew to 5v5:
http://i.imgur.com/4FOU4qw.png
At that point the players who had wished for such host did not consider it good host anymore.

A serious host, to be accepted by 'serious' players should at least:
-have sensible map list
-sensible room size (imo: 3v3, at MAX 4v4)
-no bots/chicken
-stay with same settings for a while, so players can develop trust
