### ISSUE TITLE
Shield modules not centered properly

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#1079]
![screen00591](https://cloud.githubusercontent.com/assets/132906/10269299/e77660fe-6ad2-11e5-8a36-065e30307550.png)
![screen00597](https://cloud.githubusercontent.com/assets/132906/10269298/e774ca82-6ad2-11e5-9a72-e6d2a3a18adc.png)
![screen00595](https://cloud.githubusercontent.com/assets/132906/10269300/e779a476-6ad2-11e5-820e-3c08792513dc.png)

As commanders turn around it's very easy to notice that their shields turn with them. When a commander turns 180° its shield moves from (example) west to east of the commander.

http://zero-k.info/Battles/Detail/378633

**Comment by GoogleFrog** [comment]
This is most likely caused by them being emitted from non-empty pieces. The center of a non-empty piece does not appear to be the origin in upspring. It may be the top left vertex of the geometry (just looking at strike comm).

I noticed this and fixed it for the commanders which are now in use by emitting the shields from pieces with less geometry.
