### ISSUE TITLE
Catapult goes on melee attack

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1086]
When you attack a mobile unit with catapult, it sometimes closes to this unit instead of keeping max distance. This happens with default settins (hold pos) and with targets like bantha or funnel.

**Comment by GoogleFrog** [comment]
This is only fixable by making Catapult ignore all occlusion when targeting. The attack command means "Move to somewhere where you can fire and then fire". Catapult is often blocked.

**Comment by sprunk** [comment]
Preventing moving into better position is achieved by using set-target instead of attack.

Hold pos is implemented by engine so ZK probably can't do anything?

**Comment by GoogleFrog** [comment]
My only fix for this would be to have a command which is an attack command when outside weapon range and a set target command when inside weapon range. This would have its own issues because catapults would not move to fire past obstacles.

I'll give them strafeToAttack and see if the tag does anything.
