### ISSUE TITLE
[Feature Request] Oversized Nullfacs for AI Placement Checking

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1170]
Currently getting an AI to build facs without the fac getting blocked either by terrain or other buildings or whatever is rather difficult, expensive and unreliable. It would be a lot easier if there were oversized null factories that could be used for placement checking.

The idea is something like this:
You have a couple of different nullfacs which represent various placement restrictions, such as for hoverfac or shipfac or general land-only facs. The nullfacs should have all-blocking yardmaps and should all be at least shipfac sized. For shipfac an even bigger nullfac would be better. That way you can easily guarantee that there will be enough space in front of the fac (also properly accounting for facing) to build big units (important for amphs and jumps and possibly spiders) and ensure that big units do not get stuck trying to leave the yard.

On a slightly unrelated note I've also seen spiderfacs get stuck for seemingly no reason (there didn't appear to be any blocking terrain, let alone something spiders can't cross).

**Comment by GoogleFrog** [comment]
Can you not do this with existing units? I am wary of putting this gameside because the unitdef would have no internal purpose so there is no motivation to maintain it. Then we would have a bug with an AI which could be fixed by changing an obscure unitDef which nothing appears to use. I really dislike that situation.

Think for a bit longer and try to find a robust solution using what we already have. For example if you are building an East facing factory here:

ooooooooo
oooxxxxooo
oooxxxxooo
oooxxxxooo
oooxxxxooo
ooooooooo

(placing a 4x4 factory. o is open, x is factory placement)

you could check for pathablility by also checking whether the factory can be built at this location

ooooooooo
ooooooxxxx
ooooooxxxx
ooooooxxxx
ooooooxxxx
ooooooooo

**Comment by mtroyka** [comment]
That wouldn't work right, for example with amph fac since a grizzly may be 4x the size of the fac in the facing direction. Maybe if there were some sort of oversized campaign-only buildings that would work, but I don't know anything about that.

Also the placement restrictions are important because "find nearest build site" otherwise does not return anything sensible. I'll see if there isn't a better solution, but I don't think that there is.

**Comment by DeinFreund** [comment]
I would not recommend using findnearestbuildsite because it can lag the
engine, build things on mexspots and interfere with planned buildings(ie
grid planning). But if u still want to use it I agree that fake unitdefs
would be the easiest way to get better fac placement.

**Comment by sprunk** [comment]
This solution is undesired (double maintenance of a thing with no immediate purpose visible) and a different solution (make sides open) was decided upon (#1586).
