### ISSUE TITLE
Do something with people who have marker spam widgets

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K#1200]
1) Maybe matter of taste but in replays LOS should not be enabled by default:
Pre-game the map is all darkend, looks stupid.
It is 'random' which team gets the LOS-fog drawn which is inconsistent because units of all teams are visible.
There is option "always enable LOS" (or similiar named) but it is not seperate for replay.

2) The automatically placed factory markers look stupid/cluttered in replays.
![markerspam](https://cloud.githubusercontent.com/assets/3044855/12330327/dcac5b08-bae4-11e5-95ef-cf4d97c74070.jpg)
When watching replay those markers are not nessecary I think, it is spammy and looks bad.

**Comment by Anarchid** [comment]
I often like watching my replays just to read what spectators chatted about.

**Comment by knorker** [comment]
Nothing wrong with chat, but the automatic factory markers are spam.
Small startboxes, many players = game gets uglified in first minute.

**Comment by Anarchid** [comment]
But often parts of the chat are in markers and there is no easily telling a human marker from a robot marker.  

Maybe i just don't spec `bad local optimum` games. Maybe one shouldn't!

Duel purist viewpoint: dont save replays for game sizes of over 4 except for admin purposes.

**Comment by GoogleFrog** [comment]
1) LOS in replays is good because you can see what each team can see. It is random which team starts with their LOS shown but you can change the team shown by selecting the units of a particular team. It is interesting information and I don't think it is confusing that there are units in non-LOS areas.

LOS pregame is perhaps a problem for dark maps. The LOS toggling widget could be changed for everyone to disable LOS pregame and then enable it at the start.

2) Marker spam on factories is a problem restricted to spectating a few players. Some players are using local widgets which spam everyone with "factory spotted" markers. To fix this issue we should talk to people who spam factory markers and tell them to remove or fix their widgets. ZK has an inbuilt option to enable factory marking and this implementation does not spam everyone else with markers.

**Comment by knorker** [comment]
1) 
>  I don't think it is confusing that there are units in non-LOS areas.

I think otherwise. Compare to Starcraft or other games, where you see LOS of both teams.
Idk if possible in spring, but currently is not nice.

2) There is enabled=true widget in mod: https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/unit_marker.lua

Imo widget-placed markers and player-placed-no-text markers should disappear after some time: Usually no-text markers lose their meaning quickly. The ghost of scouted factories can still be seen outside LOS.
Spring map-drawing system is nice but sometimes marker-cluttered map looks super-ugly. I think to outsiders it is very irritating.
The /clearmapmarks-button deletes too much and players should not have to think about such stuff.

**Comment by GoogleFrog** [comment]
The included unit marker widget does nothing unless the player tells it to mark units through the ingame menu. So nobody sees it until they ask for the units to be marked.

**Comment by GoogleFrog** [comment]
Non-LOSed pregame map is implemented. I am not sure about the rest of this, all I would do is tell people who have marker spam widgets to not use them.

**Comment by knorker** [comment]
A player can tick an option in menu and then OTHER players get spammed with markers.
That seems wrong.
The markers should be local only. If a teammate wants to see automaticaly marked units too, he can tick the option himself.

**Comment by GoogleFrog** [comment]
That doesn't happen. The markers are local. As you said:
> edit: ah, the widget has 'markingActive = false', but still
To reiterate, all the exists in ZK widgets is a default-off option to locally mark certain units.

**Comment by sprunk** [comment]
1) is done so renamed for 2).

**Comment by sprunk** [comment]
I asked some people with the spamwidget to disable it but they refused to obey. Most likely we'll need to use the widget handler to modify the MarkerAddPoint callout.
