### ISSUE TITLE
Simple Command Card mode

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1248]
Most of the commands in the orders menu are not required for new players. Wait, Set Target, Cancel Target are some obvious ones but we can further tune the list. Integral menu should have an option to remove the extraneous commands. It should be on by default.

**Comment by Licho1** [comment]
set target is quite useful but can be done with mouse, wait is not very important (can be replaced by priorities).

**Comment by Anarchid** [comment]
Doing settarget with mouse would require a modifier key, or a way to reliably bind extra mouse buttons.

My attempts to bind mouse6 and mouse7 to settarget have failed.

**Comment by Licho1** [comment]
Err its double click..

**Comment by Anarchid** [comment]
Single RMB click already sets target because attack sets target. Does double RMB settarget without issuing attack? 0_o

**Comment by GoogleFrog** [comment]
You are both missing the point. There are commonly 12+ commands on the command card and that many icons is too much for a new player to figure out. Displaying them to new players is not so much about whether they are useful, it is about whether they need to see them.

**Comment by dvr333** [comment]
Guard/Assist, Move, Repair, Attack (though not onto radar shapes/into FoW), and apparently Set Target all work with RMB, so they are easy candidates for being removed to just have something that says "use RMB for actions" (cf. StarCraft 2's default UI). That leaves Fight, Patrol, and Stop (and maybe Attack for the FoW case. Clear Target could but for a simple UI I'd omit it) as explicit orders for all units, along with construction tabs and unit states.

Ferry Route and Retreat Zone should be their own widget or in the minimap commands anyway, since they are more global area states rather than unit commands. This would also allow the command panel to only be shown when units are selected (as an option most likely).

Licho: Wait isn't super useful for constructors, but it can be useful for army coordination: ex. Select Group -> Line Move > Wait > Line Move; Select Group 2 -> Line Move > Wait > Line Move; Wait until both groups reach their wait point; Select Groups 1 and 2 -> (un)Wait.

**Comment by GoogleFrog** [comment]
Todo:
- Make a widget that can merge multiple gadget-side state commands into one widget-side state command. Use it to merge Priority and Misc Priority and to merge Firestate/Movestate into HoldFire+Position, HoldPosition+FireWill, HoldPositon+Maneuver (Passive, Defensive, Aggressive).
- Make more fitting images for the state commands that made it into simple settings.
- Make the order of commands more stable, and devise a good order.
- Add simple command mode to simple interface settings.

**Comment by GoogleFrog** [comment]
Fixed since then by completing the WIP.
