### ISSUE TITLE
Dynamic commander spawn pulls 1000 energy

### ISSUE THREAD

**Issue by rlcevg** [ZeroK-RTS/Zero-K#1252]
Happens from 1.4.2.2 but wasn't visible in UI panel.
It is visible in UI now with dev version (commit f6173ca45381b5ea51e6fa15e14f2174139b2f39).

The issue affects AI's first economy steps (forces to build energy instead of mex).

Doesn't happen with "forcejunior" modoption.

**Comment by GoogleFrog** [comment]
It pulls 100 energy. You should be able to detect and deal with this case because it is lost to excess. Players now start with 600 resources and 100 is then lost to overflow.

The base cost of commanders changed from 1200 to 1000 which automatically increased the starting resources from 400 to 600. I have fixed this but you should probably handle excess.
