### ISSUE TITLE
Human Readable AllyTeam Names

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1282]
The startboxes API could include names for the AllyTeam which inhabits each startbox. This would be an improvement over the current "Team 1" and "Team 2" which is displayed in various widgets.

Startboxes could autodetect to call a team North, South, East or West from most current engine box setups. The API could contain custom names for maps with polygon startbox setups.

**Comment by sprunk** [comment]
Figure out some good names to call the teams in weird-numbered FFAs.
In 3-way and 6-way they could be eg. "X o'clock".
5, 7,  and 9+ are problematic but such maps exist. Perhaps let them stay "team X".

**Comment by GoogleFrog** [comment]
Name the AllyTeam with 1 team after the player on that team. The only case we miss is multi-team FFA. There we can just call them Team 1, Team 2 etc...

Also you could look into the clan detection. If a team has at least 2 players and all players are of the same clan then the team could have the name of the clan, provided that no other team would also have that name. The spectator stats gadget does this but I think it was only intended for two allyTeams.

**Comment by sprunk** [comment]
For multi-team FFA they could be called after the highest ranked (any, in general) member, eg "Team Saktoth".

What should a player see when the real name is not supposed to be shown?
For example the boxes are North, South, East and West and all-shuffle is enabled. The player's team is (say) North but the other teams shouldn't use these names because that defeats shuffle. The best way seems to be to use the multi-team FFA convention in this case. What of spectators then though? Should they use "Team North" (better for identification, but inconsistent) or "Team Saktoth" (consistent with what players see, but worse for identifying teams)?

**Comment by GoogleFrog** [comment]
In the case of shuffle use "Team Saktoth" for everyone. Ideally the interface would merely be a GameRulesParam which is set at the start of the game.

**Comment by Anarchid** [comment]
A cunning plan:
1) Obtain Team Saktoth generator from current attrition counter (it's derived from spec ui thing, but is fixed to not crash and tolerate AI teams and mixed teams)
2) Put it into GRP 
3) Use identical team names in each widgets that needs them.

**Comment by sprunk** [comment]
There is now a pair of GameRulesParams per allyTeam which contains its names.

"allyteam_long_name_" .. allyTeamID
"allyteam_short_name_" .. allyTeamID

The short one is mostly due to potentially long clan names (eg. "MM" vs "Mean Machines") but map-defined boxes can also supply a short version (for example "5 o'clock" vs "5oc").

**Comment by sprunk** [comment]
Left to do is to make our Lua {ga,wi}dgets use this.

**Comment by sprunk** [comment]
Crude Player List (ie. the default player list) has an "ally team" column which currently just says the number and doesn't really have room even for the short-notation team name. It's probably alright to keep it this way. Perhaps a line break between the teams (so the number won't be needed as the teams are continuous blocks) and add the team name at the top -- Deluxe already does pretty much that.

**Comment by sprunk** [comment]
Resign votes need to be parsed and the vote widget should show the new name.
