### ISSUE TITLE
chat should not disappear by default

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#1302]
For experienced players might useful (they can set it to disappear), for complete newbies might not since they discover the GUI by time.
I had the problem by myself also after 1 year to recognize Chat because so much stuff going.
Useful hints might lost due to this chat disappearing.
Most players will read it maybe after 1 min or so or see, the chatlines after a bit of time...

**Comment by sprunk** [comment]
Imo it's in large part a problem of chat being a cesspool where all messages go.

"Unit under attack" - massive spam, even though this is already done by minimap circle events.
"Giving units due to afk" - nobody except the receiving guy cares and he gets a ton of labels on his new units already.

etc.

**Comment by Licho1** [comment]
It appears if someone says something so i think its perfectly fine.

**Comment by Jamanno** [comment]
Maybe you got me wrong here.
That is exactly the point. Most new players will _not_ notice it..
and they do not get the chance to notice it when it disappears.

**Comment by Licho1** [comment]
For notifications there should be the big things based on all avatar chat. They could be shown when you mention player name too.
But lots of game use hiding chat by default.
If you press enter it reappears.

**Comment by GoogleFrog** [comment]
I don't think that finding chat is particularly important.
