### ISSUE TITLE
Set Nanoframe Death Feature Team

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1305]
[7:18 PM]  Rafal[ZK] random bug i noticed: debris left after killing a nanoframe shows "noname" in tooltip instead of player name
[7:19 PM]  Rafal[ZK] while debris left after killing funnly built units shows correct player name
[7:19 PM]  Rafal[ZK] fully built*

https://springrts.com/mantis/bug_report.php

**Comment by sprunk** [comment]
Not dev engine I think? This has been happening for ages.

**Comment by sprunk** [comment]
Looks like that callout doesn't actually work.

**Comment by CarabusX** [comment]
Wasn't dev engine btw.

**Comment by GoogleFrog** [comment]
Dev engine tag was to wait to revisit when dev engine changes.

**Comment by GoogleFrog** [comment]
Also there is no way that setting the AllyTeam of a feature is going to make the tooltip widget able to read the features Player Name correctly.

**Comment by sprunk** [comment]
It's tested and works. There were two patches, first one added the team (https://github.com/ZeroK-RTS/Zero-K/commit/d30198c1d26bb57c486d3cff9dd358bdc737ade6) but apparently the tooltip checks for allyteam too so this was added in the second (https://github.com/ZeroK-RTS/Zero-K/commit/4c10a2a0338d37edd81f54b6d56b8cce4163963b).

Won't need revisiting because it already works (but not closing in case you meant something else).

**Comment by CarabusX** [comment]
Glad that my suggestion to set proper allyTeam in addition to just team, worked :)

**Comment by GoogleFrog** [comment]
Ah, the commits have the same name.
