### ISSUE TITLE
Better nano managment

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K#1335]
I noticed players noticing that their nano-towers would not automatically help and become idle.
I had same problem. 
I think it is because of "Nanotower idle seconds" defaults to 0. (0 = never)

![zk_nanos_patrol_0seconds_inactive](https://cloud.githubusercontent.com/assets/3044855/13729815/3b477864-e93e-11e5-8169-ba0081722d6b.png)

1) Build Nano
2) Nano gets patrol-command
3) Nano is helping things inside range
4) Give an order to Nano (for example repair your Commander instead of helping factory)
5) Nano complets order
6) Nano now sits idle

Of course one can "restart" the Nano with player-given patrol command but that is unclear to new players.

There was some speculation in chat why the nanos were idle ("No energy?" etc) and I think it is diffuclt to see if a nano is correctly idle (no res, out of range etc) or 'bugged.'
Maybe Nanos should have an ON/OFF state that is clearly visible in their GUI and in their model.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/issues/1334 ?

**Comment by DeinFreund** [comment]
The widget only gives patrol command once after building. If you manually tell the nano to stop/give it a command, it won't patrol again unless you order it to. This is on default settings.

#1334 was the widget crashing completely, so even newly built nanos wouldn't receive a patrol order.

**Comment by knorker** [comment]
yes, it is not about crashing. What I described can be reproduced just by changing the setting in menu.

**Comment by sprunk** [comment]
Ok

**Comment by GoogleFrog** [comment]
Nano towers are set to patrol when created. This does not conflict with not being set to patrol when idle. The problem with being set to patrol when idle is that Stop ceases to work. If you want your nano turrets to stop what they are doing then the intuitive course of action is to select them and press the Stop button. With idle patrol this no longer works.

An argument could be made that Stop doesn't stop units from firing. But that may be a confusing case as well.

**Comment by sprunk** [comment]
How about this solution then:
 * nanos which become idle by completing another order get the patrol command, nanos which become idle through Stop don't
 * set the timeout to nonzero

**Comment by Licho1** [comment]
Its pending proper gadget solution.
Nanos should be way smarter. It's on my long term todo.

Example:
- follow construction priorities when assisting (assist high prio stuff first so that assistance is not wasted)
- if further assisting makes no difference (stall), look for other uses:
  - cooperate repair of nearby units (unless it would cause e to stall)
  - reclaim metal 
  - reclaim energy
  - assist ally in range

**Comment by Licho1** [comment]
pending smarter automation (see my previous comment)

**Comment by mtroyka** [comment]
All of that stuff could be done by a widget, really. It'd need to be a fairly sophisticated widget to account for eco state, but still only a widget.

The biggest problem I've had with caretakers though is that if you have two facs, one building cheap units and the other building expensive units, the nanos will all gravitate toward the expensive unit fac so hardly any cheap units are built. The obvious solution is to lock the caretakers to the specific fac you want them to assist, which is what I end up doing, but it's still work that might be automated better.

Also, not patrolling nanos that are given stop orders is problematic, since the user has no other simple way of setting them directly to idle so that they get patrolled, which leads to the same issue in reverse.

**Comment by sprunk** [comment]
7aa29c465a2fc8a60aabe2e29ced18764ee97cc8 (probably has room for improvements, but in that case make a new ticket with specifics because this one is ancient and buried)
