### ISSUE TITLE
Pyro friendly fire

### ISSUE THREAD

**Issue by sprangg** [ZeroK-RTS/Zero-K#1341]
Newbies and lower elo players still routinely have their pyros cause massive friendly fire to each other, because of them shooting at enemies through allied units.

Shooting through allied units has been justified by having more possibilities for micro and catching enemies behind buildings etc.

To maintain the current possibility for tactical friendly fire, I propose adding a toggle for pyros, "fire through friendlies". This would be off by default, and those confident in their abilities could enable it for all pyros in the unit states menu.

**Comment by sprunk** [comment]
If Pyro avoided friendlies, it would allow us to get rid of one type of special damages - fire immunity.

**Comment by Anarchid** [comment]
The technological part could be done by carrying two (table copied?) versions of the flamer weapon with different values for avoidFriendly.

That could also go on other flamers, too.

**Comment by Orfelius** [comment]
Consider that it would be a major buff to pyro overall and it might have to be counterbalanced with some nerf to its statistics.

**Comment by sprangg** [comment]
When pyro was made to shoot through friendlies, it wasn't accompanied by any other balance changes. The point was in fact to buff pyro by making it better at dealing with fleas and other raiders hiding behind your buildings.

Imo removal of friendly fire would be an ease-of-use change, not a balance change. It would make pyros would be arguably worse, but more reliable in the hands of a less experienced player.

**Comment by Orfelius** [comment]
Fire passing trough buildings and metal robots. What a time to be alive! Not to mention that they also pass trough the dirt and other surfaces.
Sprangg so it was the case in the past but nowdays pyro is in a good place and doesn't need such buff and I do not see how would would make them worse in any way.

**Comment by sprangg** [comment]
Pros using pyro don't need the friendly fire removal option, but newbies who lose half of their pyros to friendly fire are in dire need of it.

I think of it as something akin to fight order for skirms or raiders, that makes units more intelligent and easier to use in the hands of non-Godde people who lack the apm and control.

I'm reminded of a player called Darkenthatblack, who at one point as a newb used to do nothing but gather 5-20 pyros, and move in with them having them all bunched up. This actually often caused notable damage, whereas now they'd obliterate themselves in 5 seconds.

**Comment by Orfelius** [comment]
Yes they don't because they never make more that 8 pyros since they get killed... this is the whole point.
Newb will make more of them and lose most of them trough friendly fire. Pro will never have too many of them. This is not a question of skill but rather experience since it is literally impossible to micro properly more than 8 pyros (I personally struggle with 5 of them).
By removing half of the need for micro you also buff the unit for the pros. This is why defense turrets are so strong - one just doesn't have to put any attention into them.
Recent example of how easy-to-use change should be considered a buff is from where skydusts suddenly started to appear in great number. It is because, it was made easier to make them, 
requiring much less micro and attention.

**Comment by CrazyEddieTK** [comment]
Making micro-intense units easier to use is The Zero-K Way and should be encouraged.

**Comment by sprunk** [comment]
3ee219af0f2e2404625d4c638d775a7d1479e2a8
