### ISSUE TITLE
Report that many models are invisible.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1343]
Cloaky factory, mex and glaive are all invisible for me.

**Comment by Orfelius** [comment]
Last time something like this happened to me it turned out to be a file corruption. I had to remove my pool folder and redownload ZK.

**Comment by GoogleFrog** [comment]
Are they invisible for you? They were also invisible for the other player in the game.

**Comment by Orfelius** [comment]
I had this issue long time ago but it resulted from the game file corruption and it affected every unit in the game. The models would basically not load but gadgets and widgets worked fine.
This seems like it's a different issue though because I'm getting the same issues now. Shieldbot factory, solars thug and probably other models are broken too. It might have something to do with specular shader I imagine.

**Comment by dvr333** [comment]
If you re-add the basecontent ModelFragProg.glsl file to shaders/basecontent then the units become visible again. I'm not sure why those aren't baked into the engine properly.

**Comment by GoogleFrog** [comment]
Orfelius I don't think you read the "dev engine" tag on this ticket.

**Comment by GoogleFrog** [comment]
This ticket was just here to tell somebody to make a decent report about the issue.
