### ISSUE TITLE
change windgen animation to reduce lag

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#1351]
Is it possible to change the roration to reduce lag?

**Comment by Anarchid** [comment]
Sure, you can even try completely disabling rotation to see if it fixes lag, and benchmark that.

**Comment by sprunk** [comment]
Windgen doesn't lag because of the animation. It's the OD stuff.

**Comment by ashdnazg** [comment]
should I mention again the OD equation I suggested which is approximately similar to the current one but takes significantly less computations? (no iterations or negative OD stuff).

**Comment by ashdnazg** [comment]
Now with proof:
http://zero-k.info/Forum/Thread/17596?postID=154837#154837

**Comment by sprunk** [comment]
Changing the equation is a balance change though and an extremizing one at that (even more efficient at low density, even less at high).

Windgen energy production involves a lot of processing per windgen. Each one potentially has a different income (due to height bonus) and it needs to be recalculated individually (because of things like tooltips) repeatedly (wind fluctuates).

**Comment by ashdnazg** [comment]
it definitely doesn't need to be recalc individually every frame.
You have a formula for getting the energy output from wind strength+altitude, it seems to enable calculating it in bulk for a grid.
Tooltips can generate it on demand.

**Comment by GoogleFrog** [comment]
That OD equation looks to different.

On the topic of lag; try various things and benchmark them. I don't think anything useful will come of it though. I have looked at OD and windgen gadget performance and nothing stood out as bad. The fluctuating energy income does not really impact OD because it doesn't remember energy from frame to frame.

I suspect the greatest performance cost of windgens will be the engine. Units existing and units on screen impacts framerate. It will be a relatively low cost though because windgens are static.

**Comment by ashdnazg** [comment]
hmm, it seems like there are two issues here, one is in engine - ground decals are drawn for icons - which no longer happens
Being zoomed in helps in this case.

The other one is in ZK - every time the grid changes there's an enormous stall.
That means each time that:
 * A solar collector is hit
 * A mex is destroyed
 * A pylon, solar, fusion, geo, singu and most importantly **wind generator** is built

the game gets quite a few frames behind. 
These happen quite a lot in games with windfarms. and being zoomed in doesn't help at all.

IMO both are solvable.
You know the solution to the engine issue.
The solution for the game issue may or may not include the OD equation change. I suspect that including it will assist calculations greatly.

I wish to remind that said equation was created not to solve perf but to guarantee that connecting mexes to the grid will be beneficial/no change and to make supermexes less insane.

**Comment by GoogleFrog** [comment]
The change is too different compared to the current system. I don't want to nerf late energy that much. The stall on grid modification is not due to the OD equation or variable wind income. It is caused by the naive graph modification algorithm: destroy the grid and make it again.

**Comment by GoogleFrog** [comment]
Grid modification: https://github.com/ZeroK-RTS/Zero-K/issues/1353

Otherwise, no change required.

**Comment by sprunk** [comment]
Relevant to the original issue (spinning windgens): https://github.com/spring/spring/commit/fddc8ab23c7634bc291c085fd84d4034458efe43
