### ISSUE TITLE
mex glow is seen over the icons while zoomed out

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K#1394]
How to reproduce: overdrive a mex and zoom out.
Version: v1.4.5.0

**Comment by GoogleFrog** [comment]
I've known about this and always seen it as intentional. You get a glow in the middle of the mex icon which corresponds to overdrive.

**Comment by Orfelius** [comment]
Is that necessary to know that it is being overdriven? The glow while zoomed in is enough of a visual indication of overdrive. Besides it doesn't look very good since it actually doesn't cover the icon in a good way.

**Comment by CrazyEddieTK** [comment]
Some other unit-based effects visible in icon view:

 * Radar tower blinky light
 * Airplane exhaust
 * Jumpjets
 * Smoke from damaged units
 * Morphing
 * Cloaking
 * Nanospray

Most of them are not noticeable in my experience, including overdrive, although I suppose that depends on what you have your icon-drawing distance set to.

Seeing airplane exhaust coming from icons is the oddest-looking of the bunch (probably because it's not obscured in any way by the icon), and if we were going to take the effort to fix any of these, I'd fix that one. Seeing morph in icon view is actually kinda helpful. Nanospray is fine. The rest are no big deal IMO.

**Comment by sprunk** [comment]
Intentional
