### ISSUE TITLE
Fight command misbehave

### ISSUE THREAD

**Issue by rlcevg** [ZeroK-RTS/Zero-K#1428]
Often units with fight command just stand at the edge of attack range and do nothing.
Seen often with pack of venoms.
Sniper example (7th minute, there is only 1 sniper staring at hlt): http://zero-k.info/Battles/Detail/418824

**Comment by GoogleFrog** [comment]
The Sniper is set to not fire at radar dots (there is a unit state toggle). This toggle exists because it would spend a lot of its time missing. It starts shooting at the HLT once it becomes scouted. The Sniper is working as intended.

This is an edge case where CAI has a minor failure. Ideally it would more a Sniper which is stuck in this way and tell it to do something else. However, I don't plan to modify CAI so this isn't being fixed.

**Comment by rlcevg** [comment]
Venom example that bothers me: http://zero-k.info/Battles/Detail/418855
(probably fight misbehaves only with venoms)
