### ISSUE TITLE
Malfunctioning GUI on first run

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K#1450]
First seen in [Beamer's first impressions video](http://zero-k.info/Forum/Thread/22522?page=1)

Later encountered by Firepluk after recent new ZKL release: http://imgur.com/zpA6kBP

**Comment by KingRaptor** [comment]
[9:15 PM]  Firepluk after u press "low settings" and rejoin the game
[9:15 PM]  Firepluk u get this white background bug

**Comment by GoogleFrog** [comment]
I remade the default UI about 4 months ago and did not encounter this. The white skin looks like a skinning bug which is likely fixed by the heavy usage of skin-replacement in the new UI. Technically the default skin of each panel is the generic skin and it is widget options that cause them to have their coherent skins. I think the bug would be fixed by reloading the skins and that is currently what occurs.
