### ISSUE TITLE
No OKP for Impaler

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1469]
Is this intentional, for what reason? It's a rather expensive unit, but OKP still makes sense sometimes. For example when you're trying to clear defender forests from a safe distance.

**Comment by GoogleFrog** [comment]
It's intentional in the sense that I know it was not added. OKP breaks if there is a non-negligible chance of the projectile missing its target. To add OKP for Impaler you would need to add ta concept of static-only OKP which would only add predicated damage to known static targets. This OKP could be applied to more things such as Rogue, Rocko and Hammer.

**Comment by DeinFreund** [comment]
Nice!
