### ISSUE TITLE
COFC crashes when arrow key scrolling with smoothmesh scroll off

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K#1519]
```
[f=0003191] [cawidgets.lua] Error: Error in Update(): [string "LuaUI/Widgets/camera_cofc.lua"]:1094: attempt to perform arithmetic on upvalue 'ls_y' (a nil value)
[f=0003191] [cawidgets.lua] Error: Removed widget: Combo Overhead/Free Camera (experimental)
```

**Comment by KingRaptor** [comment]
Also happens with middle mouse pan but at least it doesn't crash the widget.

**Comment by dvr333** [comment]
Looking at the code, it seems that the issue has more to do with Free Mode being on than anything else, since that's the only case where there isn't a return statement. I'm not sure what value should be returned when Free Mode is on, since I don't know if Spring.GetGroundHeight() returns a meaningful value outside of the map (I think it does since engine 102 or so, but I haven't checked).

**Comment by sprunk** [comment]
Another old COFC ticket that is probably done, needs to be checked.
