### ISSUE TITLE
Starlight construction progression is broken

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1526]
It needs about 19% construction before any nanoframe is visible. Fiddle with all the numbers until it works correctly.

**Comment by Anarchid** [comment]
I'm suspecting engine detects model extremes incorrectly and/or uses wrong axis for those. Starlight's model has dimensions 150x150x90 in Blender. 

14% should be right in the middle of the wireframe construction step. If it thinks Starlight's lower bound is -75 and upper bound is +75, because it's been using a wrong axis, then 14-15% is where it would reach above zero and thus clip any actual geometry.

**Comment by GoogleFrog** [comment]
It does help, just apply perseverance. I had to fight Wasp, changing many different variables, to make its build progression look somewhat reasonable. It was far more broken than Starlight.

**Comment by GoogleFrog** [comment]
Seems fixed.
