### ISSUE TITLE
Revist easy transportation UI.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1555]
Currently if you make a mixed selection of ground units and transports then press L twice the transports will pick up the units. I used the UI recently, after forgetting how it worked, and thought it was broken. I thought it was broken because I would select some units and transports, give them a move command and then press L twice. I expected the transports to pick up the units (which they did) and unload them at the end of the move command (which they did not do). Perhaps an improved UI would be the one that I assumed exists.

Another UI improvement would be to have transports pick up and transport units if you select a group of units and simply give them all a move order. Perhaps this should require a modifier. Perhaps  the behaviour could be enabled by default and be overridden to "everything moves" by Alt.

**Comment by Licho1** [comment]
The command works so that if your units have move order and you click load, they will be stopped, picked by transports and moved to end of their current move commands to be unloaded.
For fine control, you can use both load and unload to decide which part of their path should be carried out by transports.

**Comment by GoogleFrog** [comment]
Are you talking about embark and disembark?

**Comment by Licho1** [comment]
Yes

**Comment by GoogleFrog** [comment]
I'm talking about transport UI that works for mixed selections of transports and units.
