### ISSUE TITLE
Ravens don't dive low enough

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1571]
causing them to miss grizzlies and some other units. They seem to do ok vs coms though.

**Comment by GoogleFrog** [comment]
Fixed I think.

**Comment by Licho1** [comment]
Raven diving is so stupid.
It looks ugly and gives no room to micro. Should not dive as deep and hit as much.

**Comment by Anarchid** [comment]
Why reopen? "Raven dives too deep and also melee bombers are stupid" is a different issue.

**Comment by Licho1** [comment]
Its just reminder for me to check raven properly.

**Comment by GoogleFrog** [comment]
Then make a new ticket.

**Comment by sprunk** [comment]
Leaving no room for micro is good in this case because it's zero decision (dodge is almost always better than tanking a bomb to the face)

**Comment by Licho1** [comment]
Micro is not about decisions. Micro is about fast reactions and having extra capacity, attention and skill to do such actions to gain advantage.

**Comment by Anarchid** [comment]
I always thought that "RTS is primarily about decisions" was a significant part of ZK philosophy.

**Comment by Licho1** [comment]
That's not true.
ZK philosophy is no boring/repetetive micro.
Avoiding Raven is very cool and not boring. 
If you want game about decisions, play turn based strategy. In every RTS the part of the skill requires people to pay attention to many stuff and do things quickly, thats part of the game.

**Comment by Anarchid** [comment]
> ZK philosophy is no boring/repetetive micro.
> Avoiding Raven is very cool and not boring. 

Avoiding Raven is mandatory, thus boring. There is no valid decision to spend your attention elsewhere. A choice to"micro 5 glaives vs optimize overdrive layout is not boring because it is a choice. There is never a valid choice to not dodge your com. This is mandatory and thus boring.

**Comment by Licho1** [comment]
You could argue that everything is boring, if it has optimal solution.
Avoiding bullets with glaive is boring, you always want to do it.
Picking correct unit type to build is boring, you always want to do it.
Scouting is boring, you always want to do it.

This is a non argument. ZK is designed for FUN micro!  Very few things can be more fun than the drama of incoming bomber vs commander.  It has drama, it has fast reactions, it has brains, it is high stakes, it is the ZK.

**Comment by Anarchid** [comment]
It is often a valid choice to let fight move take control of glaives on order to spend that time on eco optimization.

 But i guess we're talking in circles on a wrong closed ticket now.

**Comment by GoogleFrog** [comment]
Raven dodge is boring because it is an obvious optimal solution: not getting hit by bombs. Other forms of micro also require quick decision making or situation assessment to the extent that there is no single optimal solution based only on local factor. You have to think about the whole game when deciding whether to micro your Glaives to either maximize survivability, damage output or good positioning. Avoiding bullets is not boring because you can decide whether to slow down and avoid bullets or push ahead, take the bullets, and get to your destination faster.

The Comm Raven micro is a very simple decision. The Commander player never wants their Commander to die, the actions required depend only on very few factors, and the payoff is so great that it is worth investing your attention. The actual micro is a relatively simple action that relies a lot on ping time and luck. The game can be decided based on the outcome of this single interaction and the interaction relies on very few external factors in the rest of the game. It's an importance chokepoint, sucking importance from the actions in the rest of the game. I also consider it to be directly against my view of the core ZK design philosophy.

> Scouting is boring, you always want to do it.

There is so much to scouting! Scouting is expensive, you can't always do it. Always maximally scout and you will always lose. It has to be carefully weighed against everything else you do in the game and involved a lot psychology!

**Comment by Licho1** [comment]
Even if it's a simple task, it's part of the game. The game is also about reflexes and quick thinking. 
You cannot even tell if the bomber is coming for comm or not, so there is your thinking too.
If you want to widget it, widget it but raven should not 100% hit.
I know what game I wanted to make and I know what were our original design paradigms very well. I worked on defining them.
Don't try to subvert those.
This game is not about weapons 100% hitting and about pure strategic thinking.

**Comment by GoogleFrog** [comment]
As far as I can tell you are fine with the outcome of entire games being highly sensitive to a single, effectively random, event. Suppose that we change Ravens such that good players avoid getting hit by 20% of the bombs and we write a widget to replicate this behaviour, which you allow apparently. With this estimate, three Ravens bombing an appropriately healthed commander have a 50% chance of killing the commander. If you increase to four Ravens then they have an 80% chance of success. Five Ravens have a 95% chance of success.

Random success is not inherently bad. However, I think it is bad when it determines the outcome of the entire game, which sniping large units and Commanders can do. Going for a Commander snipe with three Ravens is effectively relegating the outcome of the game to a coinflip. A zero-interaction coinflip. The Ravens try to hit and the Commander tries to dodge, even if widgets are not doing the implemention there is little counterplay. There is much more counterplay already present in the current Commander vs Raven matchup: scouting, suspicion, noticing missing metal, Raven approach angle, Commander placement, unit movement and AA.

If good players can do better than avoiding 20% of the damage then Ravens are artificially more powerful in lower skill battles. Of course, every single bit of micromanagement has this effect but it is not so stark in other situations. Most of our randomness has a cumulative effect and often averages out. True, in some games there will be a single random event which turned out to determine the game. The difference is that the type of random event (eh accuracy) usually occurs often with benign effects and is not obviously important at the time. Raven dodging tends to have the feeling that it decides the game.
