### ISSUE TITLE
crudemenu and crudesubmenu both being on f10 causes conflicts

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K#1623]
This may be because my hotkeys are old, but in v1.4.11.12 (compared to v1.4.11.11) both crudemenu and crudesubmenu are bound to f10, and this causes both to be triggered at once, and the menu state ends up effectively unchanged.

**Comment by GoogleFrog** [comment]
As far as I can tell, crudemenu has been bound to escape since 2013 - basically when it was introduced. I think you changed the hotkeys and it has conflicted with my recent changes.

I made both hotkeys do effectively the same thing in v1.4.11.12 as I wanted to remove the default bind for hiding the menu without messing up hotkeys. Also, it makes sense to allow Esc and F10 to do the same thing.
