### ISSUE TITLE
Beam projectile light fade out.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1662]
I didn't implement projectile fadeout for beams because they are complicated:
 * LLT-style beams get a new projectileID every few frames so the fadeout stacks very high. A workaround would be to set their light levels very low but this feels very inefficient, it would spam many cylinder lights for each LLT.
 * Instant burst lasers already have fadeout linked to beam TTL. The beams count as visible projectiles even after they do their burst of damage so fadeout was easy to implement there.
 * Duration burst lasers are in most need of some fadeout as their beams are on then suddenly cut off. We could perhaps cheat and start fading them a few frames before they are due to extinguish, basically using beam TTL.
 * Beams attached to ordinary projectiles should be handled in the same way as ordinary projectile regarding fadeout.

**Comment by Anarchid** [comment]
I think it's fine for duration beams and continous beams themselves to stop emitting light once they disappear. Currently what they have in form of post-firing effects is the impact CEG, and that could glow by using an explosion light.

The problem with spam lasers generating many of these fadeout explosions remains, but i think nothing much can be done here besides make the fadeout short, because both continuous and duration-burst lasers can change their spatial properties (rotation and translation for continuous; position and length for bursts). 

An LLT continuously firing at a position with a five-frame explosion light fadeout will just generate at most six lights: one cylinder and five fading out spheres. Perhaps this is not *horribly* expensive.

**Comment by GoogleFrog** [comment]
I did this a while ago. See Constable for a good example. Duration beams have a hard cutoff to show their distinctive mechanics.
