### ISSUE TITLE
Scorchers dance around structures

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1668]
Scorchers danace around structures when given an attack command. This seems like really annoying behaviour because sightlines in raiding are much more important than maximising damage. It is not hard to position your Scorchers correctly but it is hard to do when they keep dancing.

**Comment by Aquanim** [comment]
It's possible to work around this by toggling their state to "hold position" if you want your Scorchers to attack a structure from a particular location.

I would want to be sure that dancing around structures has no usecase before changing this, since positioning hold-position Scorchers manually is easier than dancing them manually IMO.

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Zero-K/commit/76017eeca57183a65cfb2fe53ad155011ec5e753
