### ISSUE TITLE
Allowing AA units target anything plus all that is needed to make that work properly

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#1679]
As far as I know, a long ago the goal was to have AA units that are able to attack anything besides air units. Has that plan been scrapped or has it been merely indefinitely suspended? If still appropriate, perhaps we should consider what is required in order to make the gameplay desirable after such a change. 

Planes are fast and fly at an altitude. Therefore the weapons of AA units should probably have a cylindrical or just long range. Additionally, in order to keep up with the planes, I think the velocity of the projectiles ought to be high. However, these attributes make AA units efficient versus other things as well. Because raiders are also fast, AA units would be able to easily act as riot units. Because of the long range, AA units would also be able to counter static defenses. These are just examples.

If planes' HP was reduced considerably, the damage potential of AA units could also be decreased. That could make building AA units in order to attack non-plane targets a cost-inefficient strategy. Nevertheless, the aforementioned long range and high velocity of the projectiles would still make AA units highly capable at the antiraider role so perhaps an even larger reduction in both the plane health and AA unit weapon damage would be in order. The resulting damage per second would be so extremely low even raiders could withstand it to an extent.

Additionally, if bringing down HP isn't enough, it could possibly be desirable to increase the velocity of planes and decrease the projectile velocity of all units that shouldn't be able to counter or semi-counter them. However, the speed boost would have to be substantial to differentiate between riot units and AA units. Certain weapon types hitting instantly should be taken into account as well.

I'm not discussing gunships at this time in this post.

**Comment by sprunk** [comment]
I can't read GoogleFrog's mind but as far as I can tell it's more or less suspended partially because there are other things to do and partially because balance is very delicate so things need to be done gradually anyway.

https://github.com/ZeroK-RTS/Zero-K/commit/6d12b03ba6596eb9957614aee01a8424f4eddd7b - this was supposed to happen periodically to eventually owl dedicated AA in favour of flex. No idea what happened to the idea but it looks like GF rather prefers to force air to interact with ground through mechanics such as Raven dive.

**Comment by GoogleFrog** [comment]
I'm not sure if this was ever my aim. It might have been Saktoth's aim. I recall working towards more flex-AA without removing dedicated AA. I think dedicated AA is working well at the moment and there is a good level of flex-AA, it could increase though. To remove dedicated AA while retaining most of the current unit interactions would require either:
 * Removal of flex-AA
 * Armour classes
 * Starcraft planes

Armour classes can achieve anything and are not an option. The other solutions arise because current AA has DPS/cost on the same order as other weapons. Consider this: Vandal has DPS/cost similar to Ravager and almost 3x its range. How much damage does ground-firing Vandal need to shed to be balanced? At a conservative estimate I think it's at least 75%. A group of 6 Vandals with 1/4 their current damage still kills a Glaive in two volleys. With that sort of attrition who would raid? Even worse, think about Crasher: a Glaive-speed homing missile unit that outranges HLT. So, planes have at most 1/4 their current health. Now some of the best AA units are flex-AA and the interaction is really janky and unforgiving. Moderators 1-shot most aircraft. Penetrator destroys 4K HP Krow. Krow is excempt? Then AA is barely useful against it.

It's clear that planes need drastically less HP if the current weapon ranges are kept. The last option is Starcraft planes, basically terrain-ignoring hovercraft. Low speed planes don't need high range AA. This option is really boring.

Cylindrical range is not a requirement of current AA weapons simply because a cylinder looks a like like a sphere at a radius of 700 elmos. As far as I know all AA weapons which look like they should have spherical range (lasers and blasters) have spherical range.

I think current air/AA interaction is working really well. It has taken years to reach something which isn't broken in obvious ways. Both gunships and planes are viable and used throughout many games.

**Comment by sprunk** [comment]
There's nothing physically preventing AA from shooting ground units (especially since they shoot landed planes), the restriction is arbitrary. Hard targeting restrictions are equivalent to armor classes.

That said, it's a design purity thing. In a void it's good to do (we value physics-ness) but as GF said air is currently in a very good spot which is likely to get ruined by any larger changes.

**Comment by GoogleFrog** [comment]
Hard targeting restrictions are not equivalent to armour classes. Also, you can't just dismiss armour classes, or things that resemble armour classes, out of hand without some details.

Starcraft 2 has an ok implementation of armour classes. There are exactly two classes: heavy and light, and weapons tend to either do bonus damage against light armour or bonus damage against heavy armour. The UI makes the armour class and damage bonus of units apparent and the types generally make sense. I think this is ok because they put in the effort to make it visible on the UI and they consistently stuck to only two classes.

Poorly implemented armour classes are in ZK's history. This is the history of games from OTA to BA adding unintuitive exceptions to create the balance they desired. An example is increased LLT damage against commanders to make the early game function properly. I wouldn't add armour classes to ZK because they are not required. This is not unique to armour classes, all mechanics add complexity to the game so their cost has to be weighed against the benefit.

If air targeting is like an armour class then it's quite a well implemented one.
 * It is clear what is and is not in the air class. It is exactly whether a unit flys (instead of falls or jumps).
 * It is clear what is restricted to shoot at the class, they have Anti-Air in their short unit description. 
 * The damage output between the two classes is consistently 100% or 0%, no weird numbers to remember (technically they deal 10% damage but its effectively 0%).
 * The armour class has good unit AI, AA doesn't waste its time shooting at ground.
 * The armour class is visible, you can observer AA not shooting at ground and learn the rule.
