### ISSUE TITLE
Djinn ignores disarm

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1688]
See NCG (Top right ~16:00) in http://zero-k.info/Battles/Detail/438575

**Comment by Aquanim** [comment]
What is the desired behaviour of a disarmed Djinn?

**Comment by GoogleFrog** [comment]
As far as I'm aware the consistency rule for disarm is that it allows:
 * Ordinary movement (not jump)
 * Self-D
 * LoS (not radar or jamming, now that I think of it, probably not sonar)

I don't think a disarmed unit can be cloakered. Disarm probably does not block autoheal, idleheal or water heal. Ideally disarm should disable all self healing. On that note, slow should reduce the rate of healing. I'm unsure whether disarm or emp do/should delay the autoset of idle heal and whether slow should slow the idle heal timer.

I think teleport should be treated like buildpower, i.e. teleport should occur at the minimum rate available to the Djinn and the Lamp. 50% slow on both would only slow teleport by 50%, much like if all your constructors and economy are slowed to 50% it means you build at 50% the speed, not 25%. If only one of your entire economy or all your constructors are at 50% slow then you still build at 50% speed (I'll assume Djinn and Lamp have matched 'teleport power'). If a Djinn or Lamp is emped, disarmed (or a nanoframe) then their teleport rate should be 0. I guess this would just pause the current teleport, not clear the progress.

The same rate change would apply to Djinn summoning a Lamp. An emped or disarmed Djinn should pause summoning. Otherwise, the summon rate is based on current slow damage.

**Comment by sprunk** [comment]
Status effects already affect passive healing (but not idleness timer).

**Comment by GoogleFrog** [comment]
That's fine.
