### ISSUE TITLE
Ravens don't drop bombs at targets

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#1694]
http://zero-k.info/Battles/Detail/438750

This battle has a bug causing Ravens to not kill an HLT. Happens around 1 minute before the game ends (so ~11m in), at a southwest HLT. I assume this might be caused by the newly introduced overkill prevention on Ravens. There's around five Ravens flying over an HLT, with enough spacing between them that it looks like there's only one bomb in the air at any moment, but only three of these Ravens actually drop their bombs.

All Ravens had an attack command and were flying straight over the HLT. Ravens had ammo. I'm pretty sure they weren't too far away to bomb the HLT for whatever reason. It doesn't look like the HLT was actively being repaired or anything. One of the players mentioned that this occurs frequently. This should not happen! Ravens should drop enough bombs to kill an HLT when given a direct attack order.

**Comment by sprunk** [comment]
My guess is that the OKP timeout is too long. It seems that the current timeout is 4s ( https://github.com/ZeroK-RTS/Zero-K/blob/master/scripts/corshad.lua#L192 ) which is way longer than actual bomb TTL.

**Comment by mtroyka** [comment]
That shouldn't matter because it should still be allowing an hlt's hp worth of bombs to be dropped before blocking, even if it's within the 4 second window. Unless it's counting fakewep attacks towards okp damage or something.

Also, raven bombs can take a while to drop if the raven isn't diving. I'm not sure if it's actually 4 seconds but that does seem to be close. It could be made to adjust the timeout based on the raven's altitude vs the target's altitude but I haven't done that.

**Comment by sprunk** [comment]
As far as I know OKP does not track whether a projectile actually hits. The gadget does not implement Unit(Pre)Damaged or any Projectile* call-ins so it doesn't seem like it would.

If a projectile arrives earlier than the timeout then it would be counted twice until then.

**Comment by mtroyka** [comment]
That makes sense. In that case.. well derp. We could either adjust the timeout to be shorter, and/or add something to estimate the timeout based on relative altitude. Or we could change okp to use projectilecreated/destroyed instead. There might be some advantages to doing it that way instead, including not having to care about projectile timeouts, although it would be more work.

**Comment by GoogleFrog** [comment]
I want to avoid projectile created/destroyed for as long as possible because it will be a slow callin. I also avoided it in OKP for the rare instances where projectiles miss, fly into the sky and take a while to hit the ground. Slashers already have a distance multiplier for their OKP timeout and Raven could use that. Ravens only use OKP against static targets but with shields that can still dive so they need to take distance into account.

In general, OKP should err on the side of letting units shoot instead of not letting them shoot. If a projectile times out halfway along its journey from the Raven to the ground then it is no great loss, Raven will still have much better overkill behaviour in the common cases and at most one extra Raven will shoot.

The conservative behaviour can often be seen with land-based OKP, move 3 Scalpels into LLT range and two will shoot. Just before the missiles hit the third Scalpel might shoot. I think this is fine as if there were more targets the third Scalpel would have shot it instead.

**Comment by GoogleFrog** [comment]
>Also, raven bombs can take a while to drop if the raven isn't diving. I'm not sure if it's actually 4 seconds but that does seem to be close. It could be made to adjust the timeout based on the raven's altitude vs the target's altitude but I haven't done that.

It's more like 1.1 seconds in common cases.
