### ISSUE TITLE
Targeting: armour penalty

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1770]
Armor incurs a combat penalty (can't shoot if armored, except Crabe, who instead can't move). I consider this to be reflected in the +2 targeting priority penalty ( https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/unit_target_priority.lua#L208 ).

Armor also multiplies effective health/cost. This is not reflected in targeting at all (other than the above, which is flat instead of a multiplier).

Is the lack of proportionate targeting dispriority by design?

Related: #1537

**Comment by GoogleFrog** [comment]
Target priority is not supposed to be based off health/cost. The goal of target priority is for weapons to make good decisions, on average, when selecting their target. I have no preference for the particular implementation of this besides its performance, since O(N^2) target priority calls can occur per second where N is the number of units in range of each other.

There isn't a design decision about targeting based on effective health because there isn't even a rule for targeting based on health. It's just a heuristic that seems to work and was faster than manually entering 100^2 values. The real question is whether armoured units seem to be breaking target priority.

**Comment by sprunk** [comment]
Not yet.

I'm slightly worried about Halberd. When closed and used as a decoy it's effectively unarmed and extremely tanky but its priority is on par with most assaults. However nobody seems to be abusing it so I guess for now it's fine.
