### ISSUE TITLE
Pillagers run in circles

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1771]
This is because of tactical AI, and is particularly bad because pillagers fire much less often when moving. I think part of the issue is from pillagers trying to skirm razors that aren't in radar when the razor's range is greater than their sight range. Part of it is just overeager running away from random raiders and things, even when the pillager is sitting safely in a porc nest.

Penetrators do seem to be better now, and impalers never had an issue with shooting while moving, but pillagers are much worse than either penes or impalers at shooting while moving, and are practically as incapable at it as slashers are.

**Comment by versus666** [comment]
You're right, pillagers have a real problem to the point I do not use them anymore. I don't know why but they insist to :
_ Run in circle or retreat far away to keep (very long) distance with their target, so they don't fire at the puny unit, mobile or not and they die because it reach them or they run into other enemy units. 
_ Not shoot at units. No idea why, target is in sight but they prefer to RUN toward the target instead of firing at it. Even ordering them to attack a specific unit then doesn't work. Yeah, it's 'fire at will'.
These both behavior result in less than a TENTH of the firing potential they had a year ago but a LOT of frustration.

**Comment by Licho1** [comment]
Pillagers should default to hold fire..

**Comment by mtroyka** [comment]
They do, and it only helps as long as you don't give them a fight or attack command.

**Comment by sprunk** [comment]
Pillagers cannot fire on the move. Perhaps their AI should behave like Slashers'?
