### ISSUE TITLE
Look into replacing shield visuals

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1784]
Shields use up all the particles and don't even look that good,. The current visuals have the advantage that they show the edge of the shield, however you should be able to extrapolate the rest of the shield once you see the edge so this is not a information concern.

**Comment by Anarchid** [comment]
Current visuals also show part of the shield when the carrying unit is not visible. This would probably be complicated to replicate in Lua because there is no easy callin for units entering within N elmos of AirLOS.

**Comment by mtroyka** [comment]
How are shields eating particles? AFAIK it's just a textured sphere.. and AFAIK the wobbles are really just a single animated normaltex. I agree that they don't really look that good, mostly because the hexagons are kind of awkward and there's no meaningful 'on-hit' animation so most weapons just disappear into the shield.

Also noteworthy is that 'on-hit' changes seem to work badly wrt constant fire lasers like llt. Spring won't even show the on-hit at all, even though all it does is modulate the alpha of the shield tex.

**Comment by Anarchid** [comment]
Seek first in `CShieldPartProjectile`.

**Comment by mtroyka** [comment]
ShieldPreDamaged does give a beamEmitterUnitID so you could use getUnitWeaponVectors from there to see what it's pointing at. Since beams are instant hit you don't really need the projectile information anyway, but then you do have to recalculate the collision point which seems unavoidable and which you probably don't want to do every frame.

**Comment by GoogleFrog** [comment]
Shields are particles. They count towards the particle limit.

Maybe I should not have made the ticket. It is a thing that could be done but would take someone a lot of work. The idle musing is probably just wasting time.

**Comment by GoogleFrog** [comment]
It is likely easier and more useful to reduce the particle use of particle-greedy effects. Then we could possibly safely increase the particle limit.

**Comment by Licho1** [comment]
Afaik there are now callins  + ability to read projectile coords. That would allow us to make some on hit effect which could make it much prettier.

**Comment by Anarchid** [comment]
I even used them in my attempt! The problem is that for beam projectiles that position is incorrect, and beam projectileID is also not sent to the callin.

**Comment by mtroyka** [comment]
beam weapons have separate IDs. It doesn't give you the intersection point directly though.

**Comment by mtroyka** [comment]
Spring.GetProjectileVelocity(): "New in version 95.0: returns (targetPos - startPos) for Beamlasers and similar weapons"

This perhaps?

**Comment by GoogleFrog** [comment]
But did you test whether it works? That is the real work.

**Comment by GoogleFrog** [comment]
Forb has replaced their shields with a Lups sphere and says that performance is much better than the particle shield, so perhaps it is worth looking into further. There are still major issues to solve:
 * Shield visibility. To solve this with Lups shield I think enemy units should be visible when the edge of their shield is in aLOS. This is potentially expensive.
 * Shield charge colour. Requires lups modification.
 * Shield hit colour. Requires more extensive lups modification.
 * Depth-testing. Forb found a problem with making large lups spheres. The overlaps look unusual and may fight with other bits of the UI (he had a problem with healthbars).
 * Compatibility (major issue). People without lups need to see shields.

**Comment by Anarchid** [comment]
> Compatibility (major issue). People without lups need to see shields.

I suspect there may be people without shaders, but not people without LUPS. For example, nanolasers are LUPS particles that do not require shaders and seem to work for everyone. A similar downgraded version of LUPS-sphere shield should be easy.

**Comment by GoogleFrog** [comment]
LUPS is a widget which is able to be disabled, people have disabled it.

**Comment by let4be** [comment]
Would be really cool to see some progress here,
this is a major issue in chicken games, they tend to get porcy with lots of shields - hence lagfest and it's impossible to see anything underneath tough shield network(everything is blue)

**Comment by CrazyEddieTK** [comment]
Consider adding this to the Steam milestone. Even if the LUPS solution is not feasible in the short run, perhaps we could request engine changes that would allow a limit to stacked shield opacity. As @let4be points out, this is a big issue for chicken games, and new players will play a lot of chickens (not to mention building 9001+ shields in their porcfest games, or even just managing Felonballs).

**Comment by GoogleFrog** [comment]
This ticket isn't about transparency stacking. I don't know why #2487 was closed as either can be solved independently of the other.

**Comment by sprunk** [comment]
I don't think #2487 can be decently solved without #1784. Engine shields don't have any way to limit opacity stacking.

Of course you can just reduce single shield opacity but I think that would be a bad thing to do because stacking multiple shields in the same place is fairly uncommon (arguably it's common in chickens but I think that exposes bad design of chicken rather than shields) and is not a full solution (still possible to make the stack opaque, just needs more shields) while sacrificing visibility when there are few shields, the common case.

**Comment by CrazyEddieTK** [comment]
>Engine shields don't have any way to limit opacity stacking.

Perhaps that could be changed.

**Comment by mtroyka** [comment]
I doubt that would be either easy or efficient.

**Comment by Anarchid** [comment]
It would likely be just as easy as a LUPS solution:  bulk of the work being in GLSL.

**Comment by mtroyka** [comment]
Well duh, but you'd have to record the opacity for each shield, which isn't cheap and is also subject to the limitation that texture writes have to be the same width, which means writing to an extra 24 or 32 bit texture, possibly twice per shield when rendering the front/back faces of the spheres. Since graphics cards are memory bandwidth limited far more than they are compute limited that's a very bad kind of expensive. It would also mean rendering all the shields in two passes, doubling the number of draw calls which are already a major limiting factor to performance.

That's pretty painful when we're talking about a shieldball stacked up so much that you can't see through it, as that kind of situation is already gets pretty terrible fps on lower end cards.

**Comment by Anarchid** [comment]
I think that any kind of naive opacity adjustment is going to make inner walls of intersecting shields, as well as nested shields, very hard to see. Think a Thug inside multiple Aspis bubbles.

Regardless of that, a shader based approach can still be faster than engine-drawn shields. The main problem with those is that they are drawn in multiple separate segments to allow for depth sorting. My thinking here is that an analytical raytrace inside a frag shader could probably do this faster; also possibly there are ways to cheat by keeping in mind that all shields are necessarily spheres, which always project as circles. I

**Comment by Anarchid** [comment]
I tried figuring out how different shield types would look (without going too deep into how they are drawn).

Top to bottom:
Opacity threshold over current engine shields
Current LUPS shields
Current engine shields
Edge highlight shields with intersect and with inner faces removed
Edge highlight shields with only ground edges
Edge highlight shields with intersect highlight

![image](https://user-images.githubusercontent.com/3822768/29922637-214169f8-8e5f-11e7-9b9f-01f2f921d9c2.png)

**Comment by let4be** [comment]
> Edge highlight shields with intersect and with inner faces removed
seems like a natural and realistic fit for me, though I'd consider removing inner highlight here
it would just look like one shield with complex form

**Comment by sprunk** [comment]
Inner faces should stay because they are still there and work from a game mechanic perspective which matters in case the projectile is already under the outer layer.

**Comment by Anarchid** [comment]
If there any indication of shield interception besides the shield changing color, then that could be sufficient to indicate such cases. And if shield graphics get any work, then i think flashing in response to being hit should be a requirement anyway.

![image](https://user-images.githubusercontent.com/3822768/29968736-b8dc889e-8f25-11e7-83a2-b8affe45d3ce.png)

**Comment by sprunk** [comment]
It's not about conveying the stoppage when it happens but the fact it can happen in the first place. If there are no inner walls it looks like you only need to pierce once.

**Comment by Anarchid** [comment]
On some further thought i think other edge-based approaches as well as every other approach cannot be made work reasonably at all.

An Aegis has a footprint of 2x2, which becomes something like 32x32 elmo = 1024 square elmos. Aegis projects a shield with radius of 350 elmos, which covers ~385 000 square elmos of flat area. A worst case pathological shield spam could fit 375 such shields in a way that they would intersect every other one.

Opacity threshold will turn this into a monochrome blue tint with no gradations visible (at least once charges converge).

Both current LUPS and current engine shields will simply reach full opacity and make everything under them invisible.

Any kind of edge based shield without inner edges and faces removed, will turn the whole area into a crisscross of edge highlight lines spaced in a pretty but blinding kaleidoscope pattern - and that if you just render the lines!

And of course any kind of removal of inner edges will erase this information from being visible to the player.

Perhaps a game design solution would be to increase shield-carrier unit size, but that also nerfs such shields by allowing them to defend only a smaller amount of units (by taking up more space themselves). However, limiting the absolute worst case would allow to calculate opacity values such that they will never completely reach opacity in "bad but not absolutely pathological" situations. E.g. if only 10 shields can be expected to cover a single area, and 90% opacity still leaves underlying units kinda visible, then a single shield should have at most 9% opacity.

**Comment by Anarchid** [comment]
Alternatively, shield bubbles could merge: either forming a union of their shapes; or forming a single sphere that covers all emitters in a reasonable area.

**Comment by CrazyEddieTK** [comment]
A situation where there are so many overlapping shields that opacity would render the interior invisible is also a situation in which no one will care about the internal arrangements of the shields.

For a single Thug under a single Aegis, yes, you want to be able to see the Thug's shield and the Aegis' shield as separate objects and know where their borders are. For dozens of shieldbots underneath a half-dozen shieldwalkers, the details are unimportant. And for a base protected by dozens of shield projectors, simply knowing how many you have and where they are is sufficient, and you can see that as icons in the strategic view.

You do, however, want to see the _units_ under the shields clearly, which is why stacking opacity is such a problem.

Since there are only three sizes of shields, perhaps a reasonable solution is for shields of the same size to bubble-merge when overlapping, but leave shield blobs of different-sized shields separate from each other. For any given shield size, it's easy for a player to visually interpolate where the interior edges of the overlapping globes are even given only a single bubble-merged exterior blob, since all the globes making up the blob will be the same size. That would address @sprunk's game mechanic concerns.

**Comment by CrazyEddieTK** [comment]
If we implement shields in LUPS, perhaps there would be a way to detect people without LUPS and fall back to enabling engine shields for them. That would be a big improvement for most people while not leaving anyone worse off than they are right now.

Also:

>The other solution with engine shields would be to change the texture to transparent at the top. However this fails to convey protection from above, which I think is important since shields mostly interact with arty (who are often high trajectory).

If the shield texture opacity started strong near the edges and faded to almost-but-not-quite transparent near the top, I don't think that any players would be confused about the fact that the shields extend in a full sphere around them and do in fact offer protection from overhead attacks.

In fact, this could be a very workable solution even without LUPS. It sounds like something that could be implemented and tested right away. Maybe someone can do some trials and post the results?

**Comment by GoogleFrog** [comment]
Engine shield drawing is currently synced.

**Comment by Anarchid** [comment]
Another approach could be animated shields such that all points on a sphere are marked at some point in time, but at any given timepoint most are very transparent.

**Comment by CrazyEddieTK** [comment]
SupCom does that and I think it helps. Also, I'm not sure, but I think that SupCom hides internal shield surfaces when zoomed out and makes them more visible when zoomed in. That could also help with @sprunk's concerns - you're more interested in seeing the details of the internal geometry when you're zoomed in (doing fine-scaled unit micro) than when you're zoomed out (dealing with strategic issues).

**Comment by sprunk** [comment]
How about small shields drawn merged, large shields separately?

**Comment by Anarchid** [comment]
This does not work for fireman's pathological case of oppressive Aegis spam.

**Comment by let4be** [comment]
nah, it's not pathological
even in regular games u can find so dense mobile shield balls u can barely see underneath them...

**Comment by GoogleFrog** [comment]
This was implemented.
