### ISSUE TITLE
Replace "burrows" keyword

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1787]
The burrowing keyword is somewhat confusing. It is supposed to refer to the burrowing mechanic in Starcraft, however our cloak mechanics differ so the comparison is not great. Someone who did not know Starcraft would not know what burrowing was supposed to mean. Visually the units are not underground and there are other games where burrowing units can move through the ground. Earthworms burrow.

A for a replacement is some appropriate variation of "ambush" because that is often the role of the mechanic. We could try "static cloak" as it is the most descriptive but it is hard to work into all the situations which it would be used.

**Comment by Anarchid** [comment]
I like ambush because Wesnoth is better than Starcraft.

**Comment by GoogleFrog** [comment]
The issue with ambush as an ability name is that "ambushing" is an awkward word to add to the adjective soup that passes for brief unit descriptions. How about "hiding" or "concealable"?

**Comment by Anarchid** [comment]
I think it may be possible to circumvent the awkward "ambushing" by skipping the suffix and rearranging the phrase. Something like that:

Ultralight Scout/Raider (burrows) -> 
Ultralight ambush scout/raider /
Ultralight scout/raider (ambush)

There's even a precedent for using noun as adjective here: ships with long-range artillery used (and some still do?) noun bombardment instead of adjective bombarding.

**Comment by sprunk** [comment]
The meaning may not be obvious when read, but is it hard to discover? Perhaps I have hindsight caused by playing both ZK and Starcraft but I think it's fairly easy to see that the "burrowing" corresponds to the little dirt kickup the unit does when stopping which makes it cloak and that this effect is lost on movement.

Similarly, "cloak" means "cape" in English, using it for "invisibility" is mostly due to the fantasy trope of "invisibility cloak" which is not necessarily obvious (for example in Polish we have "invisibility hat" instead). Do we change "cloak" to "invisibility"?

**Comment by GoogleFrog** [comment]
Sounds reasonable. Perhaps if there is an issue it is with the Blastwing animation. However, Claw doesn't seem to cloak for any reason either.
