### ISSUE TITLE
Instant nanoframe spawning

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1800]
It is possible to spawn an unlimited number of nanoframes in the same game frame. The only limiter is the build range of constructors. The widget which allows this is the command insert widget, the construction starter widget is irrelevant. This functionality is a result of the way CMD.INSERT works, no gadget is causing the behaviour as far as I can tell.

To reproduce:
 * Give a constructor an order.
 * Insert a box of construction orders using the command insert widget (Alt+Space+Shift drag).

The constructor needs to have an order for command insert to activate. This is exploitable based on the current capabilities of nanoframes, which are as follows:
 * Nanoframes block movement. This could be used to trap low-firerate units in a cage of nanoframes. Make a wall to block the movement of cloaked units.
 * Nanoframes are targettable. For example they absorb Puppies. Note that this is less dire since overkill prevention as each nanoframe will only be shot at by one Defender.
 * Nanoframes are radar dots. Spoof radar.
 * Nanoframes cannot decloak enemies. They have no effect on cloaked unit visibility.
 * Nanoframes at 0% cannot block shots. I made nanoframes grow from flat to full height at 33% completion. They can't be used to nanoshield.

Constructors should be able to make nanoframes so their use will never be fully blockable, nor should it be. Radar spoofing is a particularly cool application and I wrote the construction starter widget for a reason. However, I never thought one could make multiple nanoframes in the same game frame. If this capability were embraced with automation it would make constructors extremely effective at blocking the movement and baiting the shots of slow-fire units.

My current idea for a solution is to write a small gadget to enforce a waiting time between nanoframe construction. The rate of spawning could be as low as one per second but that may just be frustrating to use. I would aim for a rate similar to that achieved by the construction starter widget.

I would also like an improved version of the construction starter widget. The current widget spends metal needlessly and is dependent on latency. Once we set a mechanical bound on the level of nanoframe spawning there should be UI in place to support the rate of spawning. Creatively applied nanoframes are unavoidable due to basic features of our construction model.

**Comment by mtroyka** [comment]
One per frame seems like it should be reasonable. That way there's no chance that it could interfere with normal usage, but it would certainly prevent this particular exploit.

**Comment by GoogleFrog** [comment]
Why do you draw the line at one per frame? Your reasoning is better suited for two per second. Whatever 'normal usage' is I doubt it would interfere with it and it would certainly prevent constructors from blocking unit movement. The most BP I have seen on a constructor is 60 on a stacked nanolathe engineer commander and the cheapest structure costs 35. In theory it can make no more than two full Windgens per second.

It still sounds quite easy to block unit movement when you can make 30 nanoframes per second. Also, don't think in terms of exploits because it's loaded language and I don't even think it is well defined. What is the exploit in this case? All I see is behaviour, some which may be degenerate. Calling infinite frames per second an exploit which is solved by reducing it to 30 frames per second still ignores the fact that, in practice, everything you can do with infinite frames can also be done with 30.

**Comment by Aquanim** [comment]
A lowish single-digit number of nanoframes per second seems reasonable to me. (I think the word "frame" was overloaded in the above comments.)

**Comment by sprunk** [comment]
Why had we gotten rid of the OTA nanoframe degeneracy solution, decaying nanoframes?

 * spoofing radar by spamming fake radar dots over a discovered real base (eg. for protection against arty) -- for this we already have jammer and their practical effect is very similar (smart units are forced to do random attacks at the area instead of targeted ones). With decaying nanoframes you have to pay the minimum building cost, but you get a real building in return and a con is much cheaper than a jammer so perhaps small scale spoofing is still viable using a constructor.
 * spoofing radar by making a bunch of radar dots in the middle of nowhere to look like a base. The opportunity cost of having the con make a fake base instead of doing something more useful (and of potentially losing the con) probably already doesn't offset the enemy cost of having to send a scout so I don't think being forced to pay for a handful of windgens would make this much less viable than it currently is.
 * Shot blocking. If a con can only maintain 1 nanoframe you can still block shots creatively.
 * Movement blocking. Same as above: hindering can be done but not 1 con making a cage by itself.
 * Caretaker not having a buildlist becomes more meaningful. For example currently you can just start a handful of 1% Caretaker nanoframes, 1% fusion nanoframes, a 1% singularity and some 1% LLTs around it and then just finish a single Caretaker to finish the others and then everything else. I don't know the reasons why Caretaker has no buildlist though so perhaps this behaviour is okay.
 * OTA had each building decay by % of its cost so large buildings decayed super fast. The decay could be made flat and fairly low (say, 5 metal / s) so as not to punish small breaks when building large things.

**Comment by mtroyka** [comment]
I think nanoframe degeneration after a given amount of time with no bp applied might be a good idea, but is a separate issue.

Another issue I've noticed is that due to the bottom-up construction 1% nanoframes are sometimes untargetable by certain weapons, notably gauss.

2 per second is probably reasonable. My concern was that it might interfere with the normal usage of the building starter widget, but spring seconds are pretty short and I don't think constructors can typically plop faster than that in practice anyway.

Making the building starter widget lag-independent can't be done. The only way to do that is to convert it into a gadget so that commands no longer need to be sent every time a nanoframe is placed. As long as the commands need to be sent they will always be affected by latency.

**Comment by GoogleFrog** [comment]
> Why had we gotten rid of the OTA nanoframe degeneracy solution, decaying nanoframes?

Because the Spring implementation of decaying nanoframes is easy to neuter with automation and it didn't seem worth a gadget.
 
* It has to be possible to keep a nanoframe from decaying if it is being attended to by a constructor which is not spending any metal. The neutering of the lack of this behaviour would be for the constructor to spend an insignificant amount of metal each frame.
 * If it takes a few seconds, say five, for a nanoframe to start decaying then each constructor could keep 150 nanoframes from decaying simply by switching between them rapidly.

> Shot blocking. If a con can only maintain 1 nanoframe you can still block shots creatively.

Nanoframes don't block shots. See OP.

> I don't know the reasons why Caretaker has no buildlist though so perhaps this behaviour is okay.

Caretaker has no buildlist to prevent long ranged construction starting. Construction starting can be used to spoof targeting as well as other things.

> Making the building starter widget lag-independent can't be done.

That is my whole point. For example I made autoskirm lag independent by making it a gadget. Lag-independent building starter could look like a command inserted after the construction command or an X,Z,TeamID triple sent via a lua message.

**Comment by sprunk** [comment]
>[Decay was removed] because the Spring implementation of decaying nanoframes is easy to neuter with automation and it didn't seem worth a gadget.

Does that mean decay is something you'd now reconsider (in a gadgetized form)?

>Nanoframes don't block shots. See OP.

Yes, that was bad wording. I meant nanoframes wasting shots of units with valuable shots (such as Defenders or Puppies).

**Comment by GoogleFrog** [comment]
Decay still doesn't seem worthwhile.
 * Decay has to be instant to be mechanically meaningful.
 * Instant decay involves checking every constructor queue and every nanoframe every game frame.
 * Instant decay seems unreasonably punishing for players who accidentally override a construction order. It is adding a noob trap.
 * Decay is a source of free buildpower (since otherwise reclaim costs buildpower) and I recall now that this was Sakoths main argument for its removal.
 * Decay constrains constructor actions, especially in the early game. It reduces the ability for constructors to reactively make defenses/energy/whatever so would have an affect on balance. Cheeses would probably be more effective. Managing your constructors would be a bit more frustrating when there is a larger cost to accidentally moving them before they are finished. The game would be easier/harder depending on skill level.
 * Decay adds more ways for unit AI to fail (which in turn leads to the frustration mentioned above). There will be situations where it is possible to avoid decay which are made difficult to implement by the UI. For example If two constructors are expanding and need to build a turret then you can make one interrupt its mex production and make the turret. Players often excess buildpower so the excess constructors could be used to keep structures from decaying. Caretakers could be particularly effective at preventing decay when constructors in the base need to do a new task. Say you have a constructor and a Caretaker making a fusion and you suddenly want a Razor. To make the Razor as quickly as possible you would need to start the Razor nanoframe, set the constructor to construct the fusion and then set the Caretaker to make the Razor.

If we were to have nanoframe decay then I would make nanoframes decay when they are outside the construction range of all your allyTeams constructors. This avoids the unit AI failures but barely addresses the degenerate behaviour and would still possibly be an expensive gadget.

**Comment by Licho1** [comment]
Eventually we will reach a point where limiting widgets might become necessary. It's probably not the case, just keep this in mind - if its too hard to gadget fix we can lock widgets.

In this case probably you could limit the frame creation rate per constructor. Limit it in widgets we supply and enforce rule in gadget. I'm not sure that enforcing wait in gadget is easy enough, but simply discaring if rate is exceeded is simple and wait itself can be enforced in widgets enabled by default.

**Comment by GoogleFrog** [comment]
The current implementation of the command insert widget is probably the most straightfoward implementation. The engine automatically creates many nanoframes when command insert is used in this way. I think a wait in the widget would be more trouble than its worth.

**Comment by GoogleFrog** [comment]
I poked around in the command insert widget and it handles blocks of structures naively and poorly. I improved the UI to match the non-insert UI which has the side effect of removing the instant nanoframe ability from the widget. 

https://github.com/ZeroK-RTS/Zero-K/commit/7305e951a8d84b8915c8cfb516ded77fa8376db1 Using command insert to construct blocks of structures:
 * Adds commands as a chunk instead of possibly inserting them at many different positions.
 * Preserves the order of the block. The structure where you initially clicked-to-drag is now produced first, just like it is without using insert.

I also tried making a naive gadget to limit nanoframe rate https://github.com/ZeroK-RTS/Zero-K/commit/fc37c1aeb6728c0e65d3c8cc75075359708b15b3. However, it removes the command instead of pausing it so I would not push the blocked rate above anything attainable by a human (with the default UI) otherwise annoyane will ensue. It can persist as a block for widgets and potentially AIs that get funny ideas.

**Comment by GoogleFrog** [comment]
It looks like this was solved. The command insert widget no longer lets you try to instantly make a block of nanoframes. It is hard to write a local widget to spam nanoframes because there is a gadget that prevents constructors from creating more than one per game frame.
