### ISSUE TITLE
Construction fails without storage

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1840]
I suspect that this only affects team games since this bug was supposedly fixed in 1v1 testing.

http://zero-k.info/Battles/Detail/443886

**Comment by GoogleFrog** [comment]
Do /resbar. His resource bars have resources in them, around 14 for each of metal and energy (you are allowed to go over your storage cap by your income).

**Comment by GoogleFrog** [comment]
I discovered that I implemented priority debug a while ago: https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/unit_priority.lua#L616

The debug says that this issue is caused by priority as the Med spending ratio is set to 0. So far I think his reserve level is set to 25 and it just happens to break on completing the Crane.

**Comment by GoogleFrog** [comment]
Ahhh obvious. The reserve is set to 0 if a unit is destroyed. However in this game he gifted his commander to another player so it was not triggered. The priority gadget does not care about current storage level at all, directly. I think I will change it to cap reserve by current storage on every check without affecting your reserve level directly. This has the benefit of effectively resettting your storage to 25 if you make a storage.
