### ISSUE TITLE
The Guard command makes units clump

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#1868]
The default, i.e. not the circling form of the Guard command, makes units follow the target unit in a tight group. If they spread out somewhat they wouldn't be so vulnerable to explosions that have a significant area of effect.

**Comment by sprunk** [comment]
* Clumping is often desirable, for example to fit large groups under area effects (cloak or shield).
 * Raw guard is an engine command so ZK does not have direct control over it.
 * Circle guard wouldnt work well as a replacement because it is parametrized and does not have some expected guard behaviour (eg cons won't assist).

**Comment by Sgathec** [comment]
Perhaps the default Guard should be replaced with a spread-out Guard though since the shield case is probably less frequent. Maybe the clumped one could coexist. I created this issue primarily because I believe new players don't realize how dangerous tight groups can be.

**Comment by sprunk** [comment]
It would be good if GoogleFrog said something because he usually has insight on how people use UI but I dont think newbies will use guard much. Rather they will probably move groups around with point move (as opposed to line move) which already has a ticket to do something against clumps #1553 .
