### ISSUE TITLE
Create API for tracking army size and related values

### ISSUE THREAD

**Issue by Aquanim** [ZeroK-RTS/Zero-K#1871]
Intent is to unify similar code in player list, attrition tracker, tourney game status tracker, and potentially endgame graphs.

(If somebody else would like to tackle this, go for it. Otherwise it will wait until it's on the critical path for new playerlist.)

**Comment by mtroyka** [comment]
That's not a bad idea. I think it'd need to be a gadget in order to correctly track everything though, and it's complicated horrendously by commshare.

**Comment by Anarchid** [comment]
Attrition counter's logic of a zero-sum game doesn't really work in all cases even as a gadget. For example, environment kills, self-destructions, and friendly fire can only be attributed as "kills" for the enemy team if there are just two teams.

**Comment by mtroyka** [comment]
Attrition counter at least advertises that attrition rate is defined as "Metal in units killed / Metal in units lost" in which case env kills would count solely as losses and not as kills if it is to be correct.

Attrition counter doesn't care about commshare since it tracks by allyTeam, but tracking per-team unit values like playerlist does cannot ignore it.

**Comment by Anarchid** [comment]
> Attrition counter at least advertises that attrition rate is defined as "Metal in units killed / Metal in units lost" in which case env kills would count solely as losses and not as kills if it is to be correct.

Sumo defenestrating an enemy commander off the cliff causes the commander to die from a ground impact. This is an env kill. Yet in an 1v1 scenario, not counting this as a kill for the Sumo player is completely incorrect.

**Comment by Licho1** [comment]
There is also need for mod-stats level stats. Which should track all damage done by every unit to every other and send it to host. 
Atm it works that way but it needs tweaking for commshare and it should also add temporal dimension and send it by minute chunks or so.

**Comment by mtroyka** [comment]
>Sumo defenestrating an enemy commander off the cliff causes the commander to die from a ground impact. This is an env kill. Yet in an 1v1 scenario, not counting this as a kill for the Sumo player is completely incorrect.

Meh. grav weapons are definitely an issue. Also other impulse damage like dropping trollcoms from transports and other such things. I'm not sure if it'd even be feasible to track impulse damage back to the source, since unlike other weapons there's no predictable timeout between the application of impulse and the damage that results. On the other hand as long as you can distinguish impulse damage from damage by acid/lava then some sort of solution might be workable.

>Scythe dealing a fatal blow on a Singularity Reactor in the dense formation of enemy buildings causes them all to die. This is a friendly fire event if you consider that most of the units in the nuclear fireball die after being damaged by the Singularity Reactor. However it is incorrect to attribute all this destruction to anything but the cunning Scythe.

Attributing death explosion damage back to the player that killed the exploding thing is also a pain. This would also apply to roaches and skuttles that get killed by the enemy and end up teamkilling. That probably wouldn't be too difficult to track via UnitDestroyed though, and certainly is easier than for impulse.

**Comment by sprunk** [comment]
#2258
