### ISSUE TITLE
Disable TTS default?

### ISSUE THREAD

**Issue by Aquanim** [ZeroK-RTS/Zero-K#1922]
This is a discussion that really needs to happen before release. To quote myself:

>I think there are pretty good reasons why no other strategy game has a feature like this. It's intrusive, the voice isn't nice to listen to, many of the things converted to speech are useless wastes of   attention like "lol", "lobster", etc., and it seems like it would be fairly easy to abuse. (Possibly there are some checks built in for abuse cases; I've never had it on for long enough to find out.) 

Judging from the votes in the forum thread so far, many more people support disable rather than enable as default.

I believe a significant newbies will get into the game and think "wtf is this, how do I turn it off", potentially fail to work out how to turn it off, and leave. I don't think anybody is going to get into the game and think "not having TTS is a dealbreaker for me, uninstall".

I don't mind that TTS exists but I do not think it provides a good first-time user experience.

**Comment by Licho1** [comment]
You also had people making threads and asking where it is when it was missing.
Without proper testing (no you cannot use voluntary polls on site) it's design choice of devs.

My own strong opinion is, that it is very useful, makes the game much more alive and must be on by default.

To convince me otherwise, we need a poll which, after few games where TTS worked, ask every new player in-game about it (and does not let them not answer).

Personally I totally miss the text, but I always notice important things said over TTS esp. if they contain my name. Maybe it is because I'm non-native or just have my visual channel clogged, but playing without it is like playing without people for me.

**Comment by Licho1** [comment]
So closing until apropriate polling tool exists.

**Comment by Aquanim** [comment]
This isn't a decision which you should make unilaterally.

**Comment by Aquanim** [comment]
Well, if the core developers have already had this discussion, then closed pending unarguable data.

**Comment by Anarchid** [comment]
One thing that recently popped into my mind that since ZK is a significantly cooperative game (especially in teams), it shouldn't stand too much in the way of voice chat. And i think TTS conflicts with voice chat.

So even if it's on by default, it should be very easy to disable it.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/595fda4c6cdee53596d2c0ef8a02e46ede270c38
