### ISSUE TITLE
Right click on move state increases move state

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2028]
Instead of decrease

**Comment by GoogleFrog** [comment]
Explain the issue.

**Comment by DeinFreund** [comment]
If I right click on the move state icon, it goes from yellow to green. Instead of to hold position(red).

**Comment by mtroyka** [comment]
That should apply to all state buttons then, that right-click cycles in reverse.

**Comment by DeinFreund** [comment]
Yes it does

**Comment by GoogleFrog** [comment]
I asked because it was ambiguous as to whether you didn't like the current behaviour or whether you expect the behaviour and it broke. The solution to this was implemented 8 years ago and unchanged for 3 years. I just tested and it works for me. I'll assume a local widget issue.

https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/cmd_state_reverse_toggle.lua
