### ISSUE TITLE
Orfelius colour issue

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2054]
Orfelius may have some actual issue with the new colours. It is hard to tell since he is so snide. This task is to try to wheedle some useful feedback out of him.

**Comment by Orfelius** [comment]
Its just that my aesthetic senses are revolting due to abundance of green. I'm farily sure this is entirely subjective to me.

Then I realized that colourblind people might actually have a problem with the new player colour but it has been pretty much ruled out.

I don't think there is a real valid argument against the current colour sheme other than "some people don't like it".

**Comment by db81** [comment]
He's just is a poor mood because of his broken leg.
