### ISSUE TITLE
Planetarwars Structures Spawning in Wrong Location

### ISSUE THREAD

**Issue by Stuart1998** [ZeroK-RTS/Zero-K#2070]
See here: http://zero-k.info/Battles/Detail/449749

**Comment by GoogleFrog** [comment]
The structures pick a random position on the map and reject it if it is not in a startbox. This is tried about 80 times after which they give up and start ignoring startboxes. This is due to the fancy startbox API that came in since the last planetwars. Using the API properly is covered here https://github.com/ZeroK-RTS/Zero-K/issues/2065 and this bug is not going to be addressed independently from doing the work to use the API properly.
