### ISSUE TITLE
PlanetWars structures cannot be attacked

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2076]
Enemy CC cannot be attacked:
http://zero-k.info/Battles/Detail/449783

**Comment by Anarchid** [comment]
They were attackable yesterday. They are, however, not attacked automatically, so merely walking units near them won't cause them to be shot; you need an explicit attack order. Right click suffices.

**Comment by mtroyka** [comment]
That's lame. Units should shoot/chase enemy stuff automatically, including pw structures.

**Comment by Anarchid** [comment]
I think it's a leftover from when structures destroyed ingame were destroyed (or, later, disabled) ingame. Then you could choose to destroy or keep intact if you expected a capture.

This proved problematic for a lot of reasons. Unaligned militia being able to destroy wormholes is a good example of what would happen currently, but what happened back then was single warp dropships triggering attacks that destroyed an entire planet's infrastructure.

Currently all structures get disabled after a successful invasion and are unharmed otherwise. So there's no reason to waste your time shooting at, and expose your units to explosions of, structures which are non-consequential. The only exception is an attacker's CC, because it's a quite consequential thing.

**Comment by Licho1** [comment]
No, not attackable even with right click force attack. 
It's not a leftover, they were attackable in the past CC and i think other structures like geos etc. still are attackable.
Attacking those disables them in PW.

**Comment by Anarchid** [comment]
CC was attackable [yesterday](http://zero-k.info/Battles/Detail/449749), so if it somewhy became not attackable, that's caused by a recent change.

**Comment by Anarchid** [comment]
I just failed to kill a CC because my commander couldn't build and shoot the CC because apparently settarget on neutral structures is ignored. So i think it shouldn't be neutral.

**Comment by sprunk** [comment]
2b64ab2246485d19a9a5f2e7cf0b701f8977521e
