### ISSUE TITLE
Endgame screen issues

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2147]
Here are some polish issues with the endgame window:
 * The horizontal bars between players in the awards screen have ellipsis (...) at their right side because the lines have a fixed size which is longer than the window. They should have a relative width (probably using 'right').
 * The numbers on the horizontal lines in the graph screen jitter up and down if you click a graph type button multiple times in a row.

**Comment by CrazyEddieTK** [comment]
Regarding the jitter:

 - If you click back and forth between two different buttons, the labels never jump
 - If you click the same button multiple times, whether quickly or slowly, the labels sometimes jump
 - If you wait for the fifteen-second auto-update (in my new version that has the live updates), the labels always jump.

The jitter happens regardless of whether the button is an engine-builtin stat from GetTeamStatsHistory (like metalProduced) or the ZK-specific ones from GetTeamRulesParam (like metal_income).

Note that when you click the same button multiple times, the _same_ numbers are redrawn (and sometimes jump). But when you wait for the auto-update, _different_ numbers are drawn, and it's the _new_ numbers that jump - the old numbers are removed, then the new numbers are drawn slightly too high, then the new numbers immediately drop down into the correct position. Which means the jitter is happening when the new labels are drawn, not when the old labels are cleared.

---------

The code for drawing and redrawing these labels is pretty clean and simple: when you click a button (or wait for the autoupdate), the existing labels and lines are cleared with ClearChildren() and the new labels and lines are drawn with New(). The clearing is done in the button OnClick() and the new ones are created in the drawIntervals() function by way of the getEngineArrays() function. All three of the cases above exercise the same code path even though they have different results.

Therefore, I suspect this is a bug in Chili, or possibly the engine.

I can't troubleshoot Chili or the engine, but I can implement a workaround in the endgraph.lua. I can prevent the buttons from being clicked more than once in a row, with an override parameter for the fifteen-second auto-update call. This would solve the button spamming issue, but the labels would still jump when the graph auto-updates.

If desired, I can add this work-around on top of the new version I've PR'd. Otherwise, someone with more knowledge of Chili / engine will have to look into this more deeply.

**Comment by CrazyEddieTK** [comment]
Regarding the horizontal bars:

I think this will be pretty easy to fix by changing the control from a horizontal stack of objects to a vertical stack of horizontal stacks of objects. I'll work on this and submit a PR against the master branch, since this should be orthogonal to my other PR.

**Comment by CrazyEddieTK** [comment]
@sprunk - Great! How does that change fix the jitter? What was the issue?

**Comment by sprunk** [comment]
I'm not totally certain, as far as I can tell the panel took its child labels into account when determining its own size and the labels had dynamic position based on it.

**Comment by GoogleFrog** [comment]
@CrazyEddieTK I highly doubt it was an issue in chili. The engine has nothing to do with this. The widget is poorly written and what I would have done is rewrite it from scratch.

**Comment by CrazyEddieTK** [comment]
Regarding this:

> - The horizontal bars between players in the awards screen have ellipsis (...) at their right side because the lines have a fixed size which is longer than the window. They should have a relative width (probably using 'right').

Unfortunately that doesn't work. I've found three solutions I like:

One: Making the bars entirely blank, by using a tab character instead of a hyphen:

![some-small-blank](https://cloud.githubusercontent.com/assets/7810334/26569460/e2c8062a-44d8-11e7-88fc-2e33c93193ea.png)

Two: Replacing the bars with Chili lines:

![some-small-lines](https://cloud.githubusercontent.com/assets/7810334/26569477/f4930526-44d8-11e7-80a4-9c88edd98b0e.png)

Three: Completely redesigning the awards panel. Here's my attempt at it:

![some-small](https://cloud.githubusercontent.com/assets/7810334/26569499/0f9a482a-44d9-11e7-9813-051649f10ce0.png)

The misalignment of the bottom right panel is, I think, due to some bugginess in Chili.StackPanel. I can probably work around it with some further effort.

Options One and Two are one-line changes. Option Three is significantly larger. I can put in PRs for any or all of these as desired.

Feedback welcome.

**Comment by KingRaptor** [comment]
My personal preference is for option 2, with a further change (if not too inconvenient) of cleanly separating names and awards (i.e. so the Airforce General box isn't partly below the "Null AI" name label).

**Comment by CrazyEddieTK** [comment]
> so the Airforce General box isn't partly below the "Null AI" name label

I couldn't figure out how to do that. Trying to solve that problem is what led me to my design overhaul. Of course, I'm a complete novice at Chili and I welcome anyone who can show me how to do it.

**Comment by GoogleFrog** [comment]
Option 2. I did not even consider that they used a label full of hyphens instead of a line.

In general avoid stackpanels.

**Comment by CrazyEddieTK** [comment]
Is there any interest in a redesigned awards screen along the lines I showed above? If so, I can fix the alignment issues by doing my own redrawing-on-window-resizing rather than using StackPanel, and add some graphics to make it look prettier.

**Comment by GoogleFrog** [comment]
I think the redesign takes up too much space.

**Comment by CrazyEddieTK** [comment]
> The horizontal bars between players in the awards screen have ellipsis (...) at their right side

Fixed in PR #2269.
