### ISSUE TITLE
Commander went underground due to jump failure

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K#2249]
See Sakal's commander jump at 2:00. It jumped into oversized collision sphere of a feature, slid into the terrain fissure and eventually went under the ground. A number of attempts to escape, including terraform and jump did not succeed:

See:
http://zero-k.info/Battles/Detail/457913

**Comment by GoogleFrog** [comment]
This is not a moveCtrl issue and the commander did not go underground.

**Comment by GoogleFrog** [comment]
The commander jumps onto a feature footprint. It leaves moveCtrl slightly above the hitvolume of the feature it is jumping into (as intended). It then bounces along the features and falls. The commander should have been able to jump out onto the edge of the cliff but I was unable to make it do so, possibly its origin is in the terrain. I was unable to attempt terraform because apparently that is not an order that godmode spectators can give.

**Comment by GoogleFrog** [comment]
Hang on, I think the commander did go underground eventually.

**Comment by GoogleFrog** [comment]
Here is a ticket about the sinking underground https://springrts.com/mantis/view.php?id=5587

Here is a workaround for being unable to jump out of underground: https://github.com/ZeroK-RTS/Zero-K/commit/068bba8995dd6d00f53c9228de453ef5cb1a9d3d

**Comment by sprunk** [comment]
https://springrts.com/mantis/view.php?id=5587
