### ISSUE TITLE
Turn off unit selection priorities..

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2268]
This is way too advanced feature and should be turned off as it can screw people and can be replaced by unit selector.

Best solution: 
 - default off

Minimum solution (still annoying, less severe): 
 - remove unit priority icons from units
 - make cons same priority as combat units (just units and structures)

**Comment by GoogleFrog** [comment]
I think the minimum solution is the worst option. Some people want selection rank so there should be an easy setting to toggle which enables a fully functional selection rank. Removing the icon and changing the priority would mean that using full selection rank would take too much knowledge to enable. It is a similar case to gestures, we used to have a neutered gestures but now we have a single toggle button which enables fully fledge gestures.

Post-selection filtering isn't really a replacement since the main aim is to reduce mistakes. Well, if you compulsively post-select filter then such a filter can help but it takes a while to learn and I'm not sure if it's good UI. Post-selection filtering with the selected units panel isn't really a replacement for experienced players since they shouldn't waste their mouse time clicking on the panel. Perhaps we could add more keybinds, they would probably even be implementable purely with selectkeys, so adding the option to the hotkeys menu would be very little work. Anyway, I'm saying that selection rank does something which is hard to replace and that I wouldn't add much extra if it were disabled. The question remains as to whether the unique thing that selection rank does is worth the cost.

I'm going to wait for a bit more input from my thread but at the moment it's leaning towards default off. I'd like a supcomm person to explain why it works. My dilemma is that this is a UI feature from a popular game in a similar niche and, most importantly, players of that game have gone out of their way to recommend implementing it.

**Comment by sprunk** [comment]
Some other RTS games other than Supcom had this too (eg Age of Mythology) and I think it's fairly intuitive.

I think most current people will dislike the feature because they're vets too used to the old way (selecting units is one of the most common actions, a few years makes people muscle trained to do it one way).

I think it would be worth disabling it for current people but leave it enabled for newbies.

**Comment by Licho1** [comment]
Another compromise for me is to show key modifiers while selecting. I had no idea you could force select all units. Game should hint you this.

**Comment by Radavvadra** [comment]
This feature seems to be helpful. I personally use it in the default to rank 3 mode since I find it cuts down on needed apm when retreating units and when using cons in a more combatative role eg. shieldball/welderball, but I can still change it to avoid selecting units I don't want moving with the main army.

**Comment by sprunk** [comment]
Hidden by default now: c123dccd4b9f6f4342389b719b04d0948b24965e
