### ISSUE TITLE
Tutorials do not explain Overdrive or Energy Grid

### ISSUE THREAD

**Issue by mvollrath** [ZeroK-RTS/Zero-K#2271]
The economy tutorial demonstrates building a solar collector, mexes, and a factory, but does not go into any detail about how to construct a competitive economy.

**Comment by GoogleFrog** [comment]
I think that is completely fine. Overdrive is not a feature that people need to know exists.

**Comment by mvollrath** [comment]
If you don't want to work on it, that's fine.

**Comment by Fortnox** [comment]
As someone that started a few days ago I would very much agree with mvollrath. I found that I wasn't at all able to beat even the Very Easy AI until I figured out how to use Overdrive effectively because I happened to overhear it mentioned in a tournament video. 

Previously I was constantly confused that I couldn't get my metal economy going, now it's a completely different game and I'm stomping the AI. It would've been really good to have it explained from the get-go.

**Comment by GoogleFrog** [comment]
Ok, thanks for the data. I had assumed that people would accidentally do some basic level of overdrive and that would be sufficient until they delved deeper into manuals. @KingRaptor do you think this could fit in tutorial 2? Perhaps when they build the Solars tell them to build them near mexes because energy increases metal production?

**Comment by sprunk** [comment]
>I had assumed that people would accidentally do some basic level of overdrive and that would be sufficient until they delved deeper into manuals.

As far as I can tell most people want to sit on their initial mexes, porc up, and tek2krog, while actively disliking the idea of expanding. This strategy worked really well in TA and Supcom against the AI (due to metalmakers, powerful defense and the AI being somewhat clueless on how to break it) and in fact was the only reasonable way to beat the campaign (when the AI starts with a full base, you never learn to raid, must have really efficient attrition etc). OD is our metalmaker equivalent so I think it's necessary to teach it to people because they won't want to learn expansion instead.

**Comment by KingRaptor** [comment]
> Perhaps when they build the Solars tell them to build them near mexes because energy increases metal production?

I think I'll put the recommended solar location next to the mex spot, then explain overdrive in the text box once both are built. Another solar ghost building will appear next to the mex so they can try it again and see the effects of adding more energy to the mex.

**Comment by Licho1** [comment]
Btw, 3 year old auto understood overdrive and grid principle by looking at mex color/speed.
Perhaps when placing energy structure there could be recommended spot hint along with expected gains?

**Comment by Anarchid** [comment]
> recommended spot hint

Finding good spots for eco (for anything, really!) is kind of AI territory. But expected gains are an interesting thing to see in a tooltip, i'd like that.

**Comment by sprunk** [comment]
>recommended spot hint

Grid color already does this (blue = good, green = medium, red = bad). Possibly there could be an improvement with purple because it represents both the best possible gain (unlinked mex) and worst, zero gain (energy without any linked mex is also purple).

>along with expected gains?

Tooltip currently contains expected payoff ETA (= cost/gain), do we want both?

**Comment by KingRaptor** [comment]
Added a brief overdrive section to economy tutorial. Poke me if changes are desired.
