### ISSUE TITLE
Populate Simple Settings

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2275]
I've added a widget to handle simple settings. Our few important settings should be added to the interface submenu. Here is a list, suggest addition/subtractions:
- [x] Selection filtering.
- [x] Grab input.
- [ ] Tickbox to enable/disable gesture menu.
- [ ] Main command visibility option. Perhaps reduce the number of options to 3 or 4.
- [ ] Colour blindness type (it is in Graphics with non-simple settings).
- [ ] Camera Type setting restricted to Standard (TA) and Rotatable (COFC).
- [x] Integral menu Grid keyboard layout (for QWERTZ fix). Autodetection would be better here.
- [ ] A choice between minimap on left and minimap on right.

Often we will want the simple version of a radiobutton setting to only show a few options. For example camera type should have only two options.

Also, we may want to show the entire hotkeys submenu.

**Comment by sprunk** [comment]
Main command visibility option: #1248
Cameras: #2185

**Comment by GoogleFrog** [comment]
Those are tangentially relevant. The Integral menu scary command culling option is something that requires adding and then could be added to simple settings, I'm unsure.

The camera options just need renaming to be more informative.

**Comment by sprunk** [comment]
Oh, so "command visibility" is about visibility of the command queue in the world, not visibility of various commands in the menu. Both sound like good things for simple settings.

**Comment by CrazyEddieTK** [comment]
Per comments on 10dac3f6257d89b1fa7eea562dbb4a355c8532f0 the intention is for the menu to have three modes, selected by an always-visible checkbox and a separate button buried in the menu. I think that's the wrong approach.

Instead, the menu should be the same for all people at all times in all circumstances. The menu needs to make it easy to do important things but possible to do anything.

I recommend that Menu -> Settings display the items discussed here (the "Simple Settings"), preferably all on a single page, but potentially with some submenus IF there are only very few submenus and IF the menu button labels make it _blindingly_ clear what is underneath them. The same page should also have a button labeled "Advanced Settings" which takes you to the top level of the _actual_ settings menu, from which all settings are accessible regardless of simpleness or advancedness.

**Comment by CrazyEddieTK** [comment]
"Use selection filtering" should be "Smart Selections". Neither one explains _exactly_ how it works (although the tooltip provides a useful summary), but the latter provides a better intuitive explanation of what it _does_.

Smart Selections off by default will leave fewer new players confused and irritated when selections don't work like they expect them to. On by default will allow more new players to discover this unfamiliar but useful feature, even if they have to learn it by trial-and-error. Off is the safe choice, On is the bold choice. Neither is wrong.

"Grab Input (lock mouse to window)" should just be "Lock mouse to window".

On the main menu screen, the "Quit game" label needs more space above it, so that it and the three buttons are better separated from the buttons above. Actually, the sequence should be:

Quit Game (capitalize the G)
.Vote Resign
.Resign
.Quit
[empty space]
Save and Load
.Save Game
.Load Game
[empty space]
.Settings
.Help
.About

**Comment by sprunk** [comment]
Blizzard games call grab input `Confine mouse cursor` and use a radiobutton:
 * Off
 * On
 * Smart, which is Off in the menu and On ingame.

**Comment by Oflameo** [comment]
Please disable simple settings by default. They made the interface much worse by hiding options I needed years ago from me. I disabled them before but I forgot to re-disable them after a bug with rapid made me reinstall.

**Comment by GoogleFrog** [comment]
I don't think the remaining things need to be added to simple settings. @Oflameo this is not a forum, if you have an issue make a ticket about it.
