### ISSUE TITLE
ivand wants to rewrite targeting priorities gadget

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2288]
ivand is @lhog. @GoogleFrog seems to have missed it in #zkdev chat.

>[ivand] GoogleFrog, what do you think if I rewrite the targetting priorities gadget from scratch? I think I can make it produce determenistic result based on direct comparison of several criteria. See my old draft https://github.com/lhog/Zero-K/blob/b4e9af0bad1fa42ad8f6162f01caffb927c096a4/LuaRules/Gadgets/unit_target_priority2.lua#L373-L426

**Comment by lhog** [comment]
The idea is to use relative priority based on a series of comparison between the current target and the existing best target using series of comparison criteria, rather than trying to fine-tune the magic numbers making up equation of everything as in the current target priority gadget. Partially inspired by #2270.

**Comment by GoogleFrog** [comment]
I think that this would create work for me and, with everything else that needs doing, I don't think I have the time for it. Can you show that the behaviour is better and no slower once you implement it? Can you then support all the bugs that will pop up?

**Comment by lhog** [comment]
I think the new gadget will be slower than the current just based on the amount of information it gathers and processes. Whether the slowdown will be significant to the gameplay is yet to be seen.

As far as better behavior I expect units to prioritize better based on hit probability and other factors. In example currently you can draw enemy's artillery fire just by running flea on patrol a bit in front of the static defense, with my implementation it will never happen as hammer's probability to hit flea is guestimated around 5%.

But most importantly the target decision process is fundamentally different. The series of "if then" conditionals improves the code readability and makes it easy to add new criteria or change existing ones. Something that will never become easy with the current implementation.

I can support my code.

**Comment by sprunk** [comment]
>rather than trying to fine-tune the magic numbers making up equation of everything (...)

>as hammer's probability to hit flea is guestimated around 5%

That sounds like a poor example because hit probabilities are more or less magic numbers. To some extent they can be derived from stats but then you just get some values that can be piped to the current Equation Of Everything.

**Comment by lhog** [comment]
5% is a calculated value and it is derived from from stats. Although it's not accurate, at least it's consistent for a given weapon.
Magic numbers are different beasts. These are semi-random hand-picked weights to accommodate a dozen of completely different parameters into a cumulative value - priority. You can find them spread thin across https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/unit_target_priority.lua

The whole point of my implementation that it's very easy to change priority selection algorithm, including addition of new criteria, without the need for guessing and fine-tuning the weights.

Anyway if you feel this is not required or even detrimental, I'm not insisting on my implementation.

**Comment by mtroyka** [comment]
unless someone broke it target priorities should already have a speed modifier for units that are bad at hitting fast stuff. Hammers shouldn't shoot moving fleas unless there's nothing else within range that they can shoot at.

**Comment by lhog** [comment]
Ok, as I see no enthusiasm I guess it's not a good idea. You can close the ticket.

**Comment by GoogleFrog** [comment]
Here is a more detailed explanation of my stance.

I have two competing aspects regarding projects of this type. One side of me wants unit AI to be as good as possible. Smart units is a major draw for me and it is satisfying to see them make good local decisions. It is fun to tinker with unit AI, target priorities etc.. and chase edge cases or things that won't come up in games. On the other hand, if Zero-K is ever to be polished then you've got to stop, or at least postpone, the tinkering of this type. The current target priorities are already quite smart so any improvement will have minimal practical impact on players.

What is your motivation for rewriting priorities? Have you spotted edge cases (not fixable with the current gadget) that impact on the actual player experience or are you motivated more by the satisfaction of having a problem perfectly solved? I would like to rewrite priorities but it would be under the latter motivation so I can't justify the time. I can have more fun elsewhere (factoring in the lengthy debugging period after the rewrite) and the ZK project as a whole would barely benefit compared to the other parts of the project that require work.

If you want to improve priorities for practical, player facing, benefits then identify edge cases that occur and see whether they can be fixed within the current system. This requires much less work and is less likely to generate bugs. As one example consider overkill against low health units. The giant table of priorities does not include as much information about overkill as it could. This does not solve all issues though. For example a Scalpel will prefer a 100 health Ravager to a 500 health Ravager even though both are killed in one shot. Perhaps health could be cached and compared to weapon damage to modify priority in these cases.

Everything has bugs and I worry that I will end up being forced to fix some of the. On a glance through I see that you are using statsdamage and statsprojectiles in a game mechanics gadget. These values are intended purely for UI so someone may change them in the future for UI purposes, breaking priorities. Also, the return values from AllowWeaponTarget imply to me that you wrote the gadget assuming that every target passed to AllowWeaponTarget is able to be fired upon. That is, that it is in range and not occluded by an ally unit or terrain.

The current gadget exists because Spring has noticeably awful default priorities to the extent that a basic gadget could do much better. My defensive approach to performance is because AllowWeaponTarget is called twice a second for each unit which is in or almost-in range of each weapon (ignoring occlusion). That is about 5000 calls a second for two armies of 50 units. I thought there was no reason to flirt with potential performance issues so I implemented what I could with the restriction of one set of Spring calls for each involved unit. Heatrays now break this rule but I think they are worth the exception.

**Comment by lhog** [comment]
Thanks for the explanation @GoogleFrog. Appreciate that.

I think you are right as my motivation was mostly to do things right and improve readability/maintainability of the code. It may yield better practical results, but I'll never know unless I finish and test it (the current code is only like 30% complete).  So I'll leave my current code as it is in case there's a need to return to that question in the future.

I think the way scalpels make their preference now is a right as one healthy ravager is less of an evil than two half-healthy ones. Having that said in my implementation I planned to introduce a feature that blocks spending high alpha shots on units not worth it. It's indeed rarely justified if screamer or sniper waste their shots on blastwings or fleas. It was relatively easy to do as I explicitly tracked weapon damages, reload time, and target health & cost. Also before going into priorities, I checked the target on whether it should be targeted/evaluated at all ("return true" stab function at the moment).

**Comment by GoogleFrog** [comment]
My point with the Ravagers was that both die in one Scalpel salvo and the 100 health Ravager is more conveniently finished off by low reload time weapons.

Shot blocking has a few related tickets. I can't find whether I said this on a ticket but my plan is to replace firestate and have units default to the middle state. Here are some tickets:
 * https://github.com/ZeroK-RTS/Zero-K/issues/1169
 * https://github.com/ZeroK-RTS/Zero-K/issues/1116

**Comment by lhog** [comment]
Now I see what you meant with ravager example. Probably a good idea, but again the weight selection isn't trivial. Here's example implementation: https://github.com/lhog/Zero-K/commit/6e6fcfa1c58987ccd450573e26b4c8faee841049#diff-09aa86ab9121f6854dc1f24027c24fc9R215


As far as intelligent shot conservation, can you please write down how you want it to look from UI perspective. Also I'm not sure I understand the rationale for _all_ units to be in return fire state. Does it make sense for units like glaive? Please elaborate.

**Comment by sprunk** [comment]
The middle state would not be return fire. The states would be "hold fire", "smart fire" and "fire at will" (return fire - removed from the UI). "Smart fire" incorporates various things like OKP, stuff mentioned in the above tickets, possibly not firing at radar, not firing from cloaked etc.

**Comment by sprunk** [comment]
General rewrite unwanted, for shot blocking refer to the linked tickets.
