### ISSUE TITLE
Queuing a command should cancel non-terminating orders

### ISSUE THREAD

**Issue by CrazyEddieTK** [ZeroK-RTS/Zero-K#2317]
If you select a constructor that is guarding a factory and tell it to build a line of windgens using shift-click, it doesn't work. The Guard order never terminates, and so the construction never starts.

This is technically correct, but it's a noobtrap. We should special-case it away.

You can make the same argument with Patrol. There's never a reason to queue an order for a unit that's currently on Patrol because the queued order will never happen. So if someone _does_ do that, rather than creating the false impression that the unit will eventually do the requested command (i.e. drawing the unreachable command queue) we should do what they probably _wanted_ to do, which is cancel the Patrol and start executing the rest of the queue.

**Comment by GoogleFrog** [comment]
Guard terminates when the unit dies so the most useful case is not feasible. Even patrol terminates when you remove the patrol command by reissuing the command.

**Comment by sprunk** [comment]
I wouldn't do that for any regular Shift+command.

Shift+build is an exception to consider because Shift has a somewhat different meaning there.

**Comment by Topkack** [comment]
why not just building lines without shift?

**Comment by GoogleFrog** [comment]
Spring doesn't work that way. The construction hotkeys UI is fairly hardcoded.

**Comment by GoogleFrog** [comment]
I've watched some new player experience and think this should be implemented. The issue is with preserving current behaviour and I am not really one to judge this. I do not make long complicated order queues but I know there are people who like long queues.

Here is my current idea:
 * When you press shift you get the token.
 * If you issue a command and have a token then relinquish the token and remove all guard and patrol orders from the queues of all selected units.

We may want the second point to "If you issue a build command ... all selected units which can build", following @sprunk.  However I don't know what benefit this would confer and it would be inconsistent.

This allows you to queue commands after Guard as long as you issue them all without releasing shift. I came up with an example where you may want to do this. Have a bunch of constructors guard an antinuke and queue another antinuke. The constructors will repair the antinuke and make a new one if the first dies.
