### ISSUE TITLE
Buoys regenerating while surfaced = Invincibility (+60 combat repair)

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2331]
Happened a few times during the first 5 minutes:
http://zero-k.info/Battles/Detail/460776

It's visible by Buoy having HP (+60) while also firing at the enemy.

**Comment by sprunk** [comment]
Regen while surfaced is by design but as I understand you want the value to change.

**Comment by DeinFreund** [comment]
Wasn't regen supposed to be based on depth? Currently their regen changes if you push them around based on the groundlevel below them, making pushing the best strategy at killing them. Doesn't seem very intuitive.

On the other hand, buoy now hardcounters ships, so they're finally not op at a thing.

**Comment by sprunk** [comment]
It's intentionally based on groundlevel so that floaters can regenerate.

**Comment by DeinFreund** [comment]
Floaters only float when enemies come nearby though. So limiting auto repair to underwater would fit the theme of not having any combat repair except for a few special units(detri, strikecom).

**Comment by Aquanim** [comment]
Is this a recent change?

('by design' suggests not but I don't recall buoy hardcountering ships that badly.)

**Comment by GoogleFrog** [comment]
I recall intentionally making this change and the gadget was last edited three years ago so it is by no means recent. It is good news if Buoy hardcounters ships because sea-Buoy is one of the most interesting units. It doesn't shoot at subs. It can't move a fire. It is slow. If Buoy is actually good then there are many ways to make an interesting game with a balanced Buoy.

What is this theme of not having combat repair? I don't see how the fact that there is little combat repair is relevant.

**Comment by DeinFreund** [comment]
In this case buoy has the best autorepair of floaters(1.5 times Grizzly), yet there is no mention of it in the unit description. It seems a little overpowered for its price when this is used well, but I wouldn't mind leaving it as is and seeing how it really develops.

**Comment by sprunk** [comment]
>I wouldn't mind leaving it as is and seeing how it really develops

Nothing to do for now, reopen if it develops into degeneracy.
