### ISSUE TITLE
Transports assisting a factory sometimes return the unit they were meant to transport.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2367]
To reproduce this set nocost and high game speed. Spam units from a factory with a simple waypoint and guard the factory with transports. I suspect what happens is that the transport cannot find anywhere to set down the unit and so the unload command fails. This seems a bit unfix-able if that is the case.

**Comment by TheToric** [comment]
Can confirm It happens due to no room to drop off. Set 2 constructors to build a single large structure. have only one transport that can pick up a builder. If the structure has already started building when another constructor arrives, the transport fails, as it is trying to drop the constructor on top of the nanoframe. If the transported constructor arrives first, then all is well.

Easiest way I can think of to solve this is to have the tranport drop the unit from a low alt if it cannot unload. However, that could be problematic with walking bombs...

Would it be performance intensive/hard to code to search for a free area pathable by the unit and unload there?
