### ISSUE TITLE
Give Hacksaw LUS burst

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2381]
Angler is designed to miss about half of his shots against planes, so OKP causes it to leave all enemy bombers surviving but with half health.

Watch around 10 minutes:
http://zero-k.info/Battles/Detail/462317

**Comment by DeinFreund** [comment]
I think angler missing shots is intentional. It's always been like that and it represents "angling" well, only sometimes do the fish take the bait.

**Comment by lhog** [comment]
Interesting case.

Might be wrong, but it looks to me, that BlockShot is only called once per whole salvo (in the beginning), while it's possible that target gets changed between individual shots (and it's getting changed because units perceived as doomed are de-prioritized and cleared as attacker's current target).

Others may have better ideas, but mine is to make Angler shooting LUS scripted, so that each projectile is individually checked.

I might look into this thing when I have some spare time.

**Comment by GoogleFrog** [comment]
I think do the LUS burst for Hacksaw as well.

**Comment by lhog** [comment]
Ok.
