### ISSUE TITLE
Enable reload UI for LUS burst units

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K#2392]
@GoogleFrog, as I'm working on the topic, I'd like to discuss how LUS reload bar/UI should look like.

For reload bar I see a few simple options (Angler is used as example):
```
local gun = {
	[0] = {firepoint = rbarrel1, loaded = true, readyToAim = true},
	[1] = {firepoint = lbarrel1, loaded = true, readyToAim = true},
	[2] = {firepoint = rbarrel2, loaded = true, readyToAim = true},
	[3] = {firepoint = lbarrel2, loaded = true, readyToAim = true},
}
```
1) Display reload time for gun[0] projectile of LUS salvo. Cons: shows reload bar while other 3 projectiles might be available for shooting, a bit confusing. This is how it's implemented in my WIP code currently.
2) Display reload time for the projectile shot last. Cons: reload bar completes, when 3 other projectiles are already reloaded. Basically same issue as (1)
3) Display reload time for the projectile shot first. Again almost equal to (1), except not hardwired to be gun[0] projectile.
4) Display sum of reload times of all non-loaded projectiles normalized to 100% when all 4 are loaded. Cons: unit might start shooting even before 100% is reached. Once a shot is made, progress is reset by 25%.

Other ideas include:

1) @sprunk : ```https://i.imgur.com/vxbygHQ.png i thought that it (bar) could be 1 but overlaid. basically if one is at 20% and one is at 70% then 0-20 is one color, 20-70 is another color and 70-100 % is empty``` Requires quite heavy rework of unit_healthbar code and shader.

2) @Anarchid : ```could be a stockpile icon. either vertical lines for each shot, or even a bullet/missile icon + number. doesnt' Screamer do this already?``` Requires some adjustments to when stockpile icon is shown and some heuristic on how large the icon&text should be.

Current WIP code: https://github.com/lhog/Zero-K/commit/da69a22e79c49b4192784f3f5ad34bdc5184094b

![How it looks](https://i.snag.gy/aI9Xov.jpg)

Please discuss.

**Comment by DeinFreund** [comment]
An even more popular unit which this should apply to is defender.

In the case of defender what I'd expect to see is a reload bar as soon as the third shot is fired, until the first shot is ready again. This is because a reload bar implies to me that the unit is currently unable to fire (I don't know of any shooting game where you can fire while reloading..). The disadvantage would be that you never know how many projectiles are actually ready.

The only other thing that'd make sense to me is (3), a reload bar as soon as the first shot is fired until it is ready again. This treats the burst as a single firing action.

**Comment by GoogleFrog** [comment]
There are a few things to consider:
 * Will people learn about the independent reloads.
 * Will people think there is a bug.
 * Will the reload bar be useful to people who know about independent reloads.
 * Consistency.

For consistency and usefulness I would make the reload bar show when the unit is unable to shoot since if you don't look any closer at a unit this is what the presence of a reload bar means. The reload 'time' of the weapon would be (script time) - (real time)*(bust count - 1) to make it the unit start at 0% reload when it shoots all missiles.

The consistent method has 'bugs', for example, "My Defender only shot one missile before reloading" is a possible situation and would look like a bug.

**Comment by GoogleFrog** [comment]
Do the consistent reload. Ideally write a general script for all script reload units that calculates whether the unit should display a reload bar and then sets UnitRulesParams appropriately. A reload frame parameter is much better than a reload progress parameter because it updates smoothly and, in the common case, requires much less unit rules param setting.

**Comment by GoogleFrog** [comment]
Actually, the length of the reload bar should just be the time it takes for one missile to reload. This is how normal bust weapons are displayed.

**Comment by mtroyka** [comment]
Why not just show separate reload bars for each charge? I don't really see an issue with that since the number is never greater than 4 anyway.

**Comment by sprunk** [comment]
4 is relatively many since most units typically approach 2-3 in combat. The extra bars would contain little extra information over just one, especially in the usual full burst case.

**Comment by lhog** [comment]
@GoogleFrog , see https://github.com/ZeroK-RTS/Zero-K/compare/master...lhog:lusReload3

I've updated your code scriptReload.lua & turretmissile.lua slightly, but most importantly added function to Sleep and Update reload status.
Now reload progress runs smoothly. As we track the missile with biggest reload progress, once it's loaded runner up missile causes progress bar to jump somewhere around 90%. Not great, but again one number cannot represent state of 3 independent missiles. I think as far as percentages are concerned the status quo is fine.

As for overlaid health bars... I drafted a fragment shader that allows for overlaid drawing, but integration into unit_healthbars is going to be nightmare. Also, is ZK run on shader-less GPUs supported?

**Comment by sprunk** [comment]
I've discovered there is a multi progress bar in Chili https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/chili/Controls/multiprogressbar.lua

I don't think any widget uses it so I don't know whether it works reliably but if it does it could be used if we want the overlaid bar.

**Comment by GoogleFrog** [comment]
Overlaid bar for what? Chili should not be used on world drawing.
