### ISSUE TITLE
Potential splash/loading screen for zk

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Zero-K#2416]
![untitled-6](https://user-images.githubusercontent.com/14219158/28306043-33742890-6be1-11e7-9066-05185ef3d48b.png)
![untitled-7](https://user-images.githubusercontent.com/14219158/28306044-3379676a-6be1-11e7-84c7-df1cf6a4555e.png)
![untitled-8](https://user-images.githubusercontent.com/14219158/28306045-337c4d40-6be1-11e7-8a86-7ca4e0810866.png)
![untitled-1](https://user-images.githubusercontent.com/14219158/28306046-337cdf76-6be1-11e7-8846-6a778bd91c9b.png)
![untitled-2](https://user-images.githubusercontent.com/14219158/28306047-337e7fd4-6be1-11e7-8418-ac59c04c6f59.png)
![untitled-3](https://user-images.githubusercontent.com/14219158/28306048-33863a80-6be1-11e7-8701-69f6f193c9e3.png)
![untitled-4](https://user-images.githubusercontent.com/14219158/28306049-33ad92a6-6be1-11e7-9c4b-a097f4e02ef6.png)
![untitled-5](https://user-images.githubusercontent.com/14219158/28306050-33b25a3e-6be1-11e7-9ced-40bbea320f88.png)

**Comment by GoogleFrog** [comment]
Engine required. See https://springrts.com/mantis/view.php?id=5659.

**Comment by Licho1** [comment]
I would go without licence, licence might worry steam valve (because steam is not OS)

**Comment by GoogleFrog** [comment]
This is in the engine now. Investigate the archive text position and see if the screens fit.

**Comment by GoogleFrog** [comment]
Chobby support added here: https://github.com/ZeroK-RTS/Chobby/commit/04eb7b833b559a0d6cf9f36e1fad310faa8d9b9c

The loadscreens can cycle. I think some good screenshots would be worth including. New players want something exciting to look at.

**Comment by Sortale** [comment]
I don't think screenshot would work here, this is the starting game screen after all. I just think it would feel weird. but it's just my opinion

**Comment by GoogleFrog** [comment]
What would not work about a screenshot?

**Comment by Sortale** [comment]
this is about the starting game screen isn't it. I just think it's more like industry standard to have mostly the game icon and a few loading text than a game screenshot.

But like always I am most likely wrong

**Comment by CrazyEddieTK** [comment]
I agree, I think the chobby initial loading screen should be something simple like the examples in this thread, not something as complex as the screenshot-based loading screens we use prior to game start. They could perhaps be more colorful, but I wouldn't make them more complex. And there's a certain elegance to the logo-on-black designs above, so maybe being more colorful isn't required either.

I have an SSD and a pretty high-end machine, so the chobby splash page only shows for less than a second. That's not enough time to use a complex screenshot; it goes by so quickly that it just looks like a distracting mess, maybe even something that was shown by accident.

I think it would be better if the initial splash page were hard-coded to be displayed for at least two or three seconds, even if the chobby load doesn't take that long. It would make it seem like an intentional formal presentation of the game rather than an incidental unwanted necessity to cover up the load time.

**Comment by CrazyEddieTK** [comment]
Here are some examples of what I mean by "more colorful" but still simpler than an in-game screenshot:

![image](https://user-images.githubusercontent.com/7810334/28827059-5645ae20-769a-11e7-9945-e42abb55e5e0.png)

![image](https://user-images.githubusercontent.com/7810334/28827082-6b617a28-769a-11e7-81a1-be11b3b14c1d.png)

![image](https://user-images.githubusercontent.com/7810334/28827113-83e5c694-769a-11e7-914a-d8f642035b53.png)

![image](https://user-images.githubusercontent.com/7810334/28827152-a0b10f72-769a-11e7-8324-5c5caa660bf6.png)

![image](https://user-images.githubusercontent.com/7810334/28827189-bf49dbda-769a-11e7-8732-bbd048254828.png)

**Comment by sprunk** [comment]
The main use case here is the first run when the cache is generated, this can last minutes.

**Comment by GoogleFrog** [comment]
This seems to be done.
