### ISSUE TITLE
Apply Unit Renames

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2545]
The list of renames seems to be basically done. At this point we should decide upon a time in the near future to consistently switch over. There are a few tasks.
- [ ] Ask core devs for final ideas/complaints.
- [ ] Create a list of places that hold names or unit descriptions that require updating.

Here are some places I can think of
- [x] Wiki
- [ ] Ingame names/descriptions (including non-english if possible).
- [x] Homepage "Manual:" unit spotlight. This may read from zk, I don't know.
- [x] Featured missions (there are 4 tutorials to check).
- [x] Campaign tips/text. I think this is mostly done.

See https://github.com/ZeroK-RTS/Zero-K/issues/2379, http://etherpad.springrts.com/p/renames and zero-k.info/Forum/Thread/24039.

**Comment by Aquanim** [comment]
I think I have caught most-to-all of the rename issues in the campaign. Any that I missed should be caught in the final review before a given mission becomes 'live'.

**Comment by Aquanim** [comment]
The class changes probably apply to more than just the factory name.

- [ ] Cloaky Bot -> Cloakbot Factory
- [ ] Rocko -> Ronin
- [ ] Warrior -> Reaver
- [ ] Zeus -> Knight
- [ ] Hammer -> Sling
- [ ] Spectre -> Phantom
- [ ] Tick -> Imp
- [ ] Eraser -> Iris

- [ ] Shield Bot -> Shieldbot Factory
- [ ] Roach -> Snitch

- [ ] Light Vehicle -> Rover Assembly
- [ ] Slasher -> Fencer
- [ ] Leveller -> Ripper
- [ ] Wovlerine -> Badger

- [ ] Penetrator -> Lance

- [ ] Banshee -> Locust
- [ ] Rapier -> Harpy
- [ ] Black Dawn -> Revenant
- [ ] Brawler -> Nimbus
- [ ] Krow -> Aurora
- [ ] Valkyrie -> Charon
- [ ] Vindicator -> Hercules

- [ ] Hawk -> Raptor
- [ ] Wyvern -> Likho
- [ ] Vulture -> Owl

- [ ] Crabe -> Crab
- [ ] Infiltrator -> Widow

- [ ] Jump/Specialist blah blah -> Jumpbot Factory
- [ ] Archangel -> Toad
- [ ] Sumo -> Jugglenaut

- [ ] Tank Foundry
- [ ] Panther -> Blitz
- [ ] Banisher -> Ogre
- [ ] Reaper -> Beast
- [ ] Pillager -> Emissary
- [ ] Copperhead -> Minotaur
- [ ] Goliath -> Cyclops

- [ ] Amphfac -> Amphibious Base

- [ ] Shipfac description -> Produces Naval Units
- [ ] Ronin -> Envoy

- [ ] Catapult -> Merlin
- [ ] Bantha -> Paladin

- [ ] Defender -> Picket
- [ ] Cobra -> Axe
- [ ] Screamer -> Artemis
- [ ] DDM -> Desolator
- [ ] Anni -> Lucifer

- [ ] whatever airpad is -> Airpad

- [ ] Sneaky Pete -> Cornea
- [ ] whatever antinuke is -> Antinuke
- [ ] Behemoth -> Tyrant
- [ ] Silencer -> Trinity
- [ ] Owl -> Glint

- [ ] Knight Commander -> Commander

**Comment by Aquanim** [comment]
Unit names also appear in Chobby.

**Comment by Aquanim** [comment]
The homepage unit spotlight does not appear to have updated automatically. Wiki and campaign should be done now.

**Comment by sprunk** [comment]
There does not seem to be a standard for localising names:
 * German keeps English for all names.
 * Polish keeps English for proper names (eg Convict) but translates the generic description ones (eg Radar Tower).
 * Russian translates all names but it has a non-Latin script.

Most systems have merits:

| x | Latin script | Other script |
|-------------------|----------------------------------------------------------------|----------------------------------------------------------------------------------------------|
| Keep English | No confusion in multiplayer, but kinda ruins the point. | see below |
| Translate generic | Decent middle ground between the two. | see below |
| Translate all | Familiarity, the whole point of localisation. On the other hand, MP confusion. | There's MP confusion due to script difference anyway so might as well do a full translation. |

Possibly it's okay if there's no standard. German is much closer to English so might get away with raw names where in Polish they would be very awkward.

**Comment by GoogleFrog** [comment]
Main ticket is complete.
