### ISSUE TITLE
Briefing music is not well handled by new campaign

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K#2584]
The recently restores briefing music works great in multiplayer, but not so well in campaign. Briefing music plays for a moment then immediately switches to peace. This seems to be because commander is spawned before briefing objectives are confirmed, rather then after.

Spawn commander after player clicks continue? Or is there a better solution?

EDIT: This is actually not much of a problem if a fade in is added to briefing track,

**Comment by GoogleFrog** [comment]
The campaign spawns everything, starts the game and then pauses for the briefing screen. This makes the game smooth after the screen is closed, because it is just an unpause. I don't want to switch to briefing before the game starts. I don't even think that briefing music is required in the campaign as the peace tracks fit reasonably well.

**Comment by The-Yak** [comment]
Okay makes sense, my workaround is good enough this can be closed.
