### ISSUE TITLE
Start Boxes widget causes black pregame UI on some maps

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K#2640]
(1)Load up aetherian void 1.3 / 1.4
(2)don't place commander
(3)open widget list and observe how turning off Start Boxes fixes black stuff

Sprung gets credit for figuring this one out, I don't know why this only seems to affect aetherian.

I don't see anything wrong with my startbox config, https://pastebin.com/SzTbqLAw

**Comment by The-Yak** [comment]
Actually, something unique about aetherian is the multiple startboxes for a single team. I haven't done that for any other maps.

**Comment by sprunk** [comment]
Not a problem, Adansonia does that.

**Comment by The-Yak** [comment]
I'm not entirely sure that's related anymore

**Comment by The-Yak** [comment]
Also, It's not just pregame stuff. ETA on factories is blackened as well. All of these blackened elements only happen when Economy View is on.

**Comment by sprunk** [comment]
The blackness is actually the map fog (!) obscuring those UI elements. As far as I can tell, that they sometimes are **not** blacked is the bug here. These UI elements are in-world so fog obedience is the correct behaviour.

I don't know why the ground and units don't get obscured but the map has `fogStart` == `fogEnd` which sounds like it would result in weird stuff like this.

**Comment by The-Yak** [comment]
Normal fogstart and fogend settings fixed the issue. I'll make a hotfix for the map.
