### ISSUE TITLE
Select all units of given type does not work for cons

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2680]
1) build some combat units, select one, press ctrl+z
-> every unit of given type gets selected

2) build some cons, select one, press ctrl+z
-> FAIL: game deselects everything

**Comment by The-Yak** [comment]
was wondering why my ctrl-z seemed to randomly fail sometimes.

**Comment by GoogleFrog** [comment]
This is an intentional thing for maybe ten years. Ctrl+z deselects constructors before selecting all units of the selected type because it was deemed too dangerous as people may accidentally select a constructor in their selection and then destroy all of their construction queues. Maybe this can be changed now with selection rank.

To select a lot of cons zoom out and press ctrl+x to select all units of type on the screen.

**Comment by Licho1** [comment]
I am talking about scenario, where i ONLY have cons selected and i click it.
Surly i would be uber dumb to want more of the same cons selected by accident right?

The condition can check and apply rule only if there are cons + not cons together. But even that is questionable with ranks.

**Comment by sprunk** [comment]
Works now.
