### ISSUE TITLE
Default right click on damaged commander is wrong

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2688]
It should be reapir but is guard.

**Comment by GoogleFrog** [comment]
What happens when you guard a damaged unit? Does it repair it or does it aid its construction tasks?

Right click guard on damaged constructors was added because right click guards non-damaged constructors and you often want to guard constructors. Imagine you have a constructor and you want to tell 3 other constructors to assist it in its construction. You right click on the constructor. When repair was the default this leads the units repairing for a bit and then going idle, as if they have ignored your assist command. The same thing is a common occurrence for factories. You right click thinking to assist, not realizing that the unit is slightly damaged.

I think right click on damaged commanders is not wrong.

**Comment by Licho1** [comment]
That is precisely what i want though, often i space click nearby cons or nanos to interrupt them, do one time repair and then leave.
For other units, this works (for other damaged units) but commander is strange exception.
Why is commander special?

**Comment by sprunk** [comment]
There is a toggle to make RMB on all constructors guard instead of repair. Commander is currently considered a constructor but we can give him a separate toggle (though that would still leave the question of the default value of this toggle, I don't know what it should be).

**Comment by Licho1** [comment]
I see .. well at least there is some consistency with constructors.  I guess its ok then.
