### ISSUE TITLE
Is ronin combat stats too good?

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K#2699]
Is ronin too good for a cost? It's very cheap and could be mass manufactured in a very short period of time,  It's quite sturdy for the cost, fast moving so it counters raiders like ducks and to an extent bandits, has fast projectiles, rate of fire is such that a mid-sized group of Ronins create a wall of rockets. Also they have a very good synergy with Reavers so that combo is quick to form and quite hard to stop. Together they counter raiders, other riots, most other skirmishers, assaults, LLTs, defenders and can hit and run into HLTs without much loss.

Perhaps Ronins should enjoy lesser rate of fire and gain some cost or w/e?

Some games for reference, where lower ELO player uses the aforementioned unit combo and stomps higher ELO players easily:
http://zero-k.info/Battles/Detail/480459
http://zero-k.info/Battles/Detail/480060

**Comment by Anarchid** [comment]
I don't think these replays are good evidence of anything but flaws in style. 

From what i've seen of follow-up games by gajop trying to copy this strategy (mostly gajop), they end up  brutally annihilated by other players with longer-ranged skirmishers (rogue,recluse), death balls (shield, spider), or AoE weapons of choice (phoenix, imp, snitch, firewalker, etc).

**Comment by lhog** [comment]
Another one, somewhat related, this time apparently without "idiosyncratic vulnerabilities in play style"
http://zero-k.info/Battles/Detail/482419

**Comment by Anarchid** [comment]
>  without "idiosyncratic vulnerabilities in play style"

Not only does this replay show Reavers rather than Ronins doing the damage, but also i can't imagine how you would say "without idiosyncratic vulnerabilities in play style" given that you watched the actual game.

**Comment by lhog** [comment]
Would you like a game where the majority of the in-game interaction is fightmove skirmishes of Reavers & Ronins from both sides? 
http://zero-k.info/Battles/Detail/483185

**Comment by sprunk** [comment]
I think the problem lies in all three basic cloakies. Glaive makes for a very smooth early game and afterwards is really good at punishing attempts to counter Ronin/Reaver with skirms.

**Comment by db81** [comment]
Are reavers and ronins the new name for rockowarrior? That's been my go to setup for ages, it works well but it didn't catapult me over 2k. Never felt it was OP.

**Comment by Anarchid** [comment]
I have watched the replay. Here is my understanding of what happened. I apologise for a somewhat sarcastic tone of narration.

At 5 minutes, the first Ronin makes its first shot. By this time there are 5 Ronins on the map: one participating in the engagement on wesley's side, two moving to reinforce it, and two coming out of Dein's factory. There are nine Reavers by this time on the map. Wesley has a 2k army advantage due to effective attrition trades, better expansion, and less excess. Clearly, achieving all this with its very first shot means Ronin OP.

The engagement lasts about two minutes, during which wesley seems to exclusively micro this thing while having reinforcements queued on a rally point. He achieves a marginal victory, destroying one expansion and doing efficient unit trades, then retreats to reinforce. Note that his army is like 3 Reavers for each Ronin. Ronin is so OP that even minimal presense of Ronins makes an army three times stronger. As a result, wesley now has a 3k army lead and a +10 income lead.

At 7:00 wesley reinforces his troops and gets back on the offensive, with a continuous stream of reinforcements that significantly outnumber Dein, as well as a porc push by his commander. Dein builds some glaives, which predictably get mauled by Reavers. Dein also starts an airplane factory. Ronin OP.

By 7:50, clearly because Ronin OP, wesley has a twofold army advantage. The airplane factory starts making a Phoenix. Wesley's eastern contingent, a small army of 3 reavers and 3 ronins which were sitting idle from like fifth minute, start to move towards Dein's exposed commander. Being able to dominate the map by just sitting there and doing nothing for most of the meaningful part of the game is clearly OP.

The reavers die, damaging the commander. Ronins also take some potshots but are deterred for a while by several lotus even after being reinforced. The commander walks a little at 10% health and then just sits there as ronins finally take the lotuses down. 

At 08:40 the Phoenix makes its strike, killing 1 ronin. That a tech switch done by a top10 player into a riot unit manages to kill only one ronin with its reveal clearly is a sign that Ronin OP. The other ronins notice that they are being bombed, and move onwards, killing the commander that is sitting just a few steps ahead. Brutal. Also by now wesley has a twofold army and income lead.

At 09:00, two Phoenix make a simultaneous strike on a group of wesley reaver-ronins fighting dein's reaver-ronins. This is more effective than the previous strike, almost immediately increasing Dein's attrition rate from abysmal ~50% to 86%. WIth this opening, one of Dein's Reavers makes it to wesley's commander, which is busy erecting razors to defend against phoenix. The razors do nothing, the next phoenix strike goes directly for the reaver-mauled commander and finishes it off. I heard that phoenix is useless and even the best players build only 1. Anyway, Dein's attrition goes to 96%. This is still not looking good enough to save him from wesley's 2.5x income and army lead. Also Razors succeed in killing the Phoenixes, so now Dein has none. He doesn't make any more, either, just deciding to spam more Ronins and Reavers at 3:1 ratio. Clearly this is going to work because Ronin OP.

Actually, it does. Dein manages to do a raid with a lone Reaver mauling some lotus and mexes, and wesley obliges by sending glaives to kill the reaver. Wesley also tries to use glaives to kill dein's 3:1 ronin-reaver mix, with no success. Dein's attrition goes to 113%. Also with commander loss and the reaver raiding, wesley is only at 2x unit value (most of it in a massive windgen farm) and 2x income. He's only 500m ahead in combat units.

At 13 minutes both sides massively shift to glaives as most Reavers seem to have died by either walking into porc or getting killed by Ronins (which are OP). The glaives quickly clean up Ronin balls for both sides just as both planned. But not before Dein's eastern main expansion dies to a bunch of Ronins and a single Reaver. This doesn't hurt so much because Dein is massively reclaiming the remains of reavers and ronins which dies right on his doorstep, with +38 income to wesley's +45. 118%.

Then wesley shifts to gunships and also a bunch of his glaives make it past an actively shooting Reaver and kill some caretakers, and the reclaim field outside of wesley porc runs out, and now Dein is at five-fold income disadvantage, and resigns.

---

I don't think this game is good at illustrating Ronin OP. But that's not new, i don't think any of the games you linked here are useful.

**Comment by lhog** [comment]
Fortunately you included TL;DR after the wall of text, otherwise I wouldn't get what the point is.

Let me just ask audience one question:

Is current riot-skirmish no-brainier, that makes most of the other units redundant, really how ZK with its extensive class system should look like? Call me old school, but in my book raiders, assaults and special units are things that make the game compelling to play and to watch. Riots and skirmishers should have secondary roles, being counters to former and latter respectively, but not the main composition units.

**Comment by Anarchid** [comment]
Oops i thought over having written that wall of text and decided it was not a good thing. Alas, too late.

Riot-skirmisher balls are historically strong in any kind because riots counter the things that counter skirmishers. The solution to them historically has been things that counter skirmishers while not being raiders. 

Phoenix worked in the replay you linked. So would have other things. The real thing wesley does and which noone seems to notice is tempo. He's a really aggressive player, and he's good with his aggression.
