### ISSUE TITLE
Crash during second game of the campaign

### ISSUE THREAD

**Issue by milipili** [ZeroK-RTS/Zero-K#2708]
Enjoy :)
[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/1609544/infolog.txt)

**Comment by GoogleFrog** [comment]
What happened just before? Were you playing? All I see is a truncated loading log.

**Comment by milipili** [comment]
Yes, started to play, crashed a few minutes after (don't remember how much time - that's the first time I try this game).
Followed the installation process, even if I would definitely prefer a normal .deb archive to be honest :)
I have a i7-6800K, and I observe that games crash more often with it (more core certainly). For example Planetary Annhilation crashes only from time to time with a i7-6700k, but crashes just after 2min with this i7-6800k. Probably the same happens here. A little thread-safety issue and bloum.

I can try to recompile it and to run it in debug eventually if you need help, assuming this is not painful to build it (didn't take a look honestly so far).

**Comment by milipili** [comment]
More about the setup: debian testing, i7-6800k, 64G ram, and a little 980 ti.
Didn't try with dual monitor as the second one is turned off for now.

**Comment by GoogleFrog** [comment]
This is not the engine development bug tracker, if you are really keen you could try their bug tracker (https://springrts.com/mantis) or the forum (https://springrts.com/phpbb/viewforum.php?f=12). My only idea for this ticket would be to report it to the engine tracker.

A crash related to memory corruption and threading was recently fixed in the engine (https://springrts.com/mantis/view.php?id=5855). I will wait until we are using that version (hopefully no more than a week) and see what happens after that.

**Comment by sprunk** [comment]
https://github.com/spring/spring/commit/122fab1916131451f3ac3e2cf044df1fc7269fc1
