### ISSUE TITLE
Ctrl+LMB selection as spec

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2734]
The left click selection modifiers are currently a bit disorganized and not consistent with RTS standards. Modifiers have been messed with for basic spring commands so this should be possible. It could also be implemented in a more brute-force method.
- No modifiers. Clicked unit is now the only selected unit.
- Shift. Clicked unit is added or removed from selection.
- Ctrl. Selection is replaced with all units of the clicked type which are on screen.
- Shift + Ctrl. If the clicked unit is selected then remove all units of selected type from selection. If the clicked unit is not selected then add all units of the clicked type which are on the screen to the selection.

I am unsure of what Alt could do, perhaps global selection?

The current behaviour seems to be as follows:
- No modifiers. Clicked unit is now the only selected unit.
- Shift. Clicked unit is added to selection.
- Ctrl. Clicked unit is added or removed from selection depending on whether it is selected.
- Shift + Ctrl. Identical to Ctrl.
- Alt does nothing.

This current behaviour also applies to the selection of multiple units, with Shift adding to selection and Ctrl toggling. Drag selection seems fine to me and I would not worry about click selection being inconsistent with drag.

**Comment by CrazyEddieTK** [comment]
This widget behaves oddly when spectating.

- Ctrl + click selects all units of the selected type that are on screen _and which are owned by_ the player that owns the clicked-on unit. Contrast with Spring's double-click behavior, which selects all units of the selected type that are on screen _regardless_ of owner.
- If you select units from Player Y, then ctrl-click on a unit from Player Z, it may fail to select anything, or it may select units of that type from Player Y instead of Player Z.

The first behavior is arguably an improvement, as you rarely want to select units from all players while spectating; selecting all units of Type Foo from just one player is handy, and it would be even nicer if there were a way to select all units of Type Foo from all players on a single side.

The second behavior just makes it awkward and confusing to use ctrl-click.

I'm not sure that this is worth fixing, given the obscurity of the use case here. But I thought it was worth noting.
