### ISSUE TITLE
Make limpet more distinct

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2745]
I would recommend giving it serious HP buff or some other defensive ability. Atm its the weakest of all bombs.

It also has no cloak, no jump making it very hard to use properly.

**Comment by Sgathec** [comment]
Yes, maybe it could have the HP to tank some damage.

**Comment by sprunk** [comment]
It already has ~7-8x HP compared to other bombs (Limpet 400, Shield bomb 60, Cloaky bomb 50). Should it get even more?

**Comment by Sgathec** [comment]
Regardless, I think the Limpet is uninteresting alone currently

**Comment by Phytophyte** [comment]
Might the Limpet be given a complementary role, rather than just making it better at suicide? Suicide units tend to be reactionary; I think giving the Limpet a more proactive purpose would help them see more use.

The Limpet is not only a slow-bomb; it's also the Amphbot Factory's fastest unit. Amphbots are almost universally the slowest units in the game. Much like the Spider factory's Fleas, a good scout unit could do wonders to help offset this vulnerability, and make the Amphbot factory more cohesive as a result.

Maybe an increase to the Limpet's sight range, or giving it a short-range radar (much like the Weaver, I imagine) would be suitable ideas for a buff?

**Comment by Licho1** [comment]
It could also be much cheaper unit instead of "heavy" unit. That would make it a natural scout.

**Comment by Phytophyte** [comment]
Being cheaper would help the Limpet serve as a scout, yes. The concern I have with the Limpet is its abysmal 240-elmo sight-range; that really limits its ability to operate on its own.

**Comment by GoogleFrog** [comment]
It does not damage allies so it has many more defensive abilities than other bombs.

**Comment by sprunk** [comment]
>I would recommend giving it serious HP buff

Done c6bd2c29901bf9b894d59edb7e888d2c2516f054 Limpet now has an order of magnitude more health than the other bombs.

>or some other defensive ability

Done 5d5a0022f6988d7af28160e51d15b560fdd58df5 Limpet is now great defensively as it does not damage allies.
