### ISSUE TITLE
Gauss turret aims from hunkered position

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2760]
https://zero-k.info/Forum/Thread/24769

**Comment by Anarchid** [comment]
This is weird, because i distinctly remember implementing a separate,  high-placed piece (`AimProxy`) in the model to serve as the elevated aimpoint stand-in.

The script also [uses](https://github.com/ZeroK-RTS/Zero-K/blob/master/scripts/turretgauss.lua#L153) it, so either something changed in piece coordinates, something changed in aiming in general, or the report is misparsed.

You can change for whether the piece is in its place by uncommenting [line 143](https://github.com/ZeroK-RTS/Zero-K/blob/master/scripts/turretgauss.lua#L143).
