### ISSUE TITLE
Metal spots are not displayed on the resource map (F4)

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K#2812]
Intel graphics card. The issue appeared after the engine change.
https://imgur.com/URp64rP

**Comment by GoogleFrog** [comment]
Impart infolog.

**Comment by GoogleFrog** [comment]
And which engine change?

**Comment by GoogleFrog** [comment]
Try with fresh install.

**Comment by Orfelius** [comment]
https://pastebin.com/5tEBihTz

**Comment by GoogleFrog** [comment]
I expect it was the reordering of the map edge extension widget.

**Comment by GoogleFrog** [comment]
Huh, it was not reordered.

**Comment by GoogleFrog** [comment]
[f=-000001] Error: [LuaUI::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=DrawWorldPreUnit trace=[Internal Lua error: Call failure] [string "LuaUI/Widgets/map_edge_extension.lua"]:384: bad argument #1 to 'CallList' (number expected, got nil)

![image](https://user-images.githubusercontent.com/1318249/36785544-4b2b0902-1cd7-11e8-93f1-d492df31c605.png)

Your problem is crazy

**Comment by GoogleFrog** [comment]
I think this 'causes' it? https://github.com/ZeroK-RTS/Zero-K/commit/bd3620ebe24b3d8789cb0fb09b59be759599e938#diff-182fad85c78b2a88aebded65c7b761b2

**Comment by sprunk** [comment]
The `or` at the end ignored the nil checks.

**Comment by Orfelius** [comment]
Everything seems to be working as intended now.
https://pastebin.com/pNJZcwnj
