### ISSUE TITLE
Aspis shield cannot be turned off, locks out energy

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K#287]
The Aspis (mobile shield walker) uses energy at high priority (if it even respects priority) and has no Active State toggle, meaning that the shield will always drain energy as long as it is active. This is problematic, as construction can be completely locked out until the Aspis is destroyed (by enemy or ctrl+d).

Shields, like Cloak, should be normal or low priority on charge to avoid this deadlock. An Active State toggle for Aspis might help as well, but more as a convenience feature to redirect energy if needed (like Cloak and Radar state toggles).

**Comment by sprunk** [comment]
Relevant: https://github.com/ZeroK-RTS/Zero-K/commit/857991cc1359ec231a689d7a65812e9935a7e971

**Comment by GoogleFrog** [comment]
The base energy change is required because it allows the On/Off button to only affect whether the shield charges. My worry with the shield/tacnuke mechanic was shield link could be subverted by unit AI. This unit AI has not been written (I don't even know whether anyone has considered it) but the fact it could exist means the units are stupid, which is bad.

The unit AI would hold fully changed shields off in areas which may be brute forced with tacnukes. If you fire a single tacnuke at a group of shields then the group will lose 3500 charge and that loss will be spread to nearby shields within a few seconds. This will bring all shields below the tacnuke blocking threshold. A shield with linking disabled could hide within the group and protect it from a followup tacnuke.

Remember that linking is not unit AI. It is an uncaring mechanic which just _happens_. It does not try to be beneficial and can be exploited, it is up to players to exploit it for their goals. It is not a failure of unit AI if the units have no choice.

It is currently also possible to turn shields off through reclaim, morph and stun. Perhaps disabling a shield should cause it to discharge. This would be quite a nerf though. Many EMP and Disarm weapons have a lot of AoE or damage enough to penetrate shields. They would effectively drain the shields for extra damage. Some examples:
 * Tick - Pure AoE, becomes more devastating if it hits a shieldball.
 * Thunderbird - 625 damage and enough AoE to slightly penetrate a small shield. Could give shieldballs an extra 30s to get up to full charge.
 * Faraday, Zeus, Panther (intermittent stunners) - Small buff.
 * Shockley - Takes stunned shields out of action for longer. This is nice mechanically.
My main worry would be increase Thunderbird power vs shieldballs.

**Comment by GoogleFrog** [comment]
Fixed in v1.3.8.12.
