### ISSUE TITLE
Consider reducing PW stuff health

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2891]
See the second bullet point in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1705

>Reduce ingame structure health. Command center is not easily rushable given its large health pool. Some defense around the CC prevents it from being sniped by a losing team. The vast majority of CC destruction that I have witnessed were achieved by an uncontested, fairly static, force (usually a commpush with turrets). This method of destruction does not care how much health the CC has so we may as well lower it as a buff purely to snipes.

**Comment by GoogleFrog** [comment]
Possibly. Maybe evac time should be increased.

**Comment by sprunk** [comment]
Everything that does not have drones probably has okay health (can be sniped by parking 1 gator or something anyway), mostly CC has this problem and CC is not evacuable.

**Comment by Anarchid** [comment]
CC is trivially sniped by a three-strong Reaver drop. The only things that are "problematic" about its sniping is if you want to do it with just bombers, because it takes 12 for its 10k hp. 

But i've lost CC's to Raven bombing runs in the last session, so it's entirely doable.

I would argue that nerfing it to 9k may be good because that allows a single expertly used Skuttle to bust it, but not more.

The thing that *is* extremely hard to snipe in time is Artifacts. These have like 40k or more hp? Some truly horrifying amount.

**Comment by Licho1** [comment]
50k

**Comment by sprunk** [comment]
![slow king](https://raw.githubusercontent.com/ZeroK-RTS/Zero-K/master/LuaRules/Images/awards/trophy_slow.png)

**Comment by Anarchid** [comment]
Email doesn't send edits :)

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/5cecc334d8b7b194f49dbb6fd2e976245bc6e97e

**Comment by GoogleFrog** [comment]
Done.
