### ISSUE TITLE
Burst UI is wrong for Vandal

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3126]
To prevent stuff like #3125, these values would ideally be read from weapon defs directly (`customParams.statsdamage`?)

**Comment by GoogleFrog** [comment]
This created some ugly numbers. For example Picket burst changed from 310 to 312.

**Comment by GoogleFrog** [comment]
310 damage is important because Pyro has 620 HP.

100.1 does not fix the issue, because when you select 4 Pickets you would still see a damage of 1201. I don't care how precise the burst indicator is, I care how useful it is. Numbers which end in 0 are much easier to parse and they need to multiply together nicely. Many weapons deal 0.1 extra damage so it sounds like we're going to need overrides or magic rounding for everything.

**Comment by Anarchid** [comment]
I don't understand why the 10x value has to be round. Doesn't selecting the bunch of units you want to evaluate for their burst value automatically output the total group burst, which you can then directly compare to health of the target, which may be as dirty as combat gets it?
