### ISSUE TITLE
Resources optimization

### ISSUE THREAD

**Issue by AlekseyLobanov** [ZeroK-RTS/Zero-K#3131]
I can see, that a lot of png images can be optimized with optipng. Probably, we should do it? Is it possible to integrate this optimization with current build process?

Sizes for portable build on itch.io:
```
before: 1744528
after: 1743340	
```

**Comment by sprunk** [comment]
Measure how load speeds are affected by the extra png decompression.

**Comment by AlekseyLobanov** [comment]
I'm not sure that this difference is significant.

**Comment by sprunk** [comment]
That's what I'd expect as well. I see three possibilities:
 * load speed is measurably slower. In that case we don't want to do this (speed is more important than size, because disk space is cheap but people's time is not).
 * difference not measurable. In that case it is a waste of time doing this because the benefit is insignificant as well.
 * somehow, load speed is faster (maybe smaller data better fits into cache or something). Very improbable but would be grounds for actually doing the optimisation.

**Comment by sprunk** [comment]
Looks like not happening. Feel free to reopen if there are any advances (better compression gains, or loadspeed measurements).
