### ISSUE TITLE
Structure shadows appear suddenly at ~75% completion

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#3155]
Building shadows appear instantly at around 70%-80% of the construction progress. I suggest gradually making the shadow visible by making it (nearly) imperceptible at first while continuously reducing the "transparency" until the structure is finished.

**Comment by Anarchid** [comment]
Spring's shadows are essentially one-bit. Zero or one, no intermediate opacity. To implement what you want you will have to rewrite the shadows from scratch.

A thing that could be easier to do would be to make the shadows draw from right from the start - draw them even while the unit is a wire mesh. Then the progressing growth of unit height from down up will make the shadows also grow from zero rather than appear wholesale.

**Comment by sprunk** [comment]
I accidentally stumbled upon the value and [it is 666 ‰](https://github.com/spring/spring/blob/4c3fd577fa944fcb9c0ecbe36adf0aafe7d68772/rts/Rendering/UnitDrawer.cpp#L1261)

**Comment by GoogleFrog** [comment]
The construction animation has three parts:
- Wireframe gets built, from the ground up.
- Wireframe gets filled with faces, from the ground up.
- Faces get given a texture, from the ground up.

Each corresponds to 1/3 of the build time. It is probably only feasible to draw the shadow for the unit when it has all of its faces.

**Comment by sprunk** [comment]
Mantised https://springrts.com/mantis/view.php?id=6204

**Comment by sprunk** [comment]
spring/spring@b5e52d1c5c49d378ab35d82688c8570aff30b5f1
