### ISSUE TITLE
Unlimited mexes possible on tiny terrahole

### ISSUE THREAD

**Issue by FFCKLR** [ZeroK-RTS/Zero-K#3178]
![screen00015](https://user-images.githubusercontent.com/34060955/43025953-5801c6a6-8c7c-11e8-9cd1-28ab17dd4714.png)
multiple mexes on the same place 
![screen00016](https://user-images.githubusercontent.com/34060955/43025957-5c454832-8c7c-11e8-8073-275029526a5a.png)
for some reason you are able to place mexes there, the mex spot needs to be surrounded by things 
![screen00017](https://user-images.githubusercontent.com/34060955/43025963-5ec48b54-8c7c-11e8-9865-79198085bbd4.png)
By holding down and getting the terraform thing, it will proceed to add new mex to the pile
![screen00018](https://user-images.githubusercontent.com/34060955/43026075-d42ad4a2-8c7c-11e8-94d2-d98542fe9e42.png)

**Comment by Histidine91** [comment]
Thanks for the screenshots! I'd probably still be trying to repro without them.

**Comment by Licho1** [comment]
From murray:
(In-game Report A Bug not working).

Was used against me to build 57 mexes in one spot and skyrocket the enemy team's income, +175 metal undeserved.

Steps to reproduce:
1) Surround a metal spot with buildings (they don't have to be finished).
2) Queue a mex deep underground (using alt and scrolling far down).
3) MOVE AWAY
4) Complete the terraform job (It will automatically finish after building the underground spike, as it cannot be lowered further because it is surrounded by buildings).
5) Build a mex to completion.
6) Build a mex using alt transform (I don't think the height matters, but I know it at least works with a deep transform). This is the exploit, as you now have 2 metal extractors in one metal spot.
7) Repeat step 6.

You can see Snoke using it in the first minute in multiple games with real players who don't know he's doing it (bannable).

B584592 12 on AquariusCrossing
http://zerok.info/Battles/Detail/584592

B584600 4 on Titan v3.1
http://zerok.info/Battles/Detail/584600

B584558 2 on Red Comet v1.3
http://zero-k.info/Battles/Detail/584558

**Comment by rugrat3** [comment]
here you can see [ffc] using this bug with real players who don't know he's doing it, which is same bannable.
http://zero-k.info/Battles/Detail/584523
