### ISSUE TITLE
Enhancement: More end game graph stuff

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#3232]
1.) Clicking on a user name will toggle a filter to show only clicked on names. (No filter: show all)
2.) Show team average option
3.) Pie chart version of end results?

**Comment by sprunk** [comment]
Related: #2274

**Comment by sprunk** [comment]
1) #4303
2) for comparing allyteams use totals (works better for uneven teams). For intra-team epenis strive to be the best, not just above average
3) Pie charts make the most sense when there's a handful of chunks of varying sizes. Our use case has either many tiny similar-sized pieces which would just blend into each other and not be very informative (when you filter by individual players) or just two chunks which doesn't really help compared to just looking at the plotted lines we already have (if you filter by allyteam). Only being available for the end results because they don't work well for showing change over time doesn't help either.
