### ISSUE TITLE
Consider nerfing Emissary

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#3251]
Pillager being faster than ~bandits~ ducks (still absurd) as an artillery unit is unacceptable, unmoral, and unjust. Cut its speed to impaler speed. It has AOE, and accuracy. Kill it with fire, please.

**Comment by ArchShaman** [comment]
I had a hard time chasing down pillagers with ravagers yesterday. I simply couldn't keep it up. Kinda absurd.

**Comment by Sgathec** [comment]
I think one should buff strengths and nerf weaknesses. However, I think it should not outrun Ravagers because it's an artillery unit. Therefore I might personally reduce speed, but also try to preserve some. I think its weapon area of effect could be downsized too a bit. If the changes make it too weak, the weapon damage could possibly be increased.

**Comment by Anarchid** [comment]
I could argue that accurate weapon with aoe is more of an Emissary strength than having raider speed.

**Comment by Sgathec** [comment]
Maybe. That's why I didn't advocate nearly removing its area of effect.

**Comment by ArchShaman** [comment]
Maybe:
* Nerf speed to impaler speed
* Remove ability to fire on the move completely
?

**Comment by Licho1** [comment]
Pillager was nearly never used before ability to fire on move...
Artileries had this step (need to stop) precisely because they are op otherwise. By allowing fire on move you are making a giant super-skirmisher. It might be ok for impaler because it cannot hit mobiles but not here..

Another option is the past angle restriction. Let it shoot only in one direction (forward), meaning that if the unit retreats it cannot keep shooting and must stop and turn.

**Comment by sprunk** [comment]
What if health 840 -> 800? Heavily nerfs weakness to being sniped by bomber (hits to kill 2 -> 1) but keeps strengths intact.

**Comment by Licho1** [comment]
I am against more glass-canno nerfs.
Nerfs were historically in the direction less HP and buffs in direction more DMG. So I would prefer changing how the unit behaves instead of nerfing hp further. It's a visually big unit and "tank" chassis.

**Comment by Anarchid** [comment]
> Pillager was nearly never used before ability to fire on move...

You are confusing pillager and wolverine. Pillager was never used until people realised it counters everything.

**Comment by Licho1** [comment]
I don't i am pillager was at one point restricted by turning angle of turret. It could shoot only in one forward direction.
That meant, retreating pillager was harmless and it worked less as a skirmisher. I would recommend returning to that state.

**Comment by Anarchid** [comment]
That changes very little IMO, but i wouldn't mind this alongside the speed nerf.

**Comment by ArchShaman** [comment]
Pillager **can** fire on the move though. I can prove this if you want.

**Comment by ArchShaman** [comment]
https://youtu.be/KYer6gK0Lf4

**Comment by Anarchid** [comment]
Okay, fine. This is worse than perma-cloaked blastwings.

**Comment by ArchShaman** [comment]
Oh, I remember the days of perma-cloaked blastwings. Those were fun days.

**Comment by Aquanim** [comment]
I don't see any particularly good reason for Pillager to move faster than Impaler. Speed is an inappropriate advantage for a Tank to have over a Rover in the same role.

Note: tankarty script is currently dumb stupid BOS.

**Comment by GoogleFrog** [comment]
Fix its LUS before doing anything.

**Comment by GoogleFrog** [comment]
Moving while firing has been fixed, and Emissary is now unable to move until its gun is stowed in the forward facing position.
