### ISSUE TITLE
The game appears to need more player colors

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#3257]
The game supports 32-player team battles, but there aren't enough colors available. I think http://zero-k.info/Battles/Detail/618560 is an example of a battle that ran out of colors. At least one team contained two players who shared a color if I recall correctly.

**Comment by sprunk** [comment]
Adding any more nominally different colors won't help because some of the colours are already hard to dinstinguish, it's a limit of the human eye.

**Comment by Sgathec** [comment]
Would it be easy to use two colors to represent each player?

**Comment by sprunk** [comment]
no

**Comment by Sgathec** [comment]
How do you know?

**Comment by sprunk** [comment]
1) many instances of teamcoloured stuff (zoomed out units, for example) are already just a handful of pixels so you'd be getting a blend
2) dual colors only allow "more" colors by reusing the same colour across different pairs, so you'd inevitably get situations where people get confused due to AB and AC pair appearing next to each other
