### ISSUE TITLE
One of the ally colors is ambiguous

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#3258]
One of the teammate colors is too close to purple. That means it could be interpreted as an enemy team color. I seem unable to find it at the moment in https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Configs/TeamColorConfig.lua.

**Comment by sprunk** [comment]
Technically this "fix" just pushes the problem further back into larger games, but that is fine since at that point teamcolors are screwed anyway. If I made that color more blue, it would look too similar to an existing one and if I removed it, it would just mean the duplicate colors problem manifests earlier.
