### ISSUE TITLE
Check Gauss animations

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3295]
[03:39] _Shaman: in the current test version
[03:39] _Shaman: for some reason, guass fucks up big time and causes massive lag
[03:39] _Shaman: it keeps calling the unpack-pack animation
[03:40] _Shaman: like rapidly calling it

**Comment by ArchShaman** [comment]
See #3296

**Comment by ArchShaman** [comment]
This actually is in stable too.

**Comment by ArchShaman** [comment]
Can Confirm it wasn't @Anarchid 's guass turret fix that caused this. The bug has been present since April.

**Comment by GoogleFrog** [comment]
The model is a dae, so I assume @Anarchid made it. I haven't tried to open the file, but the bug looks like it is caused by a piece that both changes location and is returned by AimWeapon.

**Comment by Anarchid** [comment]
This should not be the case. The model has a separate, immobile piece for aiming.

**Comment by ArchShaman** [comment]
Another incident: http://zero-k.info/Battles/Detail/631031 (recreated for funz)

**Comment by GoogleFrog** [comment]
QueryWeapon could be it. Fire checks come from both the query and the aim piece.

**Comment by Anarchid** [comment]
My current primary suspicion is that the problem is that boolean shift between two QueryWeapon pieces presents a very sharp non-continuous angle change, which in turn causes it to oscillate between two states every frame.

A proper fix that retains the hax in cd56bfc would be an extra rotatable proxy aiming piece that aligns perfectly with `Muzzle` when unpacked, eliminating the discontinuity. I'll try this sometime weekendly-ish.

**Comment by Anarchid** [comment]
^ The above implements the "extra rotatable proxy piece that is aligned perfectly to unfolded `Muzzle`.
