### ISSUE TITLE
Consider improving victory conditions to prevent stalling / bm-ing

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#3297]
Allyteams without constructors should be forced to resign after a set period of time in order to prevent people from dragging games. (This could possibly be a match ending mode or something like that and turned off on FFA)

**Comment by Anarchid** [comment]
100% mex control

**Comment by ArchShaman** [comment]
I was thinking of creating a defeat condition (or rather victory condition) of either of the following to help cut down the frustrating "hunt down the last flea / kill the 9 razors left on the map" situations that pop up from time to time.

Options I came up with:
1.) allyteams with nothing but static defenses left are defeated (since they cannot project force into the enemy base).
* Helps in a niche condition.

2.) allyteams with no method of creating new units (eg: without constructors, comms, and factories) will lose after a period of time if they are unable to force the other allyteam into the same situation. If this situation occurs, both allyteams get radar coverage of the other's units (so that they're not hunting eachother down for 9 years).
* This would cut down on time wasted hunting the freeman, provide an incentive to throw all your remaining units at the enemy (as opposed to bming), and end the game faster.

3.) During overwhelming advantage, display a win button for the other team.
* This also would help cut down wasted time and prevent bad mannering / stalling.

**Comment by ArchShaman** [comment]
http://zero-k.info/Battles/Detail/631947 is an example of a game where I wasted multiple minutes building an air fac after the game was clearly over.

**Comment by GoogleFrog** [comment]
I can't think of anything un-janky which will solve the buried commander problem. Clearly a team must be able to live with just a commander.

**Comment by sprunk** [comment]
I think if somebody consistently hides fleas / buries crap to prolong the game to the point that people refuse to play with them that's a social issue that should get solved in social ways.

**Comment by FeXoR-o-Illuria** [comment]
"Adding a click to win button would respect player agency" is one sided and not at all true for the party that would lose if that button is clicked.

**Comment by sprunk** [comment]
Yes, that is the whole point of the proposal. Agency is already one-sided but the opposite way (if the loser wants to play hide and seek with fleas, the winner has no choice and is forced to play along).

I agree with Shaman that if somebody is to have this agency it should be the winner, and it would be preferable to strip the loser of this agency and give it to the winner. However, I don't agree with his specific implementation proposals because most of them don't actually solve the problem (I agree with GoogleFrog that it's hard to find a useful way to figure out who the definite winner is going to be before the game is actually over through regular game over mechanics). In particular, Overwhelming Advantage is clearly not sufficient to solve commander burial since you'd need 24K+ net worth to overwhelm a buried naked commander and this gets even worse with morphing.

**Comment by FeXoR-o-Illuria** [comment]
"[...] the winner has no choice and is forced to play along." @sprunk 
1.) He's not the winner because otherwise the game had ended
2.) AFAIK he chose to play a game, no one forced him. The victory/defeat conditions where likely known to him (hopefully, that's why those conditions IMO should be as simple and clear as possible) when he entered it.

A sane solution to the "buried commander" is to make terraforming cost depend on material moved, independent of the desired shape. The cost to lower or raise terrain is several times cheaper than e.g. restore terrain when comparing the amount of material moved, removed or added. I'd prefer fixing issues at their root.

The other root is likely impatient players, players that don't want to be put to the same rules as others (so actually don't want to play a fair game) or players that want different rules (so don't really want to play the game they entered) and thus go AFK, sabotage their team, focus on chatting rather than playing or (in the best of the bad cases) start a team resign vote long before e.g. observers would agree the game was clearly decided in that direction anyway (also maybe players that prefer to play longer on the winning than on the losing side - at least as they feel the balance is tipped. This is not something everyone can have so I'd consider that unfair, too).
I think this is much harder to manage since one can't just implement it. However, giving the players tools like "vote resign" is the wrong direction IMO. Rather give them a reason and motivation to try to play and win games like "whitelists".

The "vote resign" option already makes this game more a social and psychological game rather than a one with rules clear for everyone from the start. That's unfortunate IMO just in terms of victory/defeat conditions independent on the specific likings of players and specific situations on the end of the game.

**Comment by GoogleFrog** [comment]
I agree with FeXoR and am pretty strongly against the "click to win" button. Let me just copy what I said earlies.

> I'm pretty heavily against anything which is proposed as a forced resign. Instead, propose changes to the victory conditions of the game. This stops us from discussing this topic in terms of how ZK "actually" plays and what sort of win condition the forced resign should attempt to encode. Basically, I want to be able to say "that proposal is too janky to be the win condition".

In short: **Propose actual win conditions instead of piling complications on the UI (that effectively add up to defeat anyway)**.

I disagree with the non-symetric terraforming cost solution to buried commanders, as it is stated. Additionally, I am not even sure that such a thing doesn't already exist.

**Comment by Anarchid** [comment]
> **Propose actual win conditions instead of piling complications on the UI (that effectively add up to defeat anyway)**.

100% of mex spots captured by one team

**Comment by Licho1** [comment]
Special maps?  Also maybe both sides can have fun even then. For example in FFA you can lose all mexes but still be competetive .. lets say you have detriment and water con economy...
So no .. 100% mex is *NOT* applicable.

**Comment by sprunk** [comment]
That doesn't solve earlygame commander burial, capping the map takes more time than getting a handful of bombers.

**Comment by Anarchid** [comment]
> For example in FFA you can lose all mexes but still be competetive .. lets say you have detriment and water con economy...

As long as noone gains *all* the mexes you are safe. My proposal is not "eliminate teams with zero mexes", that would obviously kill everyone on start because noone starts with prebuilt mexes.

If your conch farm is giving you comeback-worthy income, you should be able to prevent the enemy from capturing the last mex.

> That doesn't solve earlygame commander burial, capping the map takes more time than getting a handful of bombers.

I don't think anything solves *that*. But this solves the lone cloaked commander hiding forever in FFA.

**Comment by sprunk** [comment]
I think the solution to FFA would be to enable Overwhelming Advantage there.

Currently the FFA OA logic is backwards. If anything, OA should kick in earlier there because the set of enemy units is not a unified front and they can fight against each other (to your benefit).

Consider a situation where allyteam X has 1 Flea; allyteam Y also has 1 Flea; meanwhile allyteam Z has forty Dets. It has 40 Dets. And that's not overwhelming because there are more than 2 allyteams left. Surely by consolidating the losers can only lessen the advantage (because they are better coordinated and are not shooting at each other) but if X gave its Flea to Y it would trigger OA for Z.

**Comment by Licho1** [comment]
I dislike any solutions and especially overwhelming advantage.
If losing players want to mess around with few units let them. If winning player has such an advnatage he will eliminate rest quickly anyway.

**Comment by GoogleFrog** [comment]
OA is effectively an economic win condition. I never really liked it and would rather it apply in as few situations as politically possible.

**Comment by sprunk** [comment]
Reopen if there is a concrete proposal that fulfils the various design constraints listed above.
