### ISSUE TITLE
Resign Weirdness

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#3303]
https://cdn.discordapp.com/attachments/278908415756206080/507176530154225674/unknown.png

Battle in question:
http://zero-k.info/Battles/Detail/634487

There's some weird double resigning taking place in this battle. May be related to #3308

**Comment by GoogleFrog** [comment]
Link, description, and locally hosted screenshots.

**Comment by GoogleFrog** [comment]
Is gameplay negatively impacted, or does it seem to be UI?

**Comment by ArchShaman** [comment]
Unable to tell with the current take issues. May be related. May just be ui weirdness

**Comment by sprunk** [comment]
`Giving all units of X to Y due to lag/AFK` can legitimately be triggered multiple times with different Y as long as X receives some units and a different person clicks the button the second time. Hard to tell whether this was such legit occurence without any more data.

As far as I can tell `X resigned, giving all units to Y` will currently be shown for all subsequent takes on that team (even if a different player is being taken), this is broken.

**Comment by ArchShaman** [comment]
I think this may be a consequence of #3308 but with the current system being generally borked it's hard to say. I'll keep an eye out for more occurrences if needed and may try replication when I have spare time.

**Comment by sprunk** [comment]
Closing as a subset of #3308
