### ISSUE TITLE
Investigate spontaneous pause and detonation

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#3409]
><Lord_Stronghold> i just played a matchmaking game 1v1 and my opponent paused the game
<Lord_Stronghold> a second after i exploded
<Lord_Stronghold> and lost
<Lord_Stronghold> could this be because my connection?

http://zero-k.info/Battles/Detail/682347

**Comment by sprunk** [comment]
The pause, the explosion and the belief in the faultiness of his connection is consistent with this https://github.com/ZeroK-RTS/Zero-K/commit/e5782fb70410e5316a7b377606229d4282733ea3

**Comment by sprunk** [comment]
I opened the replay txt and found `luarules inactivitywin` so that explains the explosion.

Lagmonitor messages say he was never more than 4s of ingame time away, which is somewhat weird but this does not include any connection losses or time elapsed during pause so watching the replay would be needed.

**Comment by Anarchid** [comment]
Crisis debunked.
