### ISSUE TITLE
New Hunter model fires directly downwards.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3417]
It should fire out of its gun.

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/52853802-c30cb980-3170-11e9-970e-b49f5c103f47.png)

**Comment by Anarchid** [comment]
The problem is that projectile has zero initial velocity. The projectile starts between the two guide rails, correctly, but instead of jumping forward, it falls straight down.

`StartVelocity` does not affect this behaviour. Unsure if engine bug. Possible to workaround with some lua shenanigans (like that old @xponen code that replaced Scalpel missiles with torps on crossing water).

**Comment by GoogleFrog** [comment]
I don't think you are correct. I set `startVelocity` and `weaponVelocity` to 6000 and observed a change in behaviour. I expect the issue to be `fixedLauncher` combined with misconfigured pieces.

**Comment by Anarchid** [comment]
There was something weird with the `torpedo` piece causing the direction to be somewhere weird and not as represented in the actual model.

Probably one of those OTAisms with deriving piece orientations from their vertices.
