### ISSUE TITLE
Check whether airLOS firing reveal works

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3498]
In a recent game I had an LLT be damaged by an enemy LLT without the enemy LLT being revealed. It should be the case that any enemy unit that fires from within your aLOS is revealed to your allyTeam.

**Comment by sprunk** [comment]
Chat complaint about HLT (haven't watched, from the text it might actually involve aimpoint / ground clipping)

>\<CatLady\> there is a bug with stinger dug that are able to shoot "through terrain", but are invisible to units
\<CatLady\> so can't be shoot back
\<CatLady\> http://zero-k.info/Battles/Detail/704408 here is example of unfinished stinger set at exactly the hbeight required for bug
\<CatLady\> on other match, same person used them finished, and they were shooting at full stinger range, yet were invisible to units until approached at the very point blank
\<CatLady\> the stinger is clearly underground and should be unable top shoot at all
\<CatLady\> I'll try to find the match in question
\<CatLady\> or not, cause i told them what i think about his bug using :)
\<CatLady\> probably will earn me a mute, lol
\<CatLady\> but anyway, the bug is real, testable, and the correct elmo of digging udnerground to trigger bug is present in the latest battle i linked, with the unfinished stinger
\<CatLady\> the guy in question is abusing the bug in all his matches, too
