### ISSUE TITLE
Look at Zephyr vs planes

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3500]
https://zero-k.info/Forum/Thread/28092

**Comment by sprunk** [comment]
Zephyr is trash against planes. This is because it has a non-homing projectile which planes often dodge through their normal movement patterns. Engine leading being unreliable (#1881) doesn't help. Zephyr also has 0.25° inaccuracy (compared to Razor's 0.1°). Having no alpha means that getting lucky won't result in meaningful damage. Plane hitvolumes seem fairly small so missing is easy.

Missiles (present on the other sea AA - Flail and Angler) have a random hax that makes them ignore radar wobble. Zephyr doesn't:
![image](https://user-images.githubusercontent.com/2573076/66119284-a9719280-e5d8-11e9-9850-aa6b799da0f0.png)

Here's some unit-specific situations. Likho has a forward-facing missile which reduces the time it spends flying forward and a relateively large turning circle which increases the time it spends turning. 
![image](https://user-images.githubusercontent.com/2573076/66118449-ad041a00-e5d6-11e9-9552-3a10396087e3.png)
![image](https://user-images.githubusercontent.com/2573076/66118461-b42b2800-e5d6-11e9-8dbd-abfb743297e5.png)
![image](https://user-images.githubusercontent.com/2573076/66118473-bab99f80-e5d6-11e9-9140-283173efb32e.png)
![image](https://user-images.githubusercontent.com/2573076/66118485-c0af8080-e5d6-11e9-93cb-5bcdbcd5cfc0.png)
![image](https://user-images.githubusercontent.com/2573076/66118495-c73df800-e5d6-11e9-92de-6da7e7db3088.png)

Normally, flying straight on approach gets Zephyr clean hits but with a bit of manual jinking you can dodge that too:
![image](https://user-images.githubusercontent.com/2573076/66119518-0ec58380-e5d9-11e9-94a1-e30a4f694db4.png)

Raven diving is a turning point that introduces misses.
![image](https://user-images.githubusercontent.com/2573076/66119180-76c79a00-e5d8-11e9-8783-e64aa1e099d4.png)

Swifts seem to usually move in arcs when chasing other planes (screenshot tbd).

**Comment by sprunk** [comment]
I am unsure whether this can be solved without any major change. The ideal would probably be to have some sort of ship flex AA that can handle planes but this involves touching other units. Alternatively Zephyr's weapontype could be changed but that loses uniqueness.

**Comment by Anarchid** [comment]
Could sufficiently increasing innate inaccuracy (perhaps with compensating DPS buff to maintain effective DPS) result in that compensating the inability to lead and shoot by radar?

**Comment by sprunk** [comment]
>compensating damage / ROF buff to maintain effective DPS

This would increase it massively vs gunships (who are large and close enough that the inaccuracy wouldn't matter). Zephyr is already quite brutal against GS so this might be too extreme.

My idea would be to check if beefing up projectile speed would help (so as to stick to numerical changes). I'd expect the change would be large enough to warrant changing visuals so as not to produce an inconsistency with Razor - possibly use the Toad chaingun or something new entirely.

**Comment by Anarchid** [comment]
Going hitscan would also help, but there are quite a lot of pulsing hitscan AA lasers. While i think they're mainly fine (aside from the sound), if Zephyr really wants to stay unique, it could also get
- Continuous AA laser (none exist ATM)
- Burst AA laser (like Stinger; again, none exist yet).

**Comment by Oflameo** [comment]
Is Corsair any good against planes? It has better range than most riots which can hit planes. Likho outrages Corsair, but it is 2000 Metal. You can build an Amphbot factory and 6 Anglers for that amount.

**Comment by alexpyattaev** [comment]
A recent battle with totally frustrating Zephyr performance: http://zero-k.info/Battles/Detail/947403
Setup 1: a bunch of ravens fly into 2 Zephyrs and 3 flails. Most of them die, some to zephyr but mostly to flails (despite flais being 100m cheaper each), and as you can see Zephyrs are clearly missing with most of their shots:
![screen00003](https://user-images.githubusercontent.com/5932526/91823076-5ddcc400-ec41-11ea-97bc-13d97381bc76.png)
![image](https://user-images.githubusercontent.com/5932526/91823225-8ebcf900-ec41-11ea-97f7-1b235644b875.png)

But OK, you might say, its not supposed to be THAT good. Fine. Now this Likho is truly brave, flying into 4 zephyrs, 3 flails and 2 anglers, 2800 metal in dedicated AA, of which 1600 is in Zephyr. Again, Zephyrs miss with most shots:
![image](https://user-images.githubusercontent.com/5932526/91823492-f5421700-ec41-11ea-8013-d0d3aef0bb0c.png)
As you may imagine, Likho snipes one of the Zephyrs and retreats with 1800 HP left. Seriously? 
Ok, I get myself another Zephyr and we're up for another bout. Now its gonna DIE, right?
![screen00005](https://user-images.githubusercontent.com/5932526/91823828-80231180-ec42-11ea-9c8b-da1afc48756b.png)
Wrong, Zephyrs all collectively took lessons from startrooper core though, and manage to not hit the Likho more than a couple of times, and likho retreats with another kill to repair.
![image](https://user-images.githubusercontent.com/5932526/91824005-beb8cc00-ec42-11ea-9748-8a4f18da0154.png)

Okay, okay, I have better eco, I get myself even more zephyr. A likho flies into 6 zephyr now!
![image](https://user-images.githubusercontent.com/5932526/91824522-941b4300-ec43-11ea-9ad8-d3228827ad85.png)
It gets one and retreats to heal, again, with minimal damage. 
![image](https://user-images.githubusercontent.com/5932526/91824610-b57c2f00-ec43-11ea-9a88-1684c1881250.png)
Don't get me wrong but 6x Zephyr should cut through Likho's HP in about 2 seconds flat even if they miss half the time. Instead, it makes a clean approach, snipes a Zephyr and retreats to heal, AGAIN, with 1200 HP to spare. We get some flails to the party and still:
![image](https://user-images.githubusercontent.com/5932526/91824856-1b68b680-ec44-11ea-8b91-f1ad35559eb8.png)

And again (this guy ended up leaving with just 180 HP, mostly thanks to 3 solid hits from flails)
![screen00010](https://user-images.githubusercontent.com/5932526/91825030-5ec32500-ec44-11ea-8997-dff4b82bcffb.png)
Also if you look at the ranks on the units, the story is clear. Most flails are veterans, making 4x cost. Most zephyrs barely made cost because they cant hit shit.

These envoys are dead, likho gets away of course:
![image](https://user-images.githubusercontent.com/5932526/91825951-a0080480-ec45-11ea-9ba3-19f6a2e60b0c.png)
And this Zephyr is dead also, likho gets away again:
![screen00013](https://user-images.githubusercontent.com/5932526/91826106-cd54b280-ec45-11ea-8bd3-8e8a4cd15e3a.png)
Essentially we ended up keeping about 3500 metal tied in AA and kept losing metal to Likho, while enemy lost only energy for repairs. 

Now, interesting twist, enemy employs screening with a single swift (no boost). You'd expect the swift to insta-melt vs 6 Zephyrs, right? Wrong:
![screen00014](https://user-images.githubusercontent.com/5932526/91826380-2b819580-ec46-11ea-984c-c02f42ba68eb.png)
Here flails fire at the swift (as one would expect them to), and likho makes it to target with near full HP... and gets sniped by a LANCE OF ALL THINGS. Takes it down LIKE A BOSS!!! Now that is AA I appreciate! That was our first Likho kill with naval AA in whole game btw.

At this point the Likho player figured out that there is nothing to fear anymore and just flies straight into AA:
![screen00017](https://user-images.githubusercontent.com/5932526/91827000-f75aa480-ec46-11ea-8659-e5860bddbb5f.png)
Interestingly, he focuses flails and not Zephyrs (as those clearly have more effective DPS and are much more scary =)

Bottom line, we ended up losing about 8K metal to likhos while having 1.5 Likho's worth in AA. I'm fairly certain something should be done.
Interestingly, 6 razors would have been a much better investment, as they cut likhos to pieces and cost much less. Also with a simple widget one could queue a winding path for bombers that makes them nearly immune to AA ships. Here is one example that allows Likho to escape with 1200 HP. From 6 razors and 5 AA ships!!!!  Thats 3.5 K in dedicated AA...
![screen00021](https://user-images.githubusercontent.com/5932526/91828765-37bb2200-ec49-11ea-83d3-18abd6a74ac5.png)

For comparison, 4 toads shred likho to pieces, even on a winding approach. 4 Ettins do the same, no problems. In addition Toads are effectively immune to likhos due to jump ability (assuming decent micro or jumpjet AI active). 2 K in just about any AA will tear likho to pieces, so why would razors and Zephyrs be made to suck so hard? I'd say easiest short-term fix would be to change AA ship to have flak weapon instead of lasers. It would also IMO look better.

**Comment by GoogleFrog** [comment]
Razor and Zephyr seem to shoot at the nose of aircraft.

**Comment by alexpyattaev** [comment]
Bottom line is it is not important what they aim for, as long as they hit. Why not just ramp up projectile speed a bit and see if that solves it? I'd say 20% boost would likely be enough.

**Comment by Arch-Shaman** [comment]
Aiming for center mass ensures some hits when jinking (since the error tolerance is much larger than if you shoot at the nose)

**Comment by Hoppili** [comment]
OMG, I swear I would rather have 1 Angler than 1 Zephyr!
Please make anything, but making Zephyr against Planes is just most useless trash!

**Comment by GoogleFrog** [comment]
I still think someone should look into Zephyr shooting at the nose of planes. Maybe there is an offset somewhere doing this.

**Comment by sprunk** [comment]
Keep #1881 in mind as a possible explanation (but try to disprove it because that one is hard to solve).

**Comment by sprunk** [comment]
Zephyr partially redesigned with a missile d23305a98bda62090b40135c4e40d8601d1d3a25
