### ISSUE TITLE
Badger shell does not successfully spawn a mine if it direct hits

### ISSUE THREAD

**Issue by darloth** [ZeroK-RTS/Zero-K#3517]
According to what people have said, and also basic logic and balance assumptions, badgers shells should do ~220 damage if they hit something directly.

They don't, they do less than 20 damage on a direct hit, and at least in some cases the mine is spawned and then removed without detonating.

http://zero-k.info/Battles/Detail/707806 at around 17 minutes in, a badger shell hits a wind generator at the bottom left of the top left plateau.  Nothing else much is happening to that wind generator, and it takes I believe 17hp of damage and continues on.  In the replay the mine is spawned but only for a tiny increment of time, then it disappears.

**Comment by GoogleFrog** [comment]
Badger should not deal 200+ damage if it direct hits. It should deal around 20 damage then spawn a mine on the ground below the hit location. The exception is that direct hits on shields should deal 200+ damage and not spawn a mine.

**Comment by darloth** [comment]
Fair enough, then the bug is that the mines vanish without exploding

**Comment by Anarchid** [comment]
I think the spawning on ground below rule is worth taking another look at.
- It *seems* prone to failure, either because of actual failure or because the mine being placed where the player does not know to look for
- It is aesthetically jarring (an effect-free teleportation)

Alternatives:
- Spawn projectiles directly, in radial spread, with impacted unit as their target
- Change the mine to be a non-building object, spawn it right on the impact site, let it fall.
