### ISSUE TITLE
Fix jittery Gauss turret once and for all

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3550]
Gauss jitters while unfurling because its weapon emit point moves around vertically. It cannot fire unless fully unfurled, so simply make its weapon emit point never move vertically.

**Comment by Anarchid** [comment]
It already always aims from the proxy which never moves: https://github.com/ZeroK-RTS/Zero-K/blob/master/scripts/turretgauss.lua#L188

The only thing that swaps pieces is QueryWeapon.

**Comment by GoogleFrog** [comment]
Units aim from QueryWeapon on occasion.

**Comment by Anarchid** [comment]
QueryWeapon also determines where the projectile is shot from, so this would require the proxy structure to have two pieces to perfectly match the offset and orientation of the gun as it turns while aiming and offsets the muzzle. This will require a (minor) model change to add these empty pieces.

**Comment by GoogleFrog** [comment]
Yes. Or one piece and a little maths.

**Comment by sprangg** [comment]
Gauss turret can still be made to jitter. Was used to ruin this game http://zero-k.info/Battles/Detail/750486

**Comment by GoogleFrog** [comment]
https://cdn.discordapp.com/attachments/278908415756206080/604241336350146560/unknown.png

AimProxy does not sit on the Cannon at all. I applying the Alexandrian solution because I discovered that Gauss does not even aim straight. Fit the crappiness of this solution later if you want.

**Comment by danfireman** [comment]
Metal head gauss is back :(

15:00 at north of circle: https://zero-k.info/Battles/Detail/756650

**Comment by GoogleFrog** [comment]
I don't think this bug is as dire as the previous versions. Solving it requires a way to reproduce it consistently.

**Comment by Anarchid** [comment]
I was testing lasercannon gauss for #2414 and got a low-frequency version of this. Since the shifting geometry is now completely ruled out, this must be some kind of logic error in the script. 

The few cases where it triggered were when i told the turret to aim in a way that required it to change both pitch and heading while playing the pack-down animation.

**Comment by SteelBlueZK** [comment]
I think I figured out the problem with metalhead gauss.

If Aimweapon is called within a frame or 2 of https://github.com/ZeroK-RTS/Zero-K/blob/master/scripts/turretgauss.lua#L96 this wheel rotation which gets called in Close after RestoreAfterDelay then the wheel rotation in AimWeapon https://github.com/ZeroK-RTS/Zero-K/blob/master/scripts/turretgauss.lua#L231 gets called initiating a Turn on the piece in the opposite direction, meaning the Close function never completes as the engine will continue calling AimWeapon every frame or 2 continuing to turn the piece away forever. I think(not an expert here) that there is some kind of leak in the Aimweapon thread as this line https://github.com/ZeroK-RTS/Zero-K/blob/master/scripts/turretgauss.lua#L237 would mean none of these threads ever end as they wait for Wheel to stop turning(the close function turn never ends).

That means I hate this commit https://github.com/ZeroK-RTS/Zero-K/commit/e32ea20670fbad0c1063f3c55d61b55d91948bd7#diff-9f1506ed58c53303a16aafc2d0a0c719c18bb19d368f25f064fd75d47d90ce7a to radically fix metalhead gauss. A better fix would be to add a Signal(close) to the beginning of script.AimWeapon so the turn in the close thread ceases to exist.

Lesson is to be very careful with your signal mask and not have an open, close, and aim signal which all just control the same pieces. Piece groups should get their own signals and functions should clear all masks and set their signal mask to all piece groups that the functions move.

**Comment by Anarchid** [comment]
> the Close function never completes

That would be because a `while(true)` ensures that without any need for Turn conflicts. I guess your reading of the code also expects execution to never reach that `while(true)`; but we know that the execution reaches that part of the code because that is the part that also enacts Gauss autoheal, and autoheal does occur in the game.

**Comment by SteelBlueZK** [comment]
gauss still jitters on open. Gauss only jitters while it's opening if it's aiming, it does not jitter if aiming has been canceled during the opening animation. This is because every time it aims it's weapon, it starts a new thread Open() which moves it's wheel to 2 different positions, the first one conflicting with a position in the aim script. https://github.com/ZeroK-RTS/Zero-K/blob/master/scripts/turretgauss.lua#L57

Hopefully I finish my script overhaul soon. I'm just documenting these odd cases of scripts messing up.
