### ISSUE TITLE
Terraform should show "grid" texture on terrain during the initial delay

### ISSUE THREAD

**Issue by Cat-Lady** [ZeroK-RTS/Zero-K#3615]
Looking through the code, I noticed that - indeed - there is an added delay before terra starts, that was meant to give a chance to escape. Hoever, in the midst of battle, and often nanoframnes flying both way, it is hard to notice, so you still see it only when ground starts to fall down and grid texture appears
SO, could the "grid texture" appear on the terrain being about to change, at start - aka, before the delay?
Grid terraform terrain marker would appear, and then - after (even now existing) delay - the terrain would start to actually change. Noticing the terraform grid terrain "marker" would be much easier, so counterplay could be done (evasion, or counter terra-order)
Acceptable? Feasible?

**Comment by GoogleFrog** [comment]
This is a little tricky because currently the terraform texture is drawn using the following system:
- Send a message to every terrain square that was just changed by terraform.
- Every terrain square that receives the message sets a texture based on slope, or removes its texture if its height is close enough to the original height of the map.

This system handles restoration (via any terraform command) seamlessly.

If we simply forced texture upon the first bit of BP received by a new terraform then this texture would be reverted as soon as the next update was sent, since the square would be close to origHeight. A state machine per-square may be required with the following commands.
- Force apply texture.
- Update texture, but only remove if the height-origHeight threshold has been breached since the texture was forced.

**Comment by Anarchid** [comment]
Blocks of terraform that receive active BP could just draw a glowing wireframe grid over affected terrain. This would also distinguish between areas that are being currently pumped with BP and idle terraform that just sits there.

**Comment by GoogleFrog** [comment]
I prefer the idea of a glowing wireframe for actively built terraform. It solves the problem that could occur when you start a terraform (applying the texture, under my previous comment) but fail to follow it up with anything that causes the terrain to change.

Now the only task is to figure out how to make such a thing occur. It probably involves terrain shaders for which there is no precedent.

**Comment by lhog** [comment]
Perhaps someone can sketch how it should look like, then I can see if something can be done easily

**Comment by Anarchid** [comment]
I don't think a ground shader is necessary because a GroundQuad with a grid texture should be sufficient (at least for low-quality potatos).

Here's a mock-up. Some description of what i think should be going on here:
- Nanos are trying to bury Detriment. That audacity!
- The wireframe on the ground is deformed with the ground (as a GroundQuad would be), but the ground is flat, so the wireframe is flat.
- The wireframe uniformly covers the bits of the ground affected by the terraform-piece that is currently being pumped with BP. 
- The wireframe is teamcolored.
- The wireframe is faded out towards the ends.
- The wireframe is pulsing and glowing; the intensity of its glow is proportional to the amount of buildpower being pumped.

![image](https://user-images.githubusercontent.com/3822768/59928196-df827080-9446-11e9-8b7c-02ff5ea11e58.png)

**Comment by Anarchid** [comment]
Here's another style. This one should be good in case you want to run a game of life within the shader. Or just do some random digital flickering of the "pixels".

This too should just be doable with a bunch of GroundQuads.

![image](https://user-images.githubusercontent.com/3822768/59928715-09886280-9448-11e9-9145-9b053dc4836d.png)

**Comment by GoogleFrog** [comment]
I think the grid is a bit better than the solid boxes. Seems like a good approach to me.

**Comment by GoogleFrog** [comment]
Also, I would much rather a fixed less pixely outline shader than a terraform grid shader.

**Comment by Cat-Lady** [comment]
awesome, especially the "glowing intensifies proportional to buildpower pumped" thing, and teamcoloured aspects.

As for priorities - well, as a player, I would much rather like to see the terra shader fixing gameplay problem, than the non-pixely outlines.

**Comment by GoogleFrog** [comment]
Solved at some point by making the terraform texture draw shortly after the terraform starts.
