### ISSUE TITLE
Increase Ripper turret turn speed.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3787]

**Comment by sprunk** [comment]
By 60% (same as the recent chassis turnrate buff)?

**Comment by GoogleFrog** [comment]
That sounds high but ok. If it looks silly go lower. I mainly want the ability to increase Ripper turret turn speed.

**Comment by sprunk** [comment]
I had a few minutes to investigate and I think this ticket is effectively "make Ripper LUS". I assume you primarily want the ability to easily touch the value because Ripper has aiming issues lately, but:
 * nominal turret turnrate is already higher than chassis turnrate, even after the testing mult, so the aiming failures are caused by something else than not being able to keep up
 * Ripper has `reaim_rate = 8` in its weapondef due to COB. Possibly going lower could help, though in my limited tests it still struggled a lot with this line removed
 * COB wait-for-turn seems to have a bit of a different logic than the LUS version (possibly applies 1 frame later or something) so realistically the Ripper aiming issue is most likely only going away with LUS anyway.
