### ISSUE TITLE
Fire-once should make missile silos fire one missile

### ISSUE THREAD

**Issue by danfireman** [ZeroK-RTS/Zero-K#3923]
It's currently rather difficult to hit several different targets in succession with tac missiles because you need to select each individual missile and target it.

Instead, it should be possible to select the missile silo and rapidly use fire-once to make it fire just one of its missiles at each target.

It would also be very useful to be able to use fire-once with a bunch of selected missiles.

**Comment by sprunk** [comment]
what if you have 2 different tacnuke types (quake + eos, say)? does one shoot at random?
what if you have a tacnuke and an impaler? who shoots?

**Comment by danfireman** [comment]
I was thinking they fire in build order, oldest to youngest.

Both tacnuke and impaler shoot.

**Comment by sprunk** [comment]
Looks like Missile Silo currently already does this to an extent:
 * regular Attack sends one missile.
 * with CTRL modifier it works like Repeat usually does, still sending one missile but putting the order at the back of the queue. This is because the regular Repeat state is for building more missiles.

Here are some traits I think would be desirable for the behaviour:
 1) I think missile silo Attack order should behave closer to a Manual Fire order (i.e. be fire-once by default, even without modifiers) because missiles are expensive and limited.
 2) I think missile silo having some form of Repeat on a modifier is good, because it's unique in lacking it for orders due to also being a factory.
 3) I think CTRL would ideally be fire-once always.

Just shuffling fire-once vs fire-multiple around can't satisfy all three:
 * if CTRL is fire-once and regular is fire-multiple, that breaks 1.
 * if CTRL is fire-once and regular is fire-once, that breaks 2.
 * if CTRL is fire-multiple, that breaks 3. This is the current system.

I think if making a system from scratch, 3 would probably also be the one I would care the least about breaking because newbs don't know modifiers while pros know the exceptions to the modifiers. Meanwhile newbs benefit from not spending all their missiles bukkake-style from careless attack orders and pros probably enjoy the increased control that a ghetto repeat gives them. Since this is the status quo I think I'm not going to touch Missile Silo.

This still potentially leaves the "have 2 missiles selected, CTRL to fire just one" improvement. Maybe GoogleFrog could say something at this point because I suck at UI design.

**Comment by GoogleFrog** [comment]
I forgot about CTRL acting like repeat. I recall making it act like a normal attack command. I must have decided that two attack-ground commands are redundant so it may as well have repeat-like behaviour. The default being fire-once is definitely intentional. I think there are some other units like this too, where fire-once is a good default which can be toggled off with CTRL, much like how fire-once is toggled on for everything else.

**Comment by sprunk** [comment]
I found some more issues around doing the "select 2 missiles, only 1 fires":
 * what if you hold both CTRL and ALT (such that each missile gets a separate target)?
 * whom to fire if you have two missiles but on two silos (so there isn't any clear precedence)?
 * what if the missile with precedence is not in range, but the other one is (since the Attack command is still given when out of range)?

These may have fairly obvious answers but they show that things would need to work quite differently from how they usually do so I'm somewhat reluctant to implement this. Given that missile silo itself already works as requested I'll consider the ticket done.
