### ISSUE TITLE
There should be a (F)ollow command

### ISSUE THREAD

**Issue by danfireman** [ZeroK-RTS/Zero-K#3927]
(G)uard is nice and all, but very often you just want one unit to follow another, not chase after and attack every unit that damaged the latter.

Most common with Bandits which you might want to just move in front of your Thug without leaving the shieldball, no matter how tempting it is.

Inspired by this thread: https://zero-k.info/Forum/Thread/31409?postID=221695

**Comment by Anarchid** [comment]
Circle guard.

**Comment by dahn-zk** [comment]
Circle Guard is a great command, but it has a few shortcomings. One of which is the circle shape itself. Because what's the most optimal in a real battlefield scenario is "hiding", "fire front". Units dancing around another units are rarely useful except for screening purposes.

- **Hiding units**. Should always stay behind, meaning on the side with least number of enemies around, otherwise in the opposite direction of moving of the main unit. Like battlefield constructors. Your hardworking buddies that need to repair and reclaim asap without being stupidly exposed to enemy fire.
- **Fire front**. Opposite of Hidding.
  Excellent example by @danfireman above, when you want your high alpha units to stay within shield radius under such command. Also this touches dirtbox wall scenario.

**Comment by sprunk** [comment]
Circle guard, with the Alt modifier. See https://www.youtube.com/watch?v=i_Nl5bRJNyc
