### ISSUE TITLE
Hercules can still pick up unit when disarmed

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Zero-K#3949]
http://zero-k.info/Battles/Detail/901986?

about 3-4 mins in firepluk comm nap

**Comment by the-tranquility** [comment]
I watched the replay. Hercules was only disarmed (by Thunderbird) and not EMPed. EMPed airships and planes fall to the ground, while disarming only disables weapons (game does not treat picking up a unit as using a weapon).

**Comment by GoogleFrog** [comment]
It is possible to make disarm make transports unable to pickup units. I think it should be done.

**Comment by Arch-Shaman** [comment]
> I think it should be done.

I have another idea that can go along with that: dying transports eject cargo on death instead of awkwardly remaining attached while they slowly spiral to the ground and die far away or even nonsensically teleport sometimes. Both of these changes are 5 minute fixes that I can perform as side projects while tackling my bigger projects I have going on right now.
