### ISSUE TITLE
Feature; caretakers stop reclaiming wrecks when metal storage is full

### ISSUE THREAD

**Issue by thomas11111111** [ZeroK-RTS/Zero-K#3965]
In order to avoid excess reclaiming caretakers will turn to assisting near builds when metal storage is full.
Manual reclaim order shouldnt be affected

**Comment by GoogleFrog** [comment]
You only mean 'reclaiming' in some cases. Work is required to map out exactly which ones.

**Comment by sprunk** [comment]
Subtask of #1335

**Comment by Arch-Shaman** [comment]
Would it be acceptable to scale up to all cons and add a "allow reclaim when full metal" command to disable the behavior?

**Comment by GoogleFrog** [comment]
What sort of command? State toggles are just clutter.

How about constructors only reclaim when full if they have a manually issued reclaim command on the target feature?

**Comment by Licho1** [comment]
Its not that hard imo. All you need is idle handler for caretaker. Instead of using engine patrol.
Then on idle code can decide what to do and if it issues its own command, keep monitoring it. 
That way if player gives specific command, it will listen. Otherwise it can follow simple logic:

1) if not m/e stalling, assist construction
2) if not m storage full, reclaim 
3) if not energy stalling, repair nearest unit (ally unit too)

**Comment by sprunk** [comment]
This now exists in Smart Nanos, and there's a ticket with more specific feedback #4226
