### ISSUE TITLE
Area mex command: add area-split modifier

### ISSUE THREAD

**Issue by Lasica** [ZeroK-RTS/Zero-K#3974]
When selected group of builders, make each builder start with different mex in area as a starting point.

Possibly calculate time to reach all mexes by constructors selected and select farther mex to faster cons minimalizing total travel/mexing time by all constructors.

**Comment by GoogleFrog** [comment]
I think the current area mex default is near-perfect because it consistently follows a very simple rule (greedy TSP). If I select two or three constructors then area mex an area I want them to move as a group for safety. If I want more nuanced behaviour then I'll use a few more clicks to define it.

A split mode could be added as a modifier. Look up the Force Fire and Set Target split attack mode and see if it can be made consistent with those.

**Comment by Licho1** [comment]
Yeah this stuff sounds like central build AI. Widget that takes your queues as "global" and auto assignes and manages cons to do the buildings

**Comment by Lasica** [comment]
If implementing as an modifier would be acceptable, on the widget level then I'll see what can I do

**Comment by sprunk** [comment]
I think using CTRL and replicating what the attack command does would be fine.

**Comment by sprunk** [comment]
I think this would be elegantly solved by #4438. Do a line move before the command to have each con handle different mexes. Do a point move to gather up cons if they should move in a blob for safety. This way modifiers don't need to be involved (especially since CTRL has since been taken for adding solars).
