### ISSUE TITLE
zenith visual beam is hide-able, thus NOT revealing position

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#3987]
the visual beam into the sky of zenith is not visible if you park something in its path, e.g. charon

http://zero-k.info/Battles/Detail/916987

this is a strategic advantage, hiding the position when you know this. is this intended? else fix or give the skybeam damage? -.-

**Comment by GoogleFrog** [comment]
Make it such that if any skybeam explosions occur, the Zenith does not work. This implements a Zenith which requires a free shot on the sky to work.

**Comment by Arch-Shaman** [comment]
This should be a 5 minute fix. I have an idea I'll test real quick

**Comment by Arch-Shaman** [comment]
Fixed in PR #3990 by removing all collision (except ground, which honestly when will a zenith ever end up underground?) from the beam. (3989 had bad white spacing). This is a very simple fix to the problem rather than implementing some additional logic.

Bonus points: now the beam is purely cosmetic instead of dealing 0.001 damage.
![screen00014](https://user-images.githubusercontent.com/48730089/86869929-4b546d00-c08c-11ea-88f9-0b3d390b77e2.png)

**Comment by Arch-Shaman** [comment]
I've done both solutions here: skyline check and a nocollide change. If the skyline solution is chosen, I suggest adding a newton "pull" effect to the beam itself.
