### ISSUE TITLE
The GameRulesParams set by the startbox gadget seems to leak hidden information

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4097]
The positions or even existence of teams on start positions is hidden information when shuffle is enabled. The GameRulesParams set by the startbox gadget seemed to be leaking this information when I had a look at it recently. Regardless, if it didn't leak before then it does now because I added information and did not see a system in place to prevent leaks, so did not prevent leaks in the system I added.

**Comment by sprunk** [comment]
Which specific params? Some leaks are by design:
 * all box shapes are known, even if nobody occupies them.
 * "shuffle" (as opposed to "allshuffle") always takes the first N boxes (for example on a 4-way map with 3 allyteams, "shuffle" always distributes people across boxes 0, 1, and 2 while leaving box 3 empty)
 * "allshuffle" exposes the fact that the other team got shuffled into the other box when there are just 2 teams and 2 boxes.

Does "positions" refer to eg. `"startpos_x_0_1"` game rules param? This is not a player-picked startpos, but the position of the 1st recommended startpoint in box ID 0. Those are usually constant regardless of who occupies them, and the recommended startpoints are usually constant inside a box. For example:
 * box ID 0 is always west on DSD, but not saying whether that's occupied by allyteam 0 or by allyteam 1
 * startpos 1 of box 0 is always the "techer" spot, regardless of where the first player of the allyteam occupying that box, if any, is placed, if at all
![image](https://user-images.githubusercontent.com/2573076/92458179-5aa78200-f1c5-11ea-9653-79c500c6d061.png)

The startpoints are partially to guide noobs (drawn as circles on the choosing UI), partially to tell CAI where to spawn, and the 1st spot is where the people who didn't choose a startpos will spawn (the "middle" may be out of the box when they are disjoint, or in some crappy place like a cliff, so a mapper is expected to define at least one startpos manually).

**Comment by GoogleFrog** [comment]
Is Spring.SetTeamRulesParam private by default?

**Comment by sprunk** [comment]
Yes. It would probably be good to make the private explicit.
