### ISSUE TITLE
Stingers Morph to Lance and vice versa

### ISSUE THREAD

**Issue by Sharkgamedev** [ZeroK-RTS/Zero-K#4167]
Consider having Stingers morph into lances and vice versa makes sense to me because of how similar they are, both using a high damage energy weapon. 

This would be useful for taking over new land, where you can roll in a few of your lances and, faster than building new stingers, morph them into stingers to protect your mexes, or when you've expanded and have a large number of stingers sitting idle you can morph those into lances to aid with the frontlines.

I'd like to know what peoples thoughts on this are.

**Comment by Arch-Shaman** [comment]
I'm probably going to have to say that while this is cool idea, it belongs in a mod. I think it would lead to degenerate outcomes over time.

**Comment by sprunk** [comment]
Morphing a turret into a mobile, without rebalancing it to take that ability into account, ruins the whole point of turrets (they pay for the increased power with immobility). You can't just slap a morph onto HLT, you'd have to rebalance it around that new ability.

Morphing specifically to Lance is also bad because it heavily affects balance (Lance is really good, it lives in an otherwise fairly crappy fac for a reason - letting every fac get it via HLT morph would be a comparatively large upheaval), disincentivizes switching to Hover (since it's usually just for the Lance), and has bad aesthetics: the models don't look consistent and the "same weapon" argument would rather point to Grizzly (or Lucifer, from the Lance side).

"Useful for taking land" is looking at things from a player PoV. Why should people get to just bunnyhop the same HLTs forward? Let them make the interesting decision between using turrets to consolidate their existing mexes but tying up the metal in the backlines or using mobile units to cover new mexes but leaving the old ones vulnerable. You can't eat your cake and have it, too.

The way to recycle old HLTs already exists - you can reclaim them. The tradeoff here is that this costs buildpower and you only get back 50% of the metal, so is not a no-brainer.

**Comment by Sharkgamedev** [comment]
> Morphing a turret into a mobile, without rebalancing it to take that ability into account, ruins the whole point of turrets (they pay for the increased power with immobility). You can't just slap a morph onto HLT, you'd have to rebalance it around that new ability.
> 
> Morphing specifically to Lance is also bad because it heavily affects balance (Lance is really good, it lives in an otherwise fairly crappy fac for a reason - letting every fac get it via HLT morph would be a comparatively large upheaval), disincentivizes switching to Hover (since it's usually just for the Lance), and has bad aesthetics: the models don't look consistent and the "same weapon" argument would rather point to Grizzly (or Lucifer, from the Lance side).
> 
> "Useful for taking land" is looking at things from a player PoV. Why should people get to just bunnyhop the same HLTs forward? Let them make the interesting decision between using turrets to consolidate their existing mexes but tying up the metal in the backlines or using mobile units to cover new mexes but leaving the old ones vulnerable. You can't eat your cake and have it, too.
> 
> The way to recycle old HLTs already exists - you can reclaim them. The tradeoff here is that this costs buildpower and you only get back 50% of the metal, so is not a no-brainer.
You make some really good points here, I don't really have anything else to say.
