### ISSUE TITLE
Can't set ² key as shortcut (AZERTY Keyboard)

### ISSUE THREAD

**Issue by matheod** [ZeroK-RTS/Zero-K#4217]
I have an azerty keyboard. I tried to set a shortcut to the ² key but the game show me unknow (and the shortcut doesn't work) : 

![image](https://user-images.githubusercontent.com/339611/101283100-d15e1680-37d8-11eb-8527-4caa470a0917.png)

![image](https://user-images.githubusercontent.com/339611/101283157-0f5b3a80-37d9-11eb-97ec-783d3b927618.png)

**Comment by Arch-Shaman** [comment]
So, I'd like to do some tests here if you don't mind helping out.

**Comment by Sharkgamedev** [comment]
> So, I'd like to do some tests here if you don't mind helping out. I lack access to a french keyboard like the above. Basically all I'll do is have you run some code real quick to see if it's even registered by the engine.

I can help as well if you need, I still have a french keyboard installed from a while ago when I took a french class.

**Comment by matheod** [comment]
> So, I'd like to do some tests here if you don't mind helping out. I lack access to a french keyboard like the above. Basically all I'll do is have you run some code real quick to see if it's even registered by the engine.

Sure just tell me what to do :)

**Comment by Arch-Shaman** [comment]
```lua
function widget:GetInfo() return {
	name    = "Test",
	desc    = "Test keys",
	author  = "Shaman",
	date    = "Dec 2020",
	license = "PD",
	layer   = -1,
	enabled = true,
} end

function widget:KeyPress(key)
   Spring.Echo("Key: " .. key)
end
```

save this as a widget ("test.lua" under 'LuaUI/widgets') and give it a run. Paste results here.

**Comment by matheod** [comment]
It return 0

**Comment by GoogleFrog** [comment]
> save this as a widget ("test.lua" under 'LuaUI/widgets') and give it a run. Paste results here.

I am unconvinced that the results from this widget is all there is to say on the matter since keybinds are not handled by `widget:KeyPress`. I think there is a reasonable chance that you can at least set ² as a hotkey by editing a config file. For example, the default zk_keys.lua contains the string "Any+0xa7", which was presumably tested by whoever added it.

I wouldn't even give up on some sort of fix that lets this key be set using the ingame UI, since the full signature of `widget:KeyPress` is `widget:KeyPress(key, mods, isRepeat, label, unicode)`.

**Comment by matheod** [comment]
The ² key return the `0x0b2` label

**Comment by matheod** [comment]
I confirm that manually setting to 0x0B2 work.

I will see if I can't make the UI work with strange key.
