### ISSUE TITLE
Smart Nanos stuck on reclaim for a while when excessing metal.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4226]
![image](https://user-images.githubusercontent.com/1318249/101852441-bfea8500-3bb1-11eb-9220-4f14e6fc777d.png)

In this battle: http://zero-k.info/Battles/Detail/1006569

**Comment by rtwfroody** [comment]
I've sometimes seen this, but generally when I look at the excess graph later it turns out I didn't excess metal. There might be a real bug here, but it seems like the top center widget does something that means it doesn't quite reflect what's going on in the moment.

**Comment by thomas11111111** [comment]
Long game but it's shows smart nanos is a ''hermetic'' environment.
The interesting part is after i queued a fortress and went afk, upon returning metal storage was full and caretakers looked stuck, they were connecting with factories but no metal was flowing. 
https://zero-k.info/Battles/Detail/1008206

**Comment by GoogleFrog** [comment]
Were you testing in a teamgame? It is hard to actually excess in team games.

**Comment by rtwfroody** [comment]
Some things I noticed while watching the first 2/3rds or so of this replay:

1. In this video, the metal widget in the top shows income of 30-something, and pull of -130, yet the metal inventory is going up. That doesn't make sense to me. http://casualhacker.net/zero-k-caretaker/economy-2020-12-14_18.50.02.mp4
2. At some point the factory, which was on low priority, just stopped building. http://casualhacker.net/zero-k-caretaker/factory-2020-12-14_18.51.21.mp4
3. Then it built, but slowly. http://casualhacker.net/zero-k-caretaker/building-again-2020-12-14_18.53.35.mp4
4. Later it stopped building again. http://casualhacker.net/zero-k-caretaker/not-building-2020-12-14_19.51.01.mp4

I think the building might have stopped because Thomas was repeatedly building phantoms, and eventually they sucked up so much energy that the factory and caretakers (which were on low priority) didn't have any to build.

**Comment by GoogleFrog** [comment]
1. Energy stall. Energy is pulling 120 more than income and is at the reserve point.
2. Construction costs energy and there was less energy than the reserve point, so all construction that isn't high priority halts.
3. Same as 1.
4. Same as 3.

**Comment by rtwfroody** [comment]
:bulb:! I had always assumed those numbers were what was happening, not what would happen if only there was enough of everything. This explains one problem with smart nanos 2, because in Thomas' video the caretakers would be told to reclaim. (They think net metal income is -90 or so, so they can reclaim.)

The widget uses getTeamResources() to find the state, and currently only looks at current level, storage, pull, and income. The function returns:
```
			lua_pushnumber(L, team->res.metal);
			lua_pushnumber(L, team->resStorage.metal);
			lua_pushnumber(L, team->resPrevPull.metal);
			lua_pushnumber(L, team->resPrevIncome.metal);
			lua_pushnumber(L, team->resPrevExpense.metal);
			lua_pushnumber(L, team->resShare.metal);
			lua_pushnumber(L, team->resPrevSent.metal);
			lua_pushnumber(L, team->resPrevReceived.metal);
			lua_pushnumber(L, team->resPrevExcess.metal);
```

Is there a definition of exactly what each one of those numbers mean? It sounds like I want to look at income and expense, ignoring pull altogether.

It does not explain the screenshot that started this PR.

**Comment by rtwfroody** [comment]
> In this battle: http://zero-k.info/Battles/Detail/1006569

I spent some time looking at this replay. The caretakers are definitely reclaiming when they shouldn't be. I just worked through DecideCommands() using those values, and I believe the logic is correct. Another possibility is that something with adding/checking the priority queue went wrong, and I'm not sure how to look into that.

How do you feel about setting `debug = true` on line 86? Then when something goes wrong somebody can capture the log and send it to me so I can dig through it in more detail.

**Comment by rtwfroody** [comment]
I think I've seen the same problem GF reported
battle: https://zero-k.info/Battles/Detail/1024484
log: [1024484.txt](https://github.com/ZeroK-RTS/Zero-K/files/5778793/1024484.txt)

The caretaker in question had unitID 2510. Here is the relevant bit of the log:
```
[f=0022991] [uapn] 2510; give order 40(952, 196.194031, 3256, 50000, nil) 0 (build assist)
[f=0022991] [uapn] 2510; queue order 40(952, 196.194031, 3256, 50000, nil) 4 (repair units)
[f=0022997] [uapn] 2510; UnitIdle(2510 (iW=2, cF=23118, rI=22991))
[f=0022997] [uapn] 2510; push for 22998
[f=0022998] [uapn] 2510; push for 23128
[f=0022998] [uapn] 2510; give order 40(952, 196.194031, 3256, 50000, nil) 0 (build assist)
[f=0022998] [uapn] 2510; queue order 40(952, 196.194031, 3256, 50000, nil) 4 (repair units)
[f=0023004] [uapn] 2510; UnitIdle(2510 (iW=2, cF=23128, rI=22999))
[f=0023004] [uapn] 2510; push for 23004
[f=0023005] [uapn] 2510; push for 23129
[f=0023005] [uapn] 2510; was commanded -587(3144, 195.761719, 2856, 2, nil) 32
[f=0023005] [uapn] 2510; Ignore until it becomes idle.
[f=0030172] [uapn] 2510; UnitIdle(2510 (iW=1, cF=30292, rI=0))
[f=0030172] [uapn] 2510; push for 30172
[f=0030173] [uapn] 2510; push for 30299
[f=0030173] [uapn] 2510; give order 40(952, 196.174774, 3256, 50000, nil) 0 (build assist)
[f=0030173] [uapn] 2510; queue order 40(952, 196.174774, 3256, 50000, nil) 4 (repair units)
[f=0030173] [uapn] 2510; queue order 90(952, 196.174774, 3256, 50000, nil) 0 (reclaim metal)
```

And here are my observations from watching the replay:
```
[f=22080] 12m16s, start assisting building a stardust
[f=22380] 12m26s, stardust is completed
[f=22410] 12m27s, start assisting building a radar    
[f=22470] 12m29s, radar is completed
[f=22530] 12m31s, reclaim a tiny bit
[f=23010] 12m47s, reclaim a tiny bit
[f=23640] 13m8s, the caretaker does not assist building a shield like it should.
```

At frame 0023004 (12m47s), the engine told us the unit became idle. In response we pushed it onto the priority queue. The result is that in the next frame the widget looked at this caretaker, and it discovers it was issued a command: -587. This correspond to "build a stardust." In reality a stardust had been built in that area, starting at 12m16s and stopping at 12m26s. The caretaker assisted as expected. What happened in-game at 12m47s was that the caretaker reclaimed just a tiny bit of metal.

I have no idea why this build command ended up in the caretaker's queue, especially given that the stardust had already been completed, and the caretaker even helped build a radar afterwards. The widget assumes this must be a command issued by the user, so stops paying attention to the caretaker. Later, I notice it's not doing anything when it should, and I tell it to repair some units which seems to have snapped it back to normal.

I spent a bit of time reading the spring code (which I'm not familiar with) and couldn't find where such a command might be pushed onto the queue.

How could this command end up on the queue, if it wasn't issued by a player? The command's ID was -587, and the parameters were 3144, 195.761719, 2856, 2. The SHIFT option was set (and no others were).

It would be easy to change the widget so it interprets build commands as a possibility if build assist was issued, but I'd like to understand things a bit better, if possible.

**Comment by GoogleFrog** [comment]
Any command can be issued to any unit. Widgets usually need to be able to ignore these commands safely. If this is too hard then it may be possible to track down the source, but this would leave the widget open to being broken by new widgets or player widgets. Perhaps the Caretaker was selected while someone used the Skydust UI.

**Comment by rtwfroody** [comment]
The widget detects a command it doesn't recognize. It assumes this must be a command issued by the user, so it stops managing the caretaker. In this case I was the user, and I did not issue any commands to this caretaker. So this felt like a bug because the caretaker was just sitting there doing nothing. As far as I can tell this build command came completely out of nowhere. Where could it have come from?

The reason the widget looks for unknown commands is that it doesn't want to override a user command, and a user command can come from a different client so checking whether this client issued a command doesn't solve the problem.

> this would leave the widget open to being broken by new widgets or player widgets.

That's what we want though, right? If the player does something, either manually issuing a caretaker command or running a special widget that does so, then *this* widget should get out of the way until the caretaker becomes idle again (which did not happen in this case).

> Perhaps the Caretaker was selected while someone used the Skydust UI.

I have never used the Skydust UI.

**Comment by rtwfroody** [comment]
I've added some more debugging locally for this issue.

https://zero-k.info/Battles/Detail/1073857 had a failure like the one reported.

Relevant parts of the log:
```
# The widget issues build assist, repair units, and reclaim metal orders, using GiveOrderToUnit().
[f=0017341] [uapn] 11487; give order 40(808, 26.1159515, 2776, 50000, nil) 0 (build assist)
[f=0017341] [uapn] 11487; queue order 40(808, 26.1159515, 2776, 50000, nil) 4 (repair units)
[f=0017341] [uapn] 11487; queue order 90(808, 26.1159515, 2776, 50000, nil) 0 (reclaim metal)

# We get callbacks when these commands are issued, and simply print them out. No action is taken.

# This one is for repair units (cmdOpt = META)
[f=0017342] [uapn] UnitCommand 11487: 40 (808, 26.1159515, 2776, 50000, nil) 4

[f=0017342] [uapn] 11487; UnitIdle(11487 (iW=2, cF=17466, rI=17341))

# This one is for reclaim metal. (cmdOpt = SHIFT)
[f=0017342] [uapn] UnitCommand 11487: 90 (808, 26.1159515, 2776, 50000, nil) 32

# This one is for reclaim energy. (cmdOpt = SHIFT | CTRL) How did this get in here?
[f=0017342] [uapn] UnitCommand 11487: 90 (808, 26.1159515, 2776, 50000, nil) 96

# This one is for build assist (cmdOpt = SHIFT)
[f=0017342] [uapn] UnitCommand 11487: 40 (808, 26.1159515, 2776, 50000, nil) 32

# The widget discovers a command it did not issue, so starts ignoring the unit.
[f=0017343] [uapn] 11487; was commanded 90(53972, 808, 26.1159515, 2776, 50000) 104
[f=0017343] [uapn] 11487; Ignore until it becomes idle (commanded).
```

Question for @GoogleFrog:
My assumption is that if I issue (through widget or manually) an area reclaim command with no options, only metal will be reclaimed and not energy. Is that always true?

**Comment by GoogleFrog** [comment]
I don't know off the top of my head. I would just do the same test as you, which is to open up a game and try.

**Comment by rtwfroody** [comment]
Experiment results:
1. Area reclaim without any modifiers reclaims both energy and metal.
2. Area reclaim with control only reclaims metal.

Looking in the spring code (CBuilderAI), control gets mapped to special, and if special is set there's some extra logic limiting what gets reclaimed.

I've change the widget with this new understanding of how things work. I'll see if the problem happens again. It was quite rare to start with, so it will take some time.

**Comment by sprunk** [comment]
>Experiment results:
Area reclaim without any modifiers reclaims both energy and metal.
Area reclaim with control only reclaims metal.

Did you check keyboard modifiers or actually passing OPT_CTRL? There's a widget which reverses how the "ctrl" keyboard key gets interpreted into OPT_CTRL by default: https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/unit_tree_reclaim.lua#L53-L59

**Comment by rtwfroody** [comment]
@sprunk, thanks for the insight. That would explain some funky behavior I saw but ignored.
