### ISSUE TITLE
Commander builds too many drones

### ISSUE THREAD

**Issue by pengvado** [ZeroK-RTS/Zero-K#4271]
Steps to reproduce:
* Have a commander with at least 3 companion drone modules and at least 3 battle drone modules. (Including the free ones, if it's Guardian chassis.)
* Have 0 current drones. e.g. because they all just died in combat, or because you just started a campaign mission, or because you turned off the "drone construction" toggle while upgrading the commander.
* (Re-)build all of your drones at natural speed, i.e. don't spend metal to hurry it up.
* Result: you have more drones than you're entitled to. If it's 3 of each drone-module, then you have 4 of each drone; if it's 8 of each drone-module, then you have 12 of each drone.

**Comment by Arch-Shaman** [comment]
Do you have a replay of this occurring?

**Comment by pengvado** [comment]
https://zero-k.info/Battles/Detail/1035950
At 14:24, Anarchid's commander finishes building 7 battle drones and 5 companion drones; it should have been limited to 3 and 3.

https://zero-k.info/Battles/Detail/1035075
At 11:22, Anarchid's commander finishes building 4 battle drones and 4 companion drones; it should have been limited to 3 and 3.

https://zero-k.info/Battles/Detail/986408
Anarchid's commander never stops building drones all match long, and by the end he has 10 battle drones and 13 companion drones; it should have been limited to 4 and 5.

**Comment by Anarchid** [comment]
IIRC the issue is assumed to be that the commander retains drones that were created before the upgrade, but doesn't count them towards the limit, and builds them again. 

The game with 10 battle drones should not be possible under this assumption though. The commander in B986408 seems to be above the limit suggested by this hypothesis, as it is level 4 with 3 equipped battle drone modules and one innate one, with all battle drones gained on the same final level.
