### ISSUE TITLE
Convict, Thug and Felon shouldn't be produced with full shield charge

### ISSUE THREAD

**Issue by IndeIrae** [ZeroK-RTS/Zero-K#4309]
Shieldbots get special treatment and break consistency when it comes to spawning with full shields. In Felons case especially getting out with full weapon charge throws a wrench in any early-mid/late game air/land raid or drop into shields base. Rushing into Felon after failing at raider game or getting an awkward timing coinciding with an enemy raid should be punished, instead of giving shields a freebie.

**Comment by GoogleFrog** [comment]
I'm not so sure. Starting them at full shield was an intentional choice. Other units are in top form when they leave the factory. This looks like a discussion.

**Comment by IndeIrae** [comment]
I don't see how there is any reasoning to Thug or Convict having full shield charge when leaving the factory. I can sort of understand wanting Felon out with at least some heat behind the guns, you do want your battle unit to do stuff. Again, my argument for changing this in Felon isn't that there shouldn't be *any* shield charge from the get-go, just not a *full* charge. I guess i'll throw around some example games in the forum post or whatever.

**Comment by Licho1** [comment]
It would incur additional shield charging cost which is probably fair. Would be significant nerf for funnel too.
I would either go 100% or 0% shield though not some random arbitrary value in between.

**Comment by IndeIrae** [comment]
Funnel already spawns with 0% shield charge, which is part of my point here.

**Comment by Anarchid** [comment]
> I'm not so sure. Starting them at full shield was an intentional choice. Other units are in top form when they leave the factory. This looks like a discussion.

Stockpile units don't; arguably, Felon shield is an energy-powered stockpile of sorts.

**Comment by Sharkgamedev** [comment]
> > I'm not so sure. Starting them at full shield was an intentional choice. Other units are in top form when they leave the factory. This looks like a discussion.
> 
> 
> 
> Stockpile units don't; arguably, Felon weapon is an energy-powered stockpile of sorts.

Stockpile units a lot of the time require metal to regenerate whereas energy doesn't. I'm not making an argument for either side just saying that's not a detail that should be overlooked.

**Comment by IndeIrae** [comment]
There is also one more resource in use here, and it is _time_. Artemis can only produce a rocket every 20 seconds. How much does an unsupported Felon need to recharge it shield to full? _~90 secs_. It's a long time, hell even half of this is. Yet it is cut away, gone.

**Comment by Aquanim** [comment]
Which other main factory units (i.e. not expensive statics and not striders) leave the factory at less than peak performance?

**Comment by sprunk** [comment]
>getting out with full weapon charge throws a wrench in any early-mid/late game air/land raid or drop
>getting an awkward timing coinciding with an enemy raid should be punished, instead of giving shields a freebie

If a naked Felon can beat stuff so hard, solo, then it sounds like a problem with its raw power and not the starting shield. Consider that catching a lone Felon out in the open should still be good for the catching side even if it's not fresh out of the fac, but touching starting shield does not affect this.

**Comment by Licho1** [comment]
I think that felon is too universal. It's gun can deal with swarms and also deal high DPS to big targets. It also has decent range. 
Personally I think it should be much worse against swarms. There are other units in that lab to deal with swarms.

**Comment by IndeIrae** [comment]
> If a naked Felon can beat stuff so hard, solo, then it sounds like a problem with its raw power and not the starting shield. Consider that catching a lone Felon out in the open should still be good for the catching side even if it's not fresh out of the fac, but touching starting shield does not affect this.

It affects the tempo at which it becomes unbearable. If a Felon is out in the field i prolly know it, the thing costs like a factory switch after all and one can *feel* the metal missing from the game, see a slow radar dot, whatever. I see it being there, I can react before engaging. I can't react to my timing randomly being collided with one being produced. No other unit in its price range can't crush a raid incursion nearly as badly by just exiting the factory.

Besides, nobody can even push for a Thug nerf, what hope is there to try to get Felon itself dunked even a bit. I see at least some merit in trying to route for something more tame.

**Comment by Anarchid** [comment]
> If a naked Felon can beat stuff so hard, solo, then it sounds like a problem with its raw power and not the starting shield. Consider that catching a lone Felon out in the open should still be good for the catching side even if it's not fresh out of the fac, but touching starting shield does not affect this.

Afaict there's a slight meta difference between the way this was done before and the way it is done now: most cases people used to build thug, then add Felon, which significantly delayed the impact. Nowadays it seems the opposite is done: first Felon arrives and stomps the lesser units, then Thugs arrive to replenish its ammunition.

This does sound like something likely to be upended by the proposed change - if Felon does not start with full shields, it makes sense to first build something to charge it up so that it can enter combat faster. I am unsure whether this achieves any significant change down the line though, as this is a flat one-time cost; e.g. the Shield player could just have a bunch of Convicts sit outside their factory, ready to charge the emerging Felon as it leaves the pad.

---

What would be a redesign of Felon look like? As far as i understand it, its current parameters are locked by design thus:

- It needs an instahit perfectly accurate weapon because otherwise it can waste its lifeblood-expensive ammo on missing, which is jank.

- It needs a rapid fire weapon because otherwise it would overkill, and thus waste shield-health to kill a lower amount of enemy health. In this approach, the more fine-grained it is, the less overkill, the less jank.

-  It needs to be flex-AA because the above two points make it a flex-AA and somehow prohibiting it from being such without changing something to make it obvious would just be anti-ZK.

The first two points have a set of counterpoints in expensive weapons that can miss such as Skuttle, which costs about as much as Felon, doesn't instahit, doesn't lead, and doesn't home on its targets, and can often be shot midair. Additionally, the addition of anti-bait would make a lower-ROF Felon much less janky as well.

The latter point could be addressed either by tackling one of the previous ones, or by doing something like the umbrella proposal where its shield is attached to a physical fixture, and the gun is also attached to that fixture, pointing down. That would require some model work but also sounds very cool.

**Comment by sprunk** [comment]
>What would be a redesign of Felon look like?

Less range? I think back when Felon was designed it was meant to be just a generic shields-to-damage converter for thuglaw balls and it happened to get a high range because Rocko was oppressive at the time or something.

> It needs a rapid fire weapon because otherwise it would overkill, and thus waste shield-health to kill a lower amount of enemy health. In this approach, the more fine-grained it is, the less overkill, the less jank.

Overkill sounds fine since you'd still rather spend shields killing a unit than spend shields getting shot by a unit you aren't killing. In theory current Felon already has a lot of overkill vs some basic raiders: 109 damage makes it fairly sad vs Glaive (230, two shots leave it at 12hp), or Bandit (330, three shots leave it at 3hp). More overkill sounds like it mostly affects raiders catching a naked Felon since everything else get comparatively less waste and nobody attacks shieldballs with raiders because of Outlaw.

**Comment by GoogleFrog** [comment]
Sounds like Felon was designed to kill raiders. Raiders used to have a bit less health.

**Comment by Licho1** [comment]
What's the outlaw for .. In my mind outlaw + bandit kills raiders. No need for anything else.

Felon could be high alpha "sniper-like" unit that delivers massive damage to limited number of targets. 

There are ways to avoid overkill, for example there could be "cooldown" - after killing unit/disengaging, weapon would shut down for 0.5-1s before being able to pick another target.

**Comment by IndeIrae** [comment]
Well, in current meta there's just no use for Outlaw, it is literally that bad. You're never not better off making more Bandit, making a Snitch or just going straight into Felon.

**Comment by Licho1** [comment]
Having useless unit in game sounds like the worst balancing transgression to me

**Comment by GoogleFrog** [comment]
I'm pretty sure Outlaw is useful.

**Comment by IndeIrae** [comment]
Doesn't seem to be the general consensus. The only thing it maybe has left is cloak-bomb "defusion", and even then in a non-timed situation I think everyone opts for more raiders/Dirtbags or Thugs (in case of Imp).

**Comment by Anarchid** [comment]
> Which other main factory units (i.e. not expensive statics and not striders) leave the factory at less than peak performance and need time on the order of minutes to function properly?

Aspis.

**Comment by sprunk** [comment]
Aspis is not an example of a mechanic different to Convict, Thug and Felon though.

**Comment by Anarchid** [comment]
I feel like the specific set of things that are valid counterexamples is kind of constricting if it also requires "units that have different mechanics", especially if we're talking in the context of consistency.

Stardust is not an expensive static or a strider, though it's neither a main factory unit either. With the recent change, it starts at 50% of its combat power. 

All cloaked units start decloaked and need a very small amount of time and a constant supply of energy to start being cloaked.

Commanders are neither striders nor expensive statics (and aren't factory units), but the ones that get drones, start without the drones fully stocked.

**Comment by GoogleFrog** [comment]
Aspis is a big shield. That is the important axis.

Stardust isn't to be held up as a precedent for inconsistency.

**Comment by sprunk** [comment]
Resolved the other way by af9dd1925df0ddab5d3f5a47fdfb2abbbd7079e1
Convict/Thug/Felon starting shield charge 66% → 100%

**Comment by GoogleFrog** [comment]
> Convict/Thug/Felon starting shield charge 66% → 100%

I don't think this change did anything btw. As far as I recall the weapondef is overridden by a shield gadget.
