### ISSUE TITLE
Archer vs torpedoes

### ISSUE THREAD

**Issue by IndeIrae** [ZeroK-RTS/Zero-K#4378]
When surfacing for an attack, Archer does a little jump, which raises its colvol above water, making most incoming torpedoes (namely from Hunter) miss. Doesn't seem intended judging by how effective and free it is.

**Comment by Arch-Shaman** [comment]
This information may be misleading. All amph floats impulse to the surface (afaik) which bounces them above the water briefly which makes torpedoes miss.

**Comment by sprunk** [comment]
Dunno about Archer vs modern light Hunter, but I'm fairly sure Buoy vs old 400m Hunter was consciously balanced with the "jump" dodging torps in mind (it meant Hunter couldn't just shoot a torp and retreat repeatedly to abuse the sink/float cycle).

I don't know how bad the Archer matchup is but floating amphs should probably beat Hunter because it beats the others (and is still useful against floaters by forcing them to surface).

The physics are cool so I think it would be ideal if this was resolved via stats changes instead where possible if it's a problem.

**Comment by IndeIrae** [comment]
In a real game it seemed nearly impossible for Ships to time multiple Hunters assault on a single Archer without just getting blungeoned on the head with sonic cutters, repeatedly, or killing tempo. Archer already eats the thing for lunch, so you can't stay in range, but you can't really go back and forth either since even on a simple attack move it won't submerge completely, raising in time in time and get free immunity again. 

Is this a submerge state meta I smell? Already need it to get Scallop into any useful condition in water.

**Comment by GoogleFrog** [comment]
Archer has short range so it has to rise pretty quickly if it is to counter hit-and-run torpedo ships. Each unit can have its own gravity and velocity loss that occurs when it crosses the surface of the water, but the physics starts to look off when units diverge too much on these values. Archer should be beating all short ranged torpedo units, and I don't worry about Urchin, so it seems fine to me.

The dodge bounce was intentional for Buoy. I forget about Archer, but it probably is given its history.
