### ISSUE TITLE
Investigate Lava High Ground PF failure?

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K#4406]
http://zero-k.info/Forum/Post/239534#239534

Replay in question:
http://zero-k.info/Battles/Detail/1121671

**Comment by pengvado** [comment]
This map uses a custom terrain-type for the under-lava ground, which sets all movement speeds to zero. Terraform doesn't change that property, so you can't walk across terraformed bridges either.

The custom terrain is mostly unnecessary, since Spring engine already has a provision to stop units from pathing into lava. But only mostly; that provision doesn't apply to hovers, even though hovers are just as vulnerable to lava damage.

**Comment by sprunk** [comment]
I can confirm that hovers still path into lava, and i managed to dip bot toes into the lava as well, which sounds like enough of a reason to keep the unpathability. The real solution is probably to make terraform reset terrain to x1 speeds (see #4415) which isn't a Lava Highground specific issue. Also, the map actually has code to reduce hover lava damage to 0 but it uses obsolete `moveDef.family` checks (removed in the engine, see spring/spring@c06a3057ad57d01a350b707aeb99b8c02cdaeae4), this is probably something to keep in mind if a newer version appears.
