### ISSUE TITLE
Use ctrl-F1 to group units

### ISSUE THREAD

**Issue by Gyslain** [ZeroK-RTS/Zero-K#4451]
I would like to use F1, F2, etc... to group units. I have to look at my keyboard when I use 7,8,9,0.

**Comment by SteelBlueZK** [comment]
in game, Hotkeys/Selection/Control Groups you can re-bind the keys used for control groups. In this case you would rebind controlgroups 7-0 to F1-F4 respectively. you might want to change the default binds for those buttons.

Hotkeys/Misc
F1: toggle height map.
F2: toggle pathing map.
F4: toggle economy overlay.
F3: zoom to last message.

**Comment by GoogleFrog** [comment]
I'm not 100% sure this works so feedback would be appreciated.

**Comment by SteelBlueZK** [comment]
Feedback: I tested this yesterday. I bound control group 1 to F1, I could assign Commander to Ctrl group 1 with Ctrl F1. I could not select ctrl group 1 with F1 while F1 was bound to toggle height map. I unbound toggle height map and F1 selected Commander.

Issue: non default Ctrl groups do not reflect the keyboard button that selects them. Binding control group 1 to F1 causes control group commands to respond to F1 instead of 1, but the UI next to units of control group 1 displays a 1 instead of F1. I have a feeling that binding binding non-default Ctrl groups is then bound to be confusing to the player.

**Comment by Gyslain** [comment]
Thank you @SteelBlueZK for your tests. It works as expected. I have used autohotkey for years to get around this problem! I had no idea this problem was just a hotkey conflict.
