### ISSUE TITLE
Glint can fall off starlight bug

### ISSUE THREAD

**Issue by SteelBlueZK** [ZeroK-RTS/Zero-K#4462]
https://youtu.be/KL4znlvj0t8

http://zero-k.info/Battles/Detail/1163439

At 58:24 a quake missile is  launched at a fully active starlight. At 58:31 it impacts high terrain adjacent to the starlight, having a slight effect at the base of the starlight. Glint seems to become detached from the place it should be, falling straight down into the starlight. Many different things seem to go wrong, as Hoppli reclaims and re-constructs the starlight base, attempts to newton the glint, turn it off and back on again etc.

**Comment by Anarchid** [comment]
Quake applies a small random impulse to all units in its aoe [cylinder](https://github.com/ZeroK-RTS/Zero-K/blob/68ea5ff61c9e9f15aaf582c8405daa4a9e70412a/LuaRules/Gadgets/unit_terraform.lua#L3542) in order to cause them to detach them from ground and cause them to fall by gravity rather than snap to ground.

Possible mitigations for this particular bug:
- unit_terraform could check if the units are on ground before applying impulse.
- unit_terraform could detach units in sphere rather than in cylinder
- unit_terraform could ignore units that have glint's customparams or urp's 
- Starlight could aggressively movectrl the Glint to its required position every frame.

**Comment by Anarchid** [comment]
Likely actual issue: DetatchFromGround unconditionally sets MoveCtrl off: https://github.com/ZeroK-RTS/Zero-K/blob/192f50d77035830717fa61eabb52220a1b396c5d/LuaRules/Gadgets/weapon_impulse.lua#L132
