### ISSUE TITLE
Autorepair module does not scale with health multiplier entirely

### ISSUE THREAD

**Issue by Hawkybird** [ZeroK-RTS/Zero-K#4495]
While the health the autorepair module removes scales with the health multiplier, the amount of health healed by the module does not. This can lead to a module that removes 1,000,000 health to give +10/s.

Seems like both should be affected to me?

I'm not sure how things like detriment autoheal are affected, apparently by the damage multiplier instead?

**Comment by GoogleFrog** [comment]
I don't see a problem with changing the health scale to scale all autorepair as well. It would just be a bit of work then minor ongoing maintenance.

**Comment by sprunk** [comment]
I think autorepair scales with damage because in a way it is negative damage and they work against each other. The time-to-kill formula is `HP / (DPS - HPS)`.

Why is there both a damage and a health multiplier in the first place though? The difference between setting health to X and setting damage to 1/X is likely already minuscule and should probably not exist at all.
