### ISSUE TITLE
Selfd-resigner is overzelaous

### ISSUE THREAD

**Issue by IndeIrae** [ZeroK-RTS/Zero-K#4531]
When you put a certain percentage of your stuff into self-destruction mode in a team game - you get yeeted out. No idea on specific values, but in this example: had 2 Skuttles and a factory->tried to selfd the factory->got resigned. That's less than even 50% of my value at the time, so, feels bad.
https://zero-k.info/Battles/Detail/1207595 8th min

**Comment by sprunk** [comment]
Skuttles are kamikazes so they don't count. You tried to selfd 100% of your non-exempt units.

I am unsure what to do that wouldn't introduce other edge cases:
 * if kamikazes count, then you would instead resign when trying to selfd the kamikazes. This fairly important in cheezes like Dirtbag spam or Blastwing openings.
 * if they count to the total but not to the "units trying to self-d", then your case is not distinguishable from Ctrl+AD, which goes against the reason the gadget exists.
 * making the rule require 100% of units is vulnerable to network lags, human input delay etc (a handful of units can be created between you selecting everything and the command being registered on the server).

Maybe one of the following?
 * single-unit selfd never resigns. But sometimes you do have just one unit so this would let a Ctrl+AD through.
 * do both a check with and without kamikazes counting and only resign if both would be passed. Ctrl+AD will pass both but weird shenanigans like this case will not (in this case 1/1 passes but 1/3 doesn't, and conversely when using the skuttles 2/3 would pass but 0/1 wouldn't). Sounds complicated and opaquq, though maybe it is fine because people don't really need to know the specifics?

**Comment by CarabusX** [comment]
If we go toward:
> single-unit selfd never resigns.
I would add that it still resigns if your only unit is Commander, to prevent self-d right at game start.

**Comment by sprunk** [comment]
I think I would like to stick to "ctrl+AD is resign" as much as possible to make the behaviour predictable and an exception for the commander doesn't help the general case of "have just 1 unit that is not necessarily the commander".

**Comment by GoogleFrog** [comment]
Ah, I either flipped the words or was thinking about it being 1 - threshold rather than a threshold. Swap what I said. Skuttle should count towards the total number of units that the player has, but not towards the number that are being self-ded.
