### ISSUE TITLE
Units get white

### ISSUE THREAD

**Issue by Hoppili** [ZeroK-RTS/Zero-K#4606]
https://zero-k.info/Forum/Thread/34784

A few units get a kind of white skin since the new engine.
I have the feeling that it is map dependency.

Example games:
https://zero-k.info/Battles/Detail/1286537
https://zero-k.info/Battles/Detail/1286364

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/afe515fdbe831c458b56c9d819892fa021ecfcb0 and potentially https://github.com/beyond-all-reason/spring/commit/ba59341a4c7e04622199bd5cc5f47ea523306a85

There were two bugs masquerading as the same because they are reported as similar if no screenshots are provided.
