### ISSUE TITLE
GL4 outlines have bad bounding boxes.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4654]
![image](https://user-images.githubusercontent.com/1318249/159103965-850dc37c-80a0-46e8-a93a-6d661d6ba204.png)

Outlines are drawn on a billboard-style area. The size of the billboard is set by `scale`, which is currently set by footprint size. This is a bit too large for many units, and too small for a few. Some sort of better detection or configuration for this is required.

Set high outline thickness for testing.

**Comment by GoogleFrog** [comment]
Perhaps the second pass should draw over the whole screen rather than as boxes around each unit, so fixing the current sizes may be redundant work.

**Comment by Beherith** [comment]
Ive investigated second pass draws, and because stencil test is run after fragment shader, one has to weight the following:
A. fixed cost of whole-screen 'blur' pass + no per-unit scaling of outline width
B. dynamic cost of overdrawing overlapping quads around units 

Option B sounds better except for extreme edge cases.
