### ISSUE TITLE
[crash] Game expects internet connection to start

### ISSUE THREAD

**Issue by CitrusWire** [ZeroK-RTS/Zero-K#4690]
(You really shouldn't summarily close issues! Especially not when the user can't re-open them. I appreciate you probably get a lot of rubbish bug reports, but it's disincentivising for those of us who take the time to report a legit bug)

This issue:
https://github.com/ZeroK-RTS/Zero-K/issues/4689

Also happens when downloading the itch.io version (portable - 2.31GB download!) that I was told to use instead.

But this time the error is:
![image](https://user-images.githubusercontent.com/72134064/167474980-0015378f-9909-4775-bf25-4f72d1ab5048.png)

It shouldn't happen for either of them given I have all the files for the first version too.

Also, weirdly, the Itch.io version is much larger than the downloaded-from-your-site version. Surely they should be about the same size?

**Comment by GoogleFrog** [comment]
I think the game should start without internet, but Licho doesn't, and he writes the launcher.

**Comment by CitrusWire** [comment]
Licho's perspective makes no sense. Lets look at the pros and cons of requiring an internet connection:

Pros:
* You can spy on your users

That's it. I can legitimately think of no other advantage to either you or the users.
It's a free game so it's not to stop people pirating it.
@Licho1 mentioned in the other ticket "Game cannot start without critical files." but given they're already included (and they should only be needed the first time if using the downloader-installer, where it is reasonable to expect an internet connection), that can't be a reason to *always require* it.

Cons:
* Requires user to have internet connection
* User cannot play if their internet is broken
* User cannot play if they're traveling
* User loses privacy (you're spying on their play-start times, and who knows what else)
* User cannot play if they're behind a restrictive firewall
* User cannot play if their country is blocking wherever your servers are.
* Game has a form of DRM
* Is not in line with how the vast vast majority non-DRM'd games
* Fails the "Power to the People" part of the zero-k ethos
* Objectively cannot be the "best open source multi-platform strategy game available" if the player can't even start it.

This isn't an MMO.

**Comment by Lukas321321** [comment]
I agree that it would be nice if the game worked offline as it once did, but I'm not sure accusing the devs of breaking the spirit of ZK and creating spyware is the way to go here.

**Comment by sprunk** [comment]
Internet access may be an assumption nested somewhere deep in the implementation, from before ZK even had meaningful SP content. I wouldn't close the ticket but I also wouldn't count on it being done anytime soon due to pretty bad cost/benefit ratio.

**Comment by CitrusWire** [comment]
hunt sab

-----

> but I'm not sure accusing the devs of breaking the spirit of ZK and creating spyware is the way to go here.

That wasn't what I did. I simply highlighted all of the reasons a game dev might want to require internet access for a game that has a large single-player component, which was the implication of what Licho's stance was. I genuinely couldn't (and still can't) think of any reason to take this position apart from to make it impossible for a user to play the game without being spied on.

And it seems I was correct and that is plausibly the reason. Or at least, the game clearly does have a `GameAnalytics` module, and "Analystics"[sic] is listed on the script that causes the failure:

https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/34382be6e1a36e06adb169d5d223bba7d93bd556/ChobbyLauncher/ChobbylaForm.cs

`Thread.Sleep(500); // This allows Analystics to finish.`


> Internet access may be an assumption nested somewhere deep in the implementation, from before ZK even had meaningful SP content. I wouldn't close the ticket but I also wouldn't count on it being done anytime soon due to pretty bad cost/benefit ratio.

As far as I can tell, the "buggy" code isn't even in this project, it's in the infrastructure ChlobbyLauncher per my link above. And while my C# is basically back to non-existent, I don't see anything there that suggests it'd be difficult to fix.

**Comment by GoogleFrog** [comment]
>  I genuinely couldn't (and still can't) think of any reason to take this position apart from to make it impossible for a user to play the game without being spied on.

I'm sorry, but this is on you, not us, and from your tone I doubt you would recognise a good reason for things being the way they are even if it was explained to you. Are you going to implement offline mode yourself? If not then this ticket is going nowhere, and besides, it's in the wrong repository.

You assume that the existing game is the result of infinite work implementing consistent goals. This couldn't be further from the truth, for any project really. Things are the way they are because they are the way they are, and changing them would take work. The cost of extending the portable install thingy to store a consistent set of versions of things (lobby, game, AI, maps etc) to use if it finds itself offline, rather than check the internet for which versions it should have each time it starts, is apparently high. The benefit is apparently low, since the whole self-validating system only exists for non-steam in the first place since steam has a resource validator and updater that is robust enough to handle offline mode automatically.

Remember nobody is being paid for anything. If Licho doesn't want to take on the thankless task of reimplementing a feature that steam already supplies to the majority of ZK players, then you can't make him. If you care so much about this, then perhaps you've got to do it yourself.

The right ticket in the right place already exists: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2647

You can get a poor mans portable offline mode by launching with the flag 'dev'. Note that you at least need the zk chobby repository for this to run. http://zero-k.info/mediawiki/Zero-K:Developing#Modifying_the_game
