### ISSUE TITLE
Annoying keyboad shortcut behaviour

### ISSUE THREAD

**Issue by Lukas321321** [ZeroK-RTS/Zero-K#4691]
When a build command is issued using building tab shortcuts such as x, c, v, b and then a build command is issued using a specific building is issued _without releasing the key for the building tab shortcut first_, the corresponding command from the orders tab is issued if left mouse isn't clicked fast enough. If no corresponding command in the orders tab exists, the nanoframe is simply started and then immediately abandoned, such as issuing a lotus build through c + q rather than c followed by q.

**Comment by GoogleFrog** [comment]
It is unclear what you are doing. Eg what is issuing a command to you? State precisely how to reproduce the issue.

**Comment by GoogleFrog** [comment]
I cannot reproduce any issue caused by holding down the building tab key. Here are two processes.

Process 1:
- Tap X
- Press F
- Hold for a few seconds

Process 2:
- Press X
- Press F
- Hold for a few seconds

The result of both processes is a Fusion blueprint appears on the mouse, and then changes to Force Fire about half a second later.

I expect this behaviour and it seems consistent to me. It is due to key repeat. Pressing and holding F to select Fusion sends another instance of F half a second later, which selects Force Fire. It is consistent with how we handle key repeat, and that if you pressed F with Fusion selected the active command would become Force Fire. To change this behaviour we'd have to think through the implications of breaking consistency in this case, which isn't as simple as fixing a broken behaviour. My guess is that isn't a path we should go down, that instead we should continue to expect people to tap rather than hold hotkeys. Also, Q is meant to make nanoframes rather than full constructions, so the case of Q is really intended rather than an unfortunate collision.

**Comment by Lukas321321** [comment]
I see. It would appear I was mistaken.

I have observed processes 1 and 2 and they behave as described. The reason I thought it might have been a bug is because the behaviour in process 2 is different if the second key is Q or S. I was not aware the former was a feature.
