### ISSUE TITLE
Mysterious sudden performance drop in a game

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4723]
Worth investigating: https://zero-k.info/Battles/Detail/1397499

I didn't get much from command checker. This improvement to it still syncs. https://github.com/ZeroK-RTS/Zero-K/commit/141c76ccc74e0e56a70eaa64457839db9c530b37

Extra battle: http://zero-k.info/Battles/Detail/1400014

**Comment by Beherith** [comment]
Did someone queue up a huge grid of buildings?

**Comment by Porkch0p** [comment]
One oddity in the replay is the Commands FX widget hits a high allocation rate shortly before complaints about lag begin. Placing some basic logging to count active commands in DrawWorldPreUnit shows a large amount of map_erase commands issued in close proximity around the time of the spike.

![map_erase](https://user-images.githubusercontent.com/49832728/177226738-ef4b772a-e31a-42be-a8e7-519532e9f27f.png)

**Comment by Porkch0p** [comment]
Did some digging. 

The map_erases are from a large arrow on the left scrubbed away by the eraser tool. Removed between ~13:30 and 13:43. It's been mostly removed by the time this screenshot above was taken, with a few small purple bits remaining below the debug log. Two players on the same side lag out at once. 

The third affected player in the replay is MightyOak, who lags later, and is on the other team. Comments about lag at 22:00, shortly after they draw a line spanning half of the map. The line is drawn over enemy forces, which seems just enough of an edge case that it might be important to note.

**Comment by Porkch0p** [comment]
The main performance issue from this widget looks to be its tracking of three seconds of fade-out on the eraser tool. It seems to be just the overhead caused by tracking that many individual marks, and not OpenGL-related.

Going by the widget profiler, reducing the length of the fade-out effect shows linear improvements in the worst case performance. 

So, I'll do a minimal PR with a ~4x faster fade-out. That will hopefully cause fewer problems.

**Comment by sprunk** [comment]
Assuming solved by 504708fd1bbf155947a88d865d32b986c4027fe9 (#4732)
