### ISSUE TITLE
Apparently transports teleport units when they die

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4784]
https://zero-k.info/Battles/Detail/1501517

**Comment by Kingstad** [comment]
oh there's already a ticket. video clip: https://youtu.be/fLUypnra098
There things happen, especially with large cargo and especially if its nearby some lower terrain. this causes detris or palas to spawn in lavapits and can really turn games. I should think its because these units are underground by the time hercules hits the ground and actually lets go of them so either: have herc drop them the instant its health reaches 0 (so when crash sequence starts), have herc somehow know the unit its carryings length so it finishes crashing when its legs touch the ground, or maybe fiddle with the whatever logic that dictates where units should spawn nearby when they've somehow gotten underground (engine thing?).
