### ISSUE TITLE
Engine pathing issue?

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#4818]
Moving nanoframe, apparently http://zero-k.info/Battles/Detail/1549613

**Comment by Mach565** [comment]
What appears to have happened was that around the 12-minute mark, West's merlin tired to path between the airplane plant and the edge of the map, but couldn't quite fit. So what happened is it got pushed outside the boundary and starting travelling at a constant speed away from the map. When it got pushed outside, a nearby caretaker reclaimed it a little, so that's why it's a nanoframe and not a completed unit.

**Comment by sprunk** [comment]
beyond-all-reason/spring@b0262344492abc3229d905221e0a8a0efce7fde4
