### ISSUE TITLE
Check bomber airpad assignment

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#5051]
Somebody claims bombers aren't coming back to pads (~~no replay~~ https://zero-k.info/Battles/Detail/1745773 but "happens almost every time I use multiple airplanes"). Perhaps it's something silly like not having airpads.

http://zero-k.info/Battles/Detail/1716941 Different claim, apparently Lichos go back to _enemy_ pads.

**Comment by Godde** [comment]
Here is an example with Likho:
https://zero-k.info/Battles/Detail/1704119
Queued commands just get ignored sometimes.
Even direct commands can get ignored in my experience.
Something weird is definitely going on.

**Comment by Godde** [comment]
It feels like there is a window when air units will ignore orders for a short while after dropping their bombs.
Maybe the window is network latency related so it doesn't show up when you test it in singleplayer.

**Comment by GoogleFrog** [comment]
12:30?

Bombers have always ignored nearby commands. The issue is a silly default for what the command means.
- What the engine thinks: The bomber has been told to fly over this position.
- What the player thinks: The bomber has been told to turn towards this position.

To do what the engine wants the bomber has to fly straight for a bit, then turn, because if it turned immediately it would just end up circling. We have pushed the turn radius hints for aircraft pretty low to fight this issue. Other things break if they get lower though.

Ideally there would be an engine change. Perhaps bombers could interpret all orders as "Turn at least 90 degrees towards the target, then fly straight to get a good angle if I have to turn around to pass over it". Because it feels like people often mean turn, not perfectly fly over.

**Comment by GoogleFrog** [comment]
The Likho at 12:30 is doing something different. I've checked the raw moves and they are getting issued.

**Comment by GoogleFrog** [comment]
A lot happens in the chicken replay and no time was given, so I will assume my "Fix" solved it.

At minute 33 in the team game (the timestamp mentioned in the thread), the Airplane Plant has a move order queued to the enemy corner of the map, and even happens to be underneath an enemy air pad. The air player left about a minute ago and had this command queued. To the player who took over it looks like their bombers are trying to land on enemy pads. But really, they are just following a command.
