### ISSUE TITLE
Re-arranging unit construction queues re-applies shift modifier

### ISSUE THREAD

**Issue by adams164** [ZeroK-RTS/Zero-K#5261]
Steps to reproduce:
 - build factory
 - hold shift + click scorcher
 - hold shift + click fencer
 - drag fencer left of scorcher
 - End result have 25 fencers queued
 
 Suspect that when re-arranging, the shift modifier is remembered and then reapplied to each unit that is moved in the build queue. Same is probably true for ctrl modifier

**Comment by GoogleFrog** [comment]
I remembered already fixing this, and was correct.
- Works in 105.1.1-1283-g43ae1fc
- Works in 105.1.1-1732-gddfe8b8
- Works in 105.1.1-2152-gb91f41c
- Works in 105.1.1-2314-g9e0bf7d
- Broken in 105.1.1-2423-g06a2622
- Broken in 105.1.1-2399-g3ac7209
- Broken in 105.1.1-2358-g9099868
- There are essentially no more builds between those commits.

**Comment by GoogleFrog** [comment]
https://github.com/beyond-all-reason/spring/commit/7eda9ad00e06aa807f992f764ae34fae8f984677

**Comment by GoogleFrog** [comment]
Actually, I am going to declare this fixed, since doing more to use the engine feature seems like a whole can of worms. Commands are still individual commands. What should you do if 2 out of 5 Ravagers are shift-built? Just copy the remaining three to the new point in the queue, with the options stripped away. There is some minor optimisation that can be done here, at the cost of code complexity.

**Comment by sprunk** [comment]
Engine fails to strip the modifier when cloning the command.

**Comment by GoogleFrog** [comment]
> Engine fails to strip the modifier when cloning the command.

Should it though?

**Comment by sprunk** [comment]
I think so, the meaning is "this order should be cloned" and an already cloned order shouldn't be cloned anymore.

More generally I think that the shift/ctrl modifiers should be removed and build orders should just have a numerical count parameter.
