### ISSUE TITLE
Default gui layout is a pillbox

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#564]
We have modern RTS designed for modern widescreen screens that has no preffered directions (like left and right). Why then is the layout taking precious vertical space isntead of horizontal?

Default should be on left or right side not entire bottom.

**Comment by Anarchid** [comment]
-> Westwood layout for Default layout?

**Comment by Orfelius** [comment]
Because this is how most modern RTS's do their UI design Licho:
SC2, GreyGoo, TotalWar, SupCom
Do you want more reasons? Cluttering every panel at one side is not good too.
Imo everythng should be split up between the screen to give tools all around player while combat should be happening in the center of the screen and bring the most attention. AND NO FOR CENTER PLACED CHAT. Seriously it just hovers over units and is being intrusive for the gameplay :(
Then some more important stuff should be placed at high left side because this is where one starts to read in most languages so most important stuff should be there. That is why rapidly changing Minimap is placed there.

**Comment by Licho1** [comment]
Like how most modern RTS do their design is complete BS argument.
ZK is not like most modern RTS and should not be! We have free camera unlike SC etc.
It has to go back to side, imo left side due to minimap resizing.

**Comment by sprunk** [comment]
The decisions regarding default GUI layout have been made in the recent interface redesign.
