### ISSUE TITLE
scythe collision volume is oversized

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K#596]
scythe collision volume is too big, see http://zero-k.info/Battles/Detail/335619 as an example. Anarchid has all details.

**Comment by Anarchid** [comment]
Likely due to deathclones dae conversion.

These are also suspect and to be investigated:

blackdawn_d.dae.lua
chainsaw_d.dae.lua
crane_d.dae.lua
eraser_d.dae.lua
flea_d.dae.lua
gauss_91_dead1.dae.lua
gnat_d.dae.lua
heavytrans_d.dae.lua
leveler_d.dae.lua
lmcarrier_dead.dae.lua
Lordmuffe_Pene_dead.dae.lua
rocko_d.dae.lua
scythe_d.dae.lua
smalltrans_d.dae.lua
starlight_d.dae.lua
storage_d.dae.lua
surfboard_d.dae.lua
zeppelin_dead.dae.lua

**Comment by sprunk** [comment]
These are 2 times as large as they should be:
>blackdawn_d.dae.lua
chainsaw_d.dae.lua
crane_d.dae.lua
eraser_d.dae.lua
flea_d.dae.lua
gnat_d.dae.lua
heavytrans_d.dae.lua
leveler_d.dae.lua
rocko_d.dae.lua
scythe_d.dae.lua
smalltrans_d.dae.lua
starlight_d.dae.lua
storage_d.dae.lua
surfboard_d.dae.lua

These are too small by a factor of 2:
>Lordmuffe_Pene_dead.dae.lua
zeppelin_dead.dae.lua

**Comment by Anarchid** [comment]
Thanks! I'll see about obediating those this evening.
