### ISSUE TITLE
Wreck collision didn't deal expected damage

### ISSUE THREAD

**Issue by xponen** [ZeroK-RTS/Zero-K#598]
based on http://youtu.be/3GSxjwLf1tY?t=23m26s (airplane crash on a mex)

I think its because when @GoogleFrog fixed shrapnel damage (to engineer Blastwing damage for balance), it was a blanket fix, meaning it effect all other circumstances too.

https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/unit_fall_damage.lua#L246

Note: I found out that diff comparison doesn't work for pre-gitHub commit. eg: https://github.com/ZeroK-RTS/Zero-K/commit/ddfc8422f1503d549fe2d164c669ebfb2fb67644

**Comment by GoogleFrog** [comment]
So much misinformation here that wastes my time.

In the video a wreck does not crash into a mex. A crashing plane crashes into a mex. Wrecks are not units. If a crashing plane hits a unit it will deal about 150 damage because that is how much damage a plane deals when it dies.

Shrapnel deals 20 damage with weaponDefID -1. This is only for shrapnel. Note that neither wreckages or units are shrapnel. If you make a unit collide with a wreck you would notice that the weaponDefID is -3.
