### ISSUE TITLE
Big Bertha can shoot through terra wall

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#651]
see here:
http://postimg.org/image/i4gvdik3n/
and http://postimg.org/image/xsi2kazpf/

dunno if it would work for other "long" cannons too

**Comment by Jamanno** [comment]
wait on those pics you cannot see that cannon from BB is surrounded by terrawall.
Also, other side had an behe and behe killed BB through terra protection wall too. So it maybe seems a bug with those unit spheres?
here is the battle link, first attempt of making BB with terraform is around 10 th minute:
http://zero-k.info/Battles/Detail/340191

**Comment by Anarchid** [comment]
On the first screenshot, bertha barrel is long enough to poke through the terraform wall. This cannot be fixed without changing the bertha model or making things look stupider than they already are.

Behe can kill things through terraform by wearing it down and/or AoE, since it should in 98+ be ignoring terrain when deciding to pwn something. Same goes for bertha. *That* part - aiming at things despite terrain - is intentional.

**Comment by sprunk** [comment]
Close as won'tfix? Not fixable without either remodelling or making the footprint ridiculously huge.
