### ISSUE TITLE
Something can still prevent game-over

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#763]
In this replay http://zero-k.info/Battles/Detail/349786 at around 40:00 the team with only a single terraunit remaining does not automatically lose.

**Comment by CarabusX** [comment]
I can confirm Skasi's replay as I was in that game too.
Another game where it happened: http://zero-k.info/Battles/Detail/349755
(this is 90 minutes long ffa so not very useful for debugging)

**Comment by ArchShaman** [comment]
This appears to be a long standing bug. As far as I can tell it's been here since v1.2.5.3. Checked on both 91 and the current default version. I can confirm it isn't an invalid unit def id causing this (checked using an echo) and I doubt it has anything to do with unittaken/given stuff as the same result is produced when I self-d my com with only a terraunit left.
