### ISSUE TITLE
Lavarise mode have missing shader.

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K#799]
Looks like it is working alright but shader isnt working thus lava is invisible.

**Comment by Anarchid** [comment]
Lavarise modoption doesn't use an actual shader, it just draws a textured plane.

**Comment by Skasi** [comment]
replay http://zero-k.info/Battles/Detail/384107

**Comment by knorker** [comment]
In this commit https://github.com/ZeroK-RTS/Zero-K/commits/master/LuaRules/Gadgets/lavarise.lua the whole graphical part of gadget was disabled in gadget (commented out)  so nothing is drawn.

**Comment by knorker** [comment]
It is not missing shaders.
The drawing-part was commented out with comment :
"-- Unsynced part should be moved to widget"

but no widget was added. https://github.com/ZeroK-RTS/Zero-K/blob/0b30472feba0745a5731516c3f22ebb03867bcf0/LuaRules/Gadgets/lavarise.lua#L150

Imo it should not be widget because the graphical effect is too important for a player to accidently disable. It is not like fog or rain widgets, it has impact on gameplay by killing units.
Imo remove this gadget, it in this state it is no use and mostly played worse than special maps.

**Comment by dvr333** [comment]
Widgets can be hidden from the f11 menu, so that's not really a reason to discard the idea. There is no reason to sync drawing code, only to sync the data used as input for the drawing code.

**Comment by sprunk** [comment]
The gadget was not removed because it was suggested that in the future it could be made into a gameside API for maps who want to have lava (like hotstepper or Zed).

**Comment by knorker** [comment]
> Whether that's a sane idea is something to consider.

imo: no.

**Comment by sprunk** [comment]
Ditto but let's hear the others.
