### ISSUE TITLE
Stalemate handling

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#807]
Stalemates can exist where neither player is able to end the game. These are very rare cases but can happen.

Decide how to handle these. Currently these games have to be voteexited which is suboptimal for various reasons (not intuitive, requires active input (won't work if someone goes afk instead of voting), game is not saved).

**Comment by Licho1** [comment]
What? We are trying to make it more likely to have stalemate - to prolong the state when either side can still win.
Example of game that could not end?

**Comment by Anarchid** [comment]
Both players are left with sets of units that are incapable of producing more units or killing the enemy.

You've detonated your last roach to kill the enemy raiders after a base trade. Now all everyone has is solars.

**Comment by sprunk** [comment]
I mean stalemate where no side can possible ever win. For example base trade rush where both facs and both comms die and the only thing left on the map are solars and turrets.

**Comment by Licho1** [comment]
this has to be exceedingly rare, did it happen in real world? For such case I think voteexit is ok as there is otherwise no handling for "no victory" games

**Comment by sprunk** [comment]
That's why the proposition to introduce such handling. It is rare and it almost always gets exited so it's hard to show any examples. It mostly happens in 1v1 when both people decide to rush each other and base trade.

Exit is bad because:
* newbies might not know !voteexit command and wait for something to happen
* the 2nd person might be AFK or for some reason not vote
* game isn't recorded

The handling would not have to be complicated. For example if no unit is created or damaged for 5 minutes then declare stalemate, this is a simple gadget with a few lines. Springie already accepts games where both teams win (currently this happens on desync) so no change required there.

**Comment by Skasi** [comment]
I suggest !draw
Add a "suggest draw to opponent" button to exit menu. In team games this would require the same number of votes as !resign but from both teams.

Alternatively there could be some more technical code that tries to find out if the game is in a real stalemate, but it has to be made in a way that does not allow abuse and there are likely going to be situations that it can not detect easy such as only two land combat units on different islands left.

**Comment by sprunk** [comment]
Votedraw is the same as voteexit. Not easy to discover and people might be unable to vote.

Checking unit creation and combat damage should do the trick.

**Comment by shaun0x00** [comment]
votedraw has other use cases, such as game becoming unplayable due to insane eco. Both teams may agree to end with a draw.
Being "hard to discover" is a GUI issue.

**Comment by sprunk** [comment]
Insane eco allows game enders and the game design should encourage ending games that way before eco gets *really* out of hand. It would be good if there was a soft "win button" unit to fulfill that role reliably. Currently starlight does that to some extent but it still attempts to be balanced.

**Comment by Orfelius** [comment]
I have once seen a draw in ZK. One team had 1 player left with 2 empty ravens vs other team's 3 schorchers. Neither side could do anything to each other.

**Comment by GoogleFrog** [comment]
Automatic draws have three big issues:
 * Players can try to abuse them with flea runaround or hard to reach aircraft. In short the draw gives them an incentive for playing an extended cat and mouse game instead of resigning.
 * The automatic detection could end unusual but otherwise interesting games (especially FFA).
 * Many people cannot be bothered watching their solars for 5 minutes to wait for the autodraw to kick in.

I like votedraw. Hard to discover is purely a UI issue. Take the example of vote resign, it is not hard to find because it is right there next to Resign and Exit. Unfortunately the vote draw button has two problems:
 * Vote draw is much less useful than Exit, Resign and Vote Resign because it would occur much less frequently. I worry about overloading the exit menu with four options when one of the options is quite useless.
 * Vote draw sends a vote to the opposing team which could be used to annoy them.

Draw handling is looking like a feature which is too complicated and rare to be worthwhile implementing at the moment. So I am going to try to ground the question in reality by considering our two use cases:
 * Custom match - Host has control over exiting the game (but to clarify the game would not end if they leave to allow them to drop and rejoin). Draws not a problem. No elo measured so recording draws is extra-not-a-problem.
 * Matchmaking - Draws are possibly a problem here. I can imagine people in 1v1 becoming stuck.

Here is my first proposed solution: 

Make some magical thing which detects when a player might want to offer a draw. When this happens put a large UI element on the side of the screen that has a single button "Offer Draw" (no other crazy features, big action buttons are simple!). When this happens the other team receives a similar box with "Accept Draw?" and 'yes/no" in it. There are two issues:
 * Invent magic (no firing units or constructors is possible? What about land units vs Hawk? Fleas vs LLT? Very hard to do well).
 * Deal with teamgames.

This still sounds like more work than is reasonable. The cost of this system not existing is that players might have to leave a game and lose elo. This may annoy them for a bit but is rare. There are areas to develop which have significantly higher return on investment.

Here is another proposal which reuses existing systems:
 * Add "Vote Exit" to the exit menu. This does bloat the menu to four options but at least there is decent symetry in Exit, Vote Exit, Resign, Vote Resign. Vote Exit is also a better name for non-draw exit situations such as if one player has a bug and the other player is nice.
 * Make exited game count as battles on the server. This should just be done anyway just for bug reporting purposes.

**Comment by sprunk** [comment]
Closing because it is of low importance.
