### ISSUE TITLE
Consider communism-reclaim

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#819]
Communism reclaim would be good to have (for the same reasons mexes are) but it is quite expensive due to AllowFeatureBuildStep. Awards already make use of that call-in though so perhaps it's possible to modify it to allow both without much added performance cost.

**Comment by xponen** [comment]
reclaim reward front player, while back player got their reward from OD return, also, IMO  communism-reclaim won't give you enough feedback to make you want to reclaim.

**Comment by CarabusX** [comment]
I am for communizing income from cons and caretakers.

But I don't see why reclaim should be shared. The person reclaiming has to spot wrecks, order cons and risks losing them, I don't see why he should lose most of the profit to team.

**Comment by sprunk** [comment]
Saying that communism reclaim doesn't give you enough reason to reclaim is just plain wrong. That's like saying nobody would make mexes after mexes started being shared.

When raiding the enemy you usually lose your raiders but don't gain anything more than other teammates.
When mexing contested places you risk losing cons too and yet mex income is shared.
I don't see why risking cons for reclaim would be different and entitle you to the whole thing.

Then there's the small issue of personal reclaim making Elo variance worse than it should be. Highly skilled people get much higher share of the team's income through reclaim than averages would dictate.

If reclaim went to everybody it would reward teamwork because you would no longer be able to solo carry the game using the massive metal income and would instead need to communicate with your teammates to harness that metal.

I think random con incomes should be removed but if that won't happen then I agree they would also benefit from communisation.

**Comment by CarabusX** [comment]
Mexes are communism not because capping them is risky, but because there is limited amount of them in team territory and only 1 player can have mex at given spot. On the other hand, while reclaim is limited too, everyone who cares about resources can join reclaiming at any time.

Speaking about mex building being risky for cons, this is why refund for placing them exists, and since personal gain is opposite of communism, the situation here and with current reclaim is exactly the same. High risk + effort -> reward is personal.

I just don't get what is the point of your idea.
Good things about current situation:
- players who are active at front get reward
- players who are efficient at killing enemy units get reward
- players who are inactive and far from combat don't get reward

Good things about your proposal:
????

**Comment by sprunk** [comment]
Reclaim is also limited. Sure many people can share one wreck field but you only get whatever the other guys don't take.

Mex refund exists but it requires the mex to survive the repay time and only covers the mex itself. If it dies you get no refund for either the mex, the LLT that you placed to protect it, nor the con that died when trying to build it.

For what it's worth I think the mex refund isn't needed in the first place (it's not like people would stop making mexes). I get no personal refund for the glaives that die when raiding either, even though it takes effort to command them and it has 100% risk because they practically always die.

"Players who are active at front get reward" is not entirely true. You can sit at the back and tek2noox but still get decent reclaim by just making cons from unassisted fac. You can also be at the front but still not get much reclaim because you're getting too pressured to afford switching away from combat units.

Good things about shared reclaim are:
* simplicity and consistency with how mex income is split. "All income is shared", period.
* promotes teamwork: if you want to make use of the metal that went to a teammates you need to communicate with them and you won't be able to solo carry the game just by getting all the reclaim.

**Comment by Orfelius** [comment]
Sprung if you want simplicity and consistency with economy then resource generation should be limited to strictly resource making units. Or their income should be also shared by communism.

**Comment by sprunk** [comment]
I know, see #798

**Comment by KlonZK** [comment]
players can already opt to share their reclaim simply by reclaiming more than they can store.

automatic reclaim sharing would have major impact on gameplay especially in larger teams because you will no longer be able to make big investments based on reclaim (unless you have a well coordinated team) - this will hurt better players and not substantially help worse ones. overall just a nerf to reclaim.

**Comment by sprunk** [comment]
>you will no longer be able to make big investments based on reclaim (unless you have a well coordinated team)

That's the whole point.

Everything will be the same as long as there is coordination. But the best player on the team won't be able to carry the game solo which I think is good because that encourages teamwork and doesn't break Elo as much.

**Comment by sprunk** [comment]
Arguments against this are legit, and the consensus seems to be keeping it private. Closing.
