### ISSUE TITLE
Consider alternative geovent usage

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#821]
Geo vents can currently only be used for energy. Consider whether a choice between energy and something else would be good.

Cons:
* CA had non-energy geos (Kettle and Behemoth) and they were removed. I don't know why but perhaps the reason still holds
* introduces additional complexity

Pros:
* introduces additional depth
* gives a reason to contest vents when going for energy is not viable (for example high wind obsoletes it, game escalates past the point where adding energy has tangible benefits, or map is too small for eco like Geyser or Avalanche)

It can be something unique (the old CA ones were fairly generic turrets). For example, an interesting usage would be to make it produce Nebula drones with a large operating radius. Or, make it offer a manual-fire weapon with the stockpile mechanic.

**Comment by GoogleFrog** [comment]
Behemoth would break maps. Tabula was particularly bad. Instead of taking a geo and holding it to get the benefit you would rush a geo and use it to control the surrounding area. The geo turret was stronger than ordinary turrets to justify the rareness of geo vents.

The Behemoth issue looks as if it would hold for other geo mechanics which increase your power in the surrounding area. Why not design a turret which is balanced to be built anywhere instead of restricting it to the geo? If you make it more powerful than normal then there is no choice, just the terrain imposing your choice. If it is not more powerful then you are just restricting the placement of a turret.

Complexity does not introduce depth. Depth comes from choices and complexity can just make the best choice harder to compute.

**Comment by GoogleFrog** [comment]
I feel like closing this also because, even if we get a working design, there are much more important things to do.

**Comment by sprunk** [comment]
It wouldn't necessarily have to be local nor a weapon; for example it could provide non-local intel  (eg. like starcraft scan sweep).

I see though that coming up with a good design wouldn't be easy and requires a lot of thought put into it so closing.
