### ISSUE TITLE
Energy sharing does not work properly

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#823]
In the case of large imbalance - say one player 10 singus, other player 0 energy outside commander, energy is not transferred properly.
Storage of 0 energy player is empty and at best there can be income of about 10-20e.
Energy producing building must be shared for 0e player to function properly even if team is in gigantic excess.
I replicated this in many games.

**Comment by xponen** [comment]
I experiment by placing 10 singu on CAI team to test energy sharing, it seem to share to me energy as we would expect.

The case experienced by @Licho1 is probably the owner of the Singu is using up all the energy in Multiplayer.

But,
A replay or replication is still needed identify what should be done.

**Comment by Licho1** [comment]
I would like to link a battle but demo was not recorded.Player (Rafal) was not using all his energy, it was mostly spent on overdrive.

**Comment by Anarchid** [comment]
what about local demo?

**Comment by GoogleFrog** [comment]
I have known that a large income difference can cause an energy stall or energy fluctuations for a while. When it comes up people tended to say that this behaviour was intended otherwise someone could spam shields with no energy and stall the entire team.

Energy fluctuations is a bug. To fix it I would remove the income from energy structures and sum up the energy structures for each allyTeam. This number would then be divided up between players as rwal income as well as be sent to overdrive.

**Comment by sprunk** [comment]
This happens because share only works on the part of income that isn't overdriven and overdrive always attempts to maximize itself given full storage.

**Comment by CarabusX** [comment]
The game Licho mentioned was in LongCat-v1, where each team has two superhuge mexes with +50M each.
I spammed singus connected to the grid and had >10 of them ODing the mexes, which gave me +1100M from OD, but the grid was still only blue, maybe this is why the energy was not shared? Or maybe I just had too many storages, but I doubt that I didn't overflow E.

**Comment by GoogleFrog** [comment]
The last two comments are wrong.

**Comment by Anarchid** [comment]
AFAICT energy has been sufficiently luaized for this to no longer occur.
