### ISSUE TITLE
Control-V Selects unfinished builders

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#834]
When having 1+ idle worker and an unfinished worker being built, it will often times select the unfinished one.

**Comment by GoogleFrog** [comment]
I think the solution is to rewrite the selectkeys implementation of Ctrl+V. Extra options could be added such as the option to exclude nanoturrets, missile silos, factories and things under construction.

**Comment by Licho1** [comment]
I think that selectkeys should entirely be written in lua, there was
excellent tool to create customized selecte keys that is no longer working
because engine implementation changed.
All of this could instead go to lua and be ingame customizable.

2015-06-15 13:59 GMT+02:00 GoogleFrog <notifications@github.com>:

**Comment by ArchShaman** [comment]
Anything is better than having to press it twice to find an actually idle con..

Very highly annoying.

**Comment by GoogleFrog** [comment]
Is this actually bad? Recently I am finding it useful to remind me to give my under construction constructors orders.

**Comment by Licho1** [comment]
I think its ok if there is no factory queue. But if you use factory queue, for example to transport units using air trans or perform other tasks, you generally want to select it only after it reaches destination. So in those cases its highly annoying
