### ISSUE TITLE
Regression: metal reserve don't appear to be working

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#863]
I enabled metal reserve in space-click on resbar options, but there is no visual indication of the reserved metal and clicking the resbar wont change reservation.

**Comment by sprunk** [comment]
It's now ctrl_click to prevent accidential clicking

**Comment by GoogleFrog** [comment]
"Ctrl+Click on the resource bars will set reserve when enabled. Low and Normal priority constructors cannot use resources in reserve storage." - options.enableReserveBar.desc

This change is so that reserve can be enabled by default (which it is) without worrying about accidental clicking. Left click is still to set one bar and right click sets them both at once. Reopen if ctrl+click doesn't work.

**Comment by Licho1** [comment]
Whats the point ofna feature that even game's own developer cannot diacover
and use? Insteadvreserve can be left click and give proper feedback
Dne 21.6.2015 5:35 napsal uživatel "GoogleFrog" <notifications@github.com>:

**Comment by sprunk** [comment]
Veteran bias, you knew what reserve is, knew some old bindings and expected they still apply.

Newbies won't assume things beforehand and will read the tooltip to learn what reserve is so they will also get to know the controls.

**Comment by GoogleFrog** [comment]
Left click leads to accidental reserve setting which causes apparent bugs where constructors do not work. The only hint someone has that reserve exists and that they have accidentally set it is the white diagonal lines on the resource bar. Left click reserve was too dangerous to have enabled by default.
I even set reserve accidentally when it was just left click.

This reserve has the benefit that it is easier to tell people about. Simply say "Ctrl+Click on the resource bar" instead of telling them how to navigate the options menu and enable reserve.

**Comment by Licho1** [comment]
Ok in that case it should be enabled by default and visible in tooltip (its not visible in tooltip, only in settings tooltip).
Another option would be confirmation of action. But ctrl+click + tooltip info is good imo.
