### ISSUE TITLE
Command queue draws white box for solars below the map

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#935]
This happens for both pregame- and midgame queue. Below the map you can see small white boxes. They appear where there are solars queued and only show up in cases where the queue is drawn.

![screen00557](https://cloud.githubusercontent.com/assets/132906/8805260/925a0c98-2fd0-11e5-8c31-560654827bad.png)
![screen00555](https://cloud.githubusercontent.com/assets/132906/8805262/925f9014-2fd0-11e5-9c52-2ae1ba0bcfb9.png)

**Comment by sprunk** [comment]
This is because queued Solars would normally look wrong when queued, so they get a fake piece that looks properly for queue purposes. The ugly one is "hidden" by moving it away as there seems to be no way to really hide them.

This should be solvable by hiding them in a better place (stratosphere probably). I'll make an attempt on this.

**Comment by CarabusX** [comment]
Perhaps Solars could be fixed to look properly by changing piece positions in the model, and then moving them back at the start of the script so they still start closed?

**Comment by GoogleFrog** [comment]
I like the model modification idea.

**Comment by sprunk** [comment]
I've tried that and it involves lots of weirdness. It should be doable but felt hard.
