### ISSUE TITLE
Daggers fires at high altitude units which are outside its spherical range.

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K#938]
1) Spawn daggers for team 0
2) Spawn vindicator or brawler for team 1.
3) Move them together, keep GS in fly-on state
4) Observe daggers can't damage flying gunships

**Comment by lhog** [comment]
Just a side note, that for instance glaives can attack high altitude units (e.g. vindicator or brawler) although their range is less than range of dagger.

**Comment by sprunk** [comment]
Dagger targeting is parabolic because its weapontype is Cannon. For this reason it attempts to shoot stuff differently than spherical range (note it also holds for targets too deep below). Glaive also has a Cannon so shoots things out of the sphere.

However Dagger also has noExplode. This makes its range spherical without affecting targeting. This can't be removed because it's responsible for the piercing.

A ZK-side solution would be to make it use another weapon type, with spherical range. Alternatively, engine could be amended to use spherical targeting for spherical Cannons but this is the harder path to enforce because it affects other games.

**Comment by Anarchid** [comment]
It's not possible to use LaserCannon for Gauss because LaserCannon projectiles don't change their direction after bouncing. But perhaps MissileLauncher could work. If done extra right, it might also solve the extra long trail particle segments (by replacing them with missile ribbon).

**Comment by sprunk** [comment]
MissileLauncher is not spherical. It'd significantly change behaviour.

LaserCannon can have bounce fixed engine-side and become useful. It still has slightly different behaviour but not much.

The other option is EmgCannon. This one is ugly but seems to have proper behaviour so should suffice after some engine fixes (currently hardcoded to use map gravity).

**Comment by Anarchid** [comment]
Fixed LaserCannon seems superior because Gauss looks pretty much just like LaserCannon.

**Comment by GoogleFrog** [comment]
HeightMod = 1 does not fix this.

**Comment by sprunk** [comment]
https://github.com/spring/spring/pull/302
