### ISSUE TITLE
(v1.3.8.10) Commander-Selector comes up when rejoining game

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K#995]
1) Play game for some time

2) crash / lag out / leave

3) rejoin

4) the Commander-Selector menu will appear.
Since the game is already running and com already choosen it servers no purpose.

**Comment by GoogleFrog** [comment]
Steps to fix:
 1. Check whether teams with spawned commanders have a TeamRulesParam set. If not then create one.
 2. Disable the Commander Selector menu during catchup.
 3. Enable the Commander Selector menu only if the TeamRulesParam indicates that a commander has not been selected.

The check and possibility of enabling the selector is because someone may rejoin at the start of the game and miss the first few seconds. When this occurs they are (currently) still able to choose their commander.

**Comment by GoogleFrog** [comment]
It looks like widget:GameProgress can be used to tell whether you are rejoining or live.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/a2e77cd3bbce6e48327e44f983e28054225841d7
